const B1_STORIES = [
    {
        "id": "green_hero",
        "title": "The Green Hero",
        "level": "B1",
        "cover": "images/b1/green_future/cover.jpg",
        "description": "Alex started a recycling project to save the city park.",
        "vocabulary": [
            {
                "word": "Environment",
                "translation": "สิ่งแวดล้อม"
            },
            {
                "word": "Recycle",
                "translation": "รีไซเคิล"
            },
            {
                "word": "Pollution",
                "translation": "มลพิษ"
            }
        ],
        "chapters": [
            {
                "title": "A Messy Park",
                "content": "Alex has lived in this city for ten years. Recently, he has noticed a lot of pollution in the local park. People throw plastic bottles and paper everywhere. He felt very sad about the environment.",
                "image": "images/b1/green_future/ch1.jpg",
                "color": "#f0fdf4",
                "visual_type": "green_pollution"
            },
            {
                "title": "The Great Idea",
                "content": "\"We must do something!\" Alex thought. He decided to start a recycling campaign. He has already talked to his school principal and his neighbors. Most people have agreed to help him.",
                "image": "images/b1/green_future/ch2.jpg",
                "color": "#ecfdf5",
                "visual_type": "green_idea"
            },
            {
                "title": "Community Action",
                "content": "Last Saturday, the community worked together. They collected five hundred bags of waste. Alex has organized different bins for plastic, glass, and paper. It was a huge success for sustainability.",
                "image": "images/b1/green_future/ch3.jpg",
                "color": "#dcfce7",
                "visual_type": "green_action"
            },
            {
                "title": "Visible Impact",
                "content": "The park has never looked better. The grass is green, and the flowers are blooming again. If we work together, we can protect our planet. Many children have started to join the Green Club.",
                "image": "images/b1/green_future/ch4.jpg",
                "color": "#bbf7d0",
                "visual_type": "green_impact"
            },
            {
                "title": "Future Plans",
                "content": "Alex hasn't finished his mission yet. He wants to plant one hundred new trees next month. If he gets more support, he will build a small garden for everyone. He is a true green hero.",
                "image": "images/b1/green_future/ch5.jpg",
                "color": "#86efac",
                "visual_type": "green_hero"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "a lot of": "จำนวนมาก",
            "about": "เกี่ยวกับ",
            "again": "อีกครั้ง",
            "agreed": "เห็นด้วย",
            "alex": "อเล็กซ์",
            "already": "แล้ว",
            "and": "และ",
            "are": "เป็น/อยู่/คือ",
            "bags": "ถุง",
            "better": "ดีขึ้น",
            "bins": "ถังขยะ",
            "blooming": "กำลังบาน",
            "bottles": "ขวด",
            "build": "สร้าง",
            "campaign": "การรณรงค์",
            "can": "สามารถ",
            "children": "เด็กๆ",
            "city": "เมือง",
            "club": "ชมรม",
            "collected": "รวบรวม",
            "community": "ชุมชน",
            "decided": "ตัดสินใจ",
            "different": "ที่แตกต่าง",
            "do": "ทำ",
            "environment": "สิ่งแวดล้อม",
            "everyone": "ทุกคน",
            "everywhere": "ทุกที่",
            "felt": "รู้สึก",
            "finished": "เสร็จสิ้น",
            "five": "ห้า",
            "five hundred": "ห้าร้อย",
            "flowers": "ดอกไม้",
            "for": "เป็นเวลา",
            "garden": "สวน",
            "gets": "ได้รับ",
            "glass": "แก้ว",
            "grass": "หญ้า",
            "green": "สีเขียว",
            "has": "มี/ได้",
            "hasn't": "ยังไม่",
            "have": "มี/ได้ (ปัจจุบัน)",
            "he": "เขา",
            "help": "ช่วย",
            "hero": "ฮีโร่",
            "him": "เขา",
            "his": "ของเขา",
            "huge": "ใหญ่โต",
            "hundred": "ร้อย",
            "if": "ถ้า",
            "in": "ใน",
            "is": "เป็น",
            "it": "มัน",
            "join": "เข้าร่วม",
            "last": "ที่แล้ว",
            "lived": "อาศัยอยู่",
            "local": "ท้องถิ่น",
            "looked": "ดูเหมือน",
            "lot": "จำนวนมาก",
            "many": "มากมาย",
            "mission": "ภารกิจ",
            "month": "เดือน",
            "more": "มากขึ้น",
            "most": "ส่วนใหญ่",
            "must": "ต้อง",
            "neighbors": "เพื่อนบ้าน",
            "never": "ไม่เคย",
            "new": "ใหม่",
            "next": "ถัดไป",
            "noticed": "สังเกตเห็น",
            "of": "ของ",
            "one": "หนึ่ง",
            "one hundred": "หนึ่งร้อย",
            "organized": "จัดระเบียบ",
            "our": "ของเรา",
            "paper": "กระดาษ",
            "park": "สวนสาธารณะ",
            "people": "ผู้คน",
            "planet": "โลก",
            "plant": "ปลูก",
            "plastic": "พลาสติก",
            "pollution": "มลภาวะ",
            "principal": "ครูใหญ่",
            "protect": "ปกป้อง",
            "recently": "เมื่อเร็วๆ นี้",
            "recycling": "การรีไซเคิล",
            "sad": "เศร้า",
            "saturday": "วันเสาร์",
            "school": "โรงเรียน",
            "small": "เล็ก",
            "something": "บางอย่าง",
            "start": "เริ่ม",
            "started": "เริ่ม",
            "success": "ความสำเร็จ",
            "support": "การสนับสนุน",
            "sustainability": "ความยั่งยืน",
            "talked": "พูดคุย",
            "ten": "สิบ",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "they": "พวกเขา",
            "this": "นี้",
            "thought": "คิด",
            "throw": "ทิ้ง/ขว้าง",
            "to": "กับ",
            "together": "ด้วยกัน",
            "trees": "ต้นไม้",
            "true": "ที่แท้จริง",
            "very": "มาก",
            "wants": "ต้องการ",
            "was": "เป็น",
            "waste": "ขยะ",
            "we": "พวกเรา",
            "will": "จะ",
            "work": "งาน/ทำงาน",
            "worked": "ทำงาน",
            "years": "ปี",
            "yet": "ยัง"
        }
    },
    {
        "id": "job_interview",
        "title": "A Big Opportunity",
        "level": "B1",
        "cover": "images/b1/job/cover.jpg",
        "description": "Mark prepared for his first professional job interview.",
        "vocabulary": [
            {
                "word": "Interview",
                "translation": "สัมภาษณ์"
            },
            {
                "word": "Professional",
                "translation": "มืออาชีพ"
            },
            {
                "word": "Nervous",
                "translation": "ประหม่า"
            }
        ],
        "chapters": [
            {
                "title": "The Invitation",
                "content": "Mark has been looking for a job for three months. Yesterday, he received an email from a big company. They invited him for a professional interview. He felt very excited but a bit nervous.",
                "image": "images/b1/job/ch1.jpg",
                "color": "#f8fafc",
                "visual_type": "job_invitation"
            },
            {
                "title": "Preparation",
                "content": "He has already researched the company's history. He bought a new suit and practiced his answers. \"I must be confident,\" he told himself. He wants to get the position of marketing assistant.",
                "image": "images/b1/job/ch2.jpg",
                "color": "#f1f5f9",
                "visual_type": "job_prep"
            },
            {
                "title": "The Interview Day",
                "content": "The interview started at 10 a.m. The office was very modern and clean. He met the manager, Mrs. Smith. She asked him many questions about his skills and experience.",
                "image": "images/b1/job/ch3.jpg",
                "color": "#eff6ff",
                "visual_type": "job_interview"
            },
            {
                "title": "Sharing Success",
                "content": "Mark talked about his university projects. He has worked on several successful campaigns. Mrs. Smith smiled and nodded. Mark felt more relaxed and confident during the conversation.",
                "image": "images/b1/job/ch4.jpg",
                "color": "#dcfce7",
                "visual_type": "job_success"
            },
            {
                "title": "The Result",
                "content": "After two days, Mark received another email. He got the job! He was very happy and called his parents immediately. This is a big opportunity for his professional career.",
                "image": "images/b1/job/ch5.jpg",
                "color": "#fdf4ff",
                "visual_type": "job_result"
            }
        ],
        "full_dictionary": {
            "10 a.m.": "10 โมงเช้า",
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "about": "เกี่ยวกับ",
            "after": "หลังจาก",
            "already": "แล้ว",
            "an": "หนึ่ง/อัน (ไม่เจาะจง)",
            "and": "และ",
            "another": "อื่น",
            "answers": "คำตอบ",
            "asked": "ถาม",
            "assistant": "ผู้ช่วย",
            "at": "ที่",
            "be": "เป็น",
            "been": "เป็น/อยู่",
            "big": "ใหญ่",
            "bit": "เล็กน้อย",
            "bought": "ซื้อ",
            "but": "แต่",
            "called": "โทรหา",
            "campaigns": "การรณรงค์",
            "career": "อาชีพ",
            "clean": "สะอาด",
            "company": "บริษัท",
            "company's": "ของบริษัท",
            "confident": "มั่นใจ",
            "conversation": "บทสนทนา",
            "days": "วัน (หลายวัน)",
            "during": "ระหว่าง",
            "email": "อีเมล",
            "excited": "ตื่นเต้น",
            "experience": "ประสบการณ์",
            "felt": "รู้สึก",
            "for": "สำหรับ/เป็นเวลา",
            "from": "จาก",
            "get": "ได้รับ",
            "got": "ได้รับ",
            "happy": "มีความสุข",
            "has": "มี/ได้",
            "he": "เขา",
            "him": "เขา",
            "himself": "ตัวเอง",
            "his": "ของเขา",
            "history": "ประวัติศาสตร์",
            "i": "ฉัน",
            "immediately": "ทันที",
            "interview": "สัมภาษณ์",
            "invited": "เชิญ",
            "is": "เป็น/อยู่/คือ",
            "job": "งาน",
            "looking": "มองหา",
            "m": "(ใน a.m.) เช้า",
            "manager": "ผู้จัดการ",
            "many": "มากมาย",
            "mark": "มาร์ค",
            "marketing": "การตลาด",
            "met": "พบ",
            "modern": "ทันสมัย",
            "months": "เดือน",
            "more": "มากขึ้น",
            "mrs": "นาง",
            "must": "ต้อง",
            "nervous": "ประหม่า",
            "new": "ใหม่",
            "nodded": "พยักหน้า",
            "of": "ของ",
            "office": "สำนักงาน",
            "on": "บน",
            "opportunity": "โอกาส",
            "parents": "พ่อแม่",
            "position": "ตำแหน่ง",
            "practiced": "ฝึกซ้อม",
            "professional": "มืออาชีพ",
            "projects": "โครงการ",
            "questions": "คำถาม",
            "received": "ได้รับ",
            "relaxed": "ผ่อนคลาย",
            "researched": "วิจัย",
            "several": "หลาย",
            "she": "เธอ",
            "skills": "ทักษะ",
            "smiled": "ยิ้ม",
            "smith": "สมิธ",
            "started": "เริ่ม",
            "successful": "ประสบความสำเร็จ",
            "suit": "ชุดสูท",
            "talked": "พูดคุย",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "they": "พวกเรา",
            "this": "นี่",
            "three": "สาม",
            "three months": "สามเดือน",
            "to": "ถึง/ไปยัง",
            "told": "บอก",
            "two": "สอง",
            "two days": "สองวัน",
            "university": "มหาวิทยาลัย",
            "very": "มาก",
            "wants": "ต้องการ",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "worked": "ทำงาน",
            "yesterday": "เมื่อวาน"
        }
    },
    {
        "id": "lost_key_b1",
        "title": "Mystery of the Key",
        "level": "B1",
        "cover": "images/b1/lost_key/cover.jpg",
        "description": "A deeper look into the mystery of the old garden box.",
        "vocabulary": [
            {
                "word": "Mystery",
                "translation": "ความลับ/ปริศนา"
            },
            {
                "word": "Discovery",
                "translation": "การค้นพบ"
            },
            {
                "word": "Artifact",
                "translation": "โบราณวัตถุ"
            }
        ],
        "chapters": [
            {
                "title": "Unlocking History",
                "content": "Tom found a gold key in the garden last week. Since then, he has spent every evening studying the old box. He believes the box belonged to his ancestors. His curiosity is growing.",
                "image": "images/b1/lost_key/ch1.jpg",
                "color": "#fef9c3",
                "visual_type": "unlock_history"
            },
            {
                "title": "The Old Map",
                "content": "Inside the box, there was a map. It wasn't a normal map of the garden; it showed hidden tunnels under the house. Tom has never seen anything like this before.",
                "image": "images/b1/lost_key/ch2.jpg",
                "color": "#fdfcf0",
                "visual_type": "old_map"
            },
            {
                "title": "Researching Artifacts",
                "content": "Tom went to the library to research the artifacts. He has read three books about the city's history. He found out that his house was built on an ancient site.",
                "image": "images/b1/lost_key/ch3.jpg",
                "color": "#f1f5f9",
                "visual_type": "research_artifacts"
            },
            {
                "title": "Secret Discovery",
                "content": "He invited Anna to help him. They have already found the entrance to the first tunnel. It was hidden behind a heavy bookshelf. They felt like real explorers.",
                "image": "images/b1/lost_key/ch4.jpg",
                "color": "#e2e8f0",
                "visual_type": "secret_entrance"
            },
            {
                "title": "Family Legacy",
                "content": "The box also contained an old letter. It explained the family legacy. Tom has finally understood the importance of protecting his home's secrets for future generations.",
                "image": "images/b1/lost_key/ch5.jpg",
                "color": "#fefce8",
                "visual_type": "family_legacy"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "about": "เกี่ยวกับ",
            "already": "แล้ว",
            "also": "เช่นกัน",
            "an": "หนึ่ง/อัน (ไม่เจาะจง)",
            "ancestors": "บรรพบุรุษ",
            "ancient": "โบราณ",
            "anna": "แอนนา",
            "anything": "บางสิ่งบางอย่าง",
            "artifacts": "โบราณวัตถุ",
            "before": "ก่อน",
            "behind": "ข้างหลัง",
            "believes": "เชื่อ",
            "belonged": "เป็นของ",
            "books": "หนังสือหลายเล่ม",
            "bookshelf": "ชั้นหนังสือ",
            "box": "กล่อง",
            "built": "สร้าง",
            "city's": "ของเมือง",
            "contained": "บรรจุ",
            "curiosity": "ความอยากรู้อยากเห็น",
            "entrance": "ทางเข้า",
            "evening": "ตอนเย็น",
            "every": "ทุกๆ",
            "explained": "อธิบาย",
            "explorers": "นักสำรวจ",
            "family": "ครอบครัว",
            "felt": "รู้สึก",
            "finally": "ในที่สุด",
            "first": "แรก",
            "for": "สำหรับ/เป็นเวลา",
            "found": "พบ",
            "found out": "ค้นพบ",
            "future": "อนาคต",
            "garden": "สวน",
            "generations": "รุ่น",
            "gold": "ทอง",
            "growing": "กำลังเติบโต",
            "has": "มี/ได้ (ปัจจุบัน)",
            "have": "มี/ได้ (ปัจจุบัน)",
            "he": "เขา",
            "heavy": "หนัก",
            "help": "ช่วย",
            "hidden": "ที่ซ่อนอยู่",
            "him": "เขา (กรรม)",
            "his": "ของเขา",
            "history": "ประวัติศาสตร์",
            "home's": "ของบ้าน",
            "house": "บ้าน",
            "importance": "ความสำคัญ",
            "in": "ใน",
            "inside": "ข้างใน",
            "invited": "เชิญ",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "key": "กุญแจ",
            "last": "ที่แล้ว/สุดท้าย",
            "last week": "สัปดาห์ที่แล้ว",
            "legacy": "มรดก",
            "letter": "จดหมาย",
            "library": "ห้องสมุด",
            "like": "ชอบ/เหมือน",
            "like this": "แบบนี้",
            "map": "แผนที่",
            "never": "ไม่เคย",
            "normal": "ปกติ",
            "of": "ของ",
            "old": "เก่า",
            "on": "บน",
            "out": "ออก",
            "protecting": "การปกป้อง",
            "read": "อ่าน",
            "real": "จริง",
            "research": "วิจัย",
            "secrets": "ความลับ",
            "seen": "เห็น",
            "showed": "แสดง",
            "since": "ตั้งแต่",
            "since then": "ตั้งแต่นั้นมา",
            "site": "สถานที่",
            "spent": "ใช้เวลา",
            "studying": "กำลังศึกษา",
            "that": "นั้น",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "then": "ตอนนั้น/หลังจากนั้น",
            "there": "ที่นั่น",
            "they": "พวกเรา",
            "this": "นี้",
            "three": "สาม",
            "three books": "หนังสือสามเล่ม",
            "to": "ถึง/ไปยัง",
            "tom": "ทอม",
            "tunnel": "อุโมงค์",
            "tunnels": "อุโมงค์",
            "under": "ใต้",
            "understood": "เข้าใจ",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "wasn't": "ไม่ใช่",
            "week": "สัปดาห์",
            "went": "ไป"
        }
    },
    {
        "id": "bakery_b1",
        "title": "The Bakery Secret",
        "level": "B1",
        "cover": "images/b1/bakery/cover.jpg",
        "description": "Mia discovers the truth about the magic bakery.",
        "vocabulary": [
            {
                "word": "Delicious",
                "translation": "อร่อย"
            },
            {
                "word": "Fragrant",
                "translation": "หอม"
            },
            {
                "word": "Enchanted",
                "translation": "ต้องมนตร์"
            }
        ],
        "chapters": [
            {
                "title": "A Fragrant Village",
                "content": "The village has always been famous for its fragrant bread. Mia has visited the bakery many times, but she has never seen the ingredients. The bread is simply delicious.",
                "image": "images/b1/bakery/ch1.jpg",
                "color": "#fffbeb",
                "visual_type": "bakery_village"
            },
            {
                "title": "The Secret Oven",
                "content": "One evening, Mia followed the blue bird. It led her to an enchanted oven. She has realized that the bakery uses ancient magic to create its special flavors.",
                "image": "images/b1/bakery/ch2.jpg",
                "color": "#fefce8",
                "visual_type": "enchanted_oven"
            },
            {
                "title": "Generations of Baking",
                "content": "She found an old recipe book. The village has kept this tradition for hundreds of years. Every baker has been a guardian of the secret magic.",
                "image": "images/b1/bakery/ch3.jpg",
                "color": "#fdfcf0",
                "visual_type": "recipe_book"
            },
            {
                "title": "Magic Ingredients",
                "content": "The bird showed her magic flour from the mountains. Mia has learned that the best bread requires more than just water and yeast; it needs heart and soul.",
                "image": "images/b1/bakery/ch4.jpg",
                "color": "#fff7ed",
                "visual_type": "magic_flour"
            },
            {
                "title": "A New Guardian",
                "content": "Mia has promised to keep the secret. She has become the next guardian of the village tradition. The magic bakery will continue to smell sweet for many years.",
                "image": "images/b1/bakery/ch5.jpg",
                "color": "#faf5ff",
                "visual_type": "new_guardian"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "always": "เสมอ",
            "an": "หนึ่ง/อัน (ไม่เจาะจง)",
            "ancient": "โบราณ",
            "and": "และ",
            "baker": "คนทำขนมปัง",
            "bakery": "ร้านขนมปัง",
            "become": "กลายเป็น",
            "been": "เป็น/อยู่/มา",
            "best": "ดีที่สุด",
            "bird": "นก",
            "blue": "สีน้ำเงิน/สีฟ้า",
            "blue bird": "นกสีน้ำเงิน",
            "book": "หนังสือ",
            "bread": "ขนมปัง",
            "but": "แต่",
            "continue": "ดำเนินต่อไป",
            "create": "สร้าง",
            "delicious": "อร่อย",
            "enchanted": "ต้องมนตร์",
            "evening": "ตอนเย็น",
            "every": "ทุกๆ",
            "famous": "มีชื่อเสียง",
            "flavors": "รสชาติ",
            "flour": "แป้ง",
            "followed": "ตาม",
            "for": "สำหรับ/เป็นเวลา",
            "found": "พบ",
            "fragrant": "หอม",
            "from": "จาก",
            "guardian": "ผู้พิทักษ์",
            "has": "มี/ได้ (ปัจจุบัน)",
            "heart": "หัวใจ",
            "her": "ของเธอ/เธอ",
            "hundreds": "หลายร้อย",
            "hundreds of years": "หลายร้อยปี",
            "ingredients": "วัตถุดิบ",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "its": "ของมัน",
            "just": "เพิ่งจะ/แค่",
            "keep": "เก็บ/รักษา",
            "kept": "เก็บรักษา",
            "learned": "เรียนรู้",
            "led": "นำ",
            "magic": "เวทมนตร์",
            "many": "มากมาย",
            "many times": "หลายครั้ง",
            "mia": "เมีย",
            "more": "มากขึ้น",
            "mountain": "ภูเขา",
            "mountains": "ภูเขา",
            "needs": "ต้องการ",
            "never": "ไม่เคย",
            "next": "ถัดไป",
            "of": "ของ",
            "old": "เก่า",
            "one": "หนึ่ง",
            "one evening": "เย็นวันหนึ่ง",
            "oven": "เตาอบ",
            "promised": "สัญญา",
            "realized": "ตระหนัก",
            "recipe": "สูตรอาหาร",
            "recipe book": "หนังสือสูตรอาหาร",
            "requires": "ต้องการ",
            "secret": "ความลับ",
            "seen": "เห็น",
            "she": "เธอ",
            "showed": "แสดง (อดีต)",
            "simply": "เรียบง่าย",
            "smell": "กลิ่น",
            "soul": "วิญญาณ",
            "special": "พิเศษ",
            "sweet": "หวาน",
            "than": "กว่า",
            "that": "นั้น",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "this": "นี้",
            "times": "ครั้ง",
            "to": "ถึง/ไปยัง",
            "tradition": "ประเพณี",
            "uses": "ใช้",
            "village": "หมู่บ้าน",
            "visited": "เยี่ยมชม",
            "water": "น้ำ",
            "will": "จะ",
            "years": "ปี (หลายปี)",
            "yeast": "ยีสต์"
        }
    },
    {
        "id": "beach_adventure",
        "title": "Adventure at the Shore",
        "level": "B1",
        "cover": "images/b1/beach/cover.jpg",
        "description": "Sam and Lily explore a hidden cave at the beach.",
        "vocabulary": [
            {
                "word": "Adventure",
                "translation": "การผจญภัย"
            },
            {
                "word": "Treasure",
                "translation": "ขุมทรัพย์"
            },
            {
                "word": "Explore",
                "translation": "สำรวจ"
            }
        ],
        "chapters": [
            {
                "title": "The Hidden Cave",
                "content": "Sam and Lily have visited this beach every summer. Today, they have discovered a hidden cave near the rocks. It only appears during low tide.",
                "image": "images/b1/beach/ch1.jpg",
                "color": "#e0f2fe",
                "visual_type": "hidden_cave"
            },
            {
                "title": "Entering the Dark",
                "content": "They brought a flashlight to explore the darkness. The air inside was cool and salty. They have never felt so excited about an adventure before.",
                "image": "images/b1/beach/ch2.jpg",
                "color": "#1e293b",
                "visual_type": "dark_cave"
            },
            {
                "title": "Shiny Objects",
                "content": "Deep inside, they saw something shiny. Lily has found an old box filled with silver coins. They couldn't believe their eyes. Was it real treasure?",
                "image": "images/b1/beach/ch3.jpg",
                "color": "#0f172a",
                "visual_type": "shiny_treasure"
            },
            {
                "title": "The Old Legend",
                "content": "Sam has read about pirates in this area. According to the legend, they hid their gold in mysterious caves. This discovery has changed their holiday forever.",
                "image": "images/b1/beach/ch4.jpg",
                "color": "#334155",
                "visual_type": "pirate_legend"
            },
            {
                "title": "Safety First",
                "content": "The tide started to rise, so they had to leave. They have reported their discovery to the local museum. They are now famous young explorers.",
                "image": "images/b1/beach/ch5.jpg",
                "color": "#bae6fd",
                "visual_type": "explorers_beach"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "about": "เกี่ยวกับ",
            "according": "ตามที่",
            "according to": "ตามที่",
            "adventure": "การผจญภัย",
            "air": "อากาศ",
            "an": "หนึ่ง/อัน (ไม่เจาะจง)",
            "and": "และ",
            "appears": "ปรากฏ",
            "are": "เป็น/อยู่/คือ",
            "area": "พื้นที่",
            "beach": "ชายหาด",
            "before": "ก่อน",
            "believe": "เชื่อ",
            "box": "กล่อง",
            "brought": "นำมา",
            "cave": "ถ้ำ",
            "caves": "ถ้ำ",
            "changed": "เปลี่ยน",
            "coins": "เหรียญ",
            "cool": "เย็น",
            "couldn't": "ไม่สามารถ",
            "couldn't believe": "ไม่สามารถเชื่อได้",
            "darkness": "ความมืด",
            "deep": "ลึก",
            "discovered": "ค้นพบ",
            "discovery": "การค้นพบ",
            "during": "ระหว่าง",
            "every": "ทุกๆ",
            "every summer": "ทุกฤดูร้อน",
            "excited": "ตื่นเต้น",
            "explore": "สำรวจ",
            "explorers": "นักสำรวจ",
            "eyes": "ตา",
            "famous": "มีชื่อเสียง",
            "felt": "รู้สึก",
            "filled": "เต็มไปด้วย",
            "flashlight": "ไฟฉาย",
            "forever": "ตลอดไป",
            "found": "พบ",
            "gold": "ทอง",
            "had": "มี/ได้ (อดีต)",
            "has": "มี/ได้ (ปัจจุบัน)",
            "have": "มี/ได้ (ปัจจุบัน)",
            "hid": "ซ่อน",
            "hidden": "ที่ซ่อนอยู่",
            "holiday": "วันหยุด",
            "in": "ใน",
            "inside": "ข้างใน",
            "it": "มัน",
            "leave": "ออกไป",
            "legend": "ตำนาน",
            "lily": "ลิลลี่",
            "local": "ท้องถิ่น",
            "low": "ต่ำ",
            "low tide": "น้ำลด",
            "museum": "พิพิธภัณฑ์",
            "mysterious": "ลึกลับ",
            "near": "ใกล้",
            "never": "ไม่เคย",
            "now": "ตอนนี้",
            "old": "เก่า",
            "only": "เท่านั้น",
            "pirates": "โจรสลัด",
            "read": "อ่าน",
            "real": "จริง",
            "reported": "รายงาน",
            "rise": "เพิ่มขึ้น",
            "rocks": "หิน",
            "salty": "เค็ม",
            "sam": "แซม",
            "saw": "เห็น",
            "shiny": "เงางาม",
            "silver": "เงิน",
            "silver coins": "เหรียญเงิน",
            "so": "ดังนั้น/มาก",
            "something": "บางอย่าง",
            "started": "เริ่ม",
            "summer": "ฤดูร้อน",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "their": "ของพวกเขา",
            "they": "พวกเรา",
            "this": "นี้",
            "tide": "น้ำขึ้นน้ำลง",
            "to": "ถึง/ไปยัง",
            "today": "วันนี้",
            "treasure": "ขุมทรัพย์",
            "visited": "เยี่ยมชม",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "with": "กับ",
            "young": "อายุน้อย"
        }
    },
    {
        "id": "robot_friend_b1",
        "title": "The Robot Project",
        "level": "B1",
        "cover": "images/b1/robot_comp/cover.jpg",
        "description": "Ben builds a smart robot for the school competition.",
        "vocabulary": [
            {
                "word": "Invention",
                "translation": "สิ่งประดิษฐ์"
            },
            {
                "word": "Program",
                "translation": "โปรแกรม"
            },
            {
                "word": "Circuit",
                "translation": "วงจร"
            }
        ],
        "chapters": [
            {
                "title": "The Vision",
                "content": "Ben has always loved technology. This year, he has decided to build a robot with artificial intelligence. He spent months drawing the blueprints and ordering parts.",
                "image": "images/b1/robot_comp/ch1.jpg",
                "color": "#f8fafc",
                "visual_type": "robot_vision"
            },
            {
                "title": "Assembling Parts",
                "content": "He has already assembled the metal frame and the complex circuits. Ben is very careful because one small mistake could ruin the whole project. His father has helped him with the heavy tools.",
                "image": "images/b1/robot_comp/ch2.jpg",
                "color": "#f1f5f9",
                "visual_type": "robot_assembly"
            },
            {
                "title": "Coding the Mind",
                "content": "The most difficult part is coding. Ben has written thousands of lines of code. He wants the robot to recognize voices and respond to simple commands. It's a huge challenge.",
                "image": "images/b1/robot_comp/ch3.jpg",
                "color": "#e2e8f0",
                "visual_type": "robot_coding"
            },
            {
                "title": "First Test",
                "content": "Yesterday, Ben performed the first test. The robot moved its arm and said, \"Hello, Ben.\" He felt incredibly proud. All his hard work has finally paid off.",
                "image": "images/b1/robot_comp/ch4.jpg",
                "color": "#eff6ff",
                "visual_type": "robot_test"
            },
            {
                "title": "The Competition",
                "content": "Ben has entered the school science competition. Many people have praised his invention. He believes that robots will play a big role in the future of humanity.",
                "image": "images/b1/robot_comp/ch5.jpg",
                "color": "#dcfce7",
                "visual_type": "robot_competition"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "all": "ทั้งหมด",
            "already": "แล้ว",
            "always": "เสมอ",
            "and": "และ",
            "arm": "แขน",
            "artificial": "เทียม/สังเคราะห์",
            "artificial intelligence": "ปัญญาประดิษฐ์",
            "assembled": "ประกอบ",
            "because": "เพราะว่า",
            "believes": "เชื่อ",
            "ben": "เบน",
            "big": "ใหญ่",
            "blueprints": "พิมพ์เขียว",
            "build": "สร้าง",
            "careful": "ระมัดระวัง",
            "challenge": "ความท้าทาย",
            "circuits": "วงจร",
            "code": "โค้ด",
            "coding": "การเขียนโค้ด",
            "commands": "คำสั่ง",
            "competition": "การแข่งขัน",
            "complex": "ซับซ้อน",
            "could": "สามารถ/อาจจะ",
            "decided": "ตัดสินใจ",
            "difficult": "ยาก",
            "drawing": "กำลังวาด",
            "entered": "เข้าร่วม",
            "father": "พ่อ",
            "felt": "รู้สึก",
            "finally": "ในที่สุด",
            "first": "แรก",
            "frame": "โครง/กรอบ",
            "future": "อนาคต",
            "hard": "ยาก/หนัก",
            "hard work": "งานหนัก",
            "has": "มี/ได้ (ปัจจุบัน)",
            "have": "มี/ได้ (ปัจจุบัน)",
            "he": "เขา",
            "heavy": "หนัก",
            "heavy tools": "เครื่องมือหนัก",
            "hello": "สวัสดี",
            "helped": "ช่วย",
            "him": "เขา (กรรม)",
            "his": "ของเขา",
            "huge": "ใหญ่โต",
            "humanity": "มนุษยชาติ",
            "in": "ใน",
            "incredibly": "อย่างมาก",
            "intelligence": "สติปัญญา",
            "invention": "สิ่งประดิษฐ์",
            "is": "เป็น/อยู่/คือ",
            "it's": "มันคือ",
            "its": "ของมัน",
            "lines": "บรรทัด",
            "loved": "รัก",
            "many": "มากมาย",
            "metal": "โลหะ",
            "metal frame": "โครงโลหะ",
            "mistake": "ข้อผิดพลาด",
            "months": "เดือน",
            "most": "มากที่สุด/ส่วนใหญ่",
            "most difficult": "ยากที่สุด",
            "moved": "เคลื่อนที่",
            "of": "ของ",
            "off": "ออก/ปิด",
            "one": "หนึ่ง",
            "ordering": "กำลังสั่งซื้อ",
            "paid": "จ่าย",
            "paid off": "สัมฤทธิ์ผล",
            "part": "ส่วน",
            "parts": "ชิ้นส่วน",
            "people": "ผู้คน",
            "performed": "ดำเนินการ",
            "play": "เล่น",
            "play a big role": "มีบทบาทสำคัญ",
            "praised": "ชมเชย",
            "project": "โครงการ",
            "proud": "ภูมิใจ",
            "recognize": "จำได้",
            "respond": "ตอบสนอง",
            "robot": "หุ่นยนต์",
            "robots": "หุ่นยนต์หลายตัว",
            "role": "บทบาท",
            "ruin": "ทำลาย",
            "said": "พูด (อดีต)",
            "school": "โรงเรียน",
            "science": "วิทยาศาสตร์",
            "simple": "ง่าย",
            "small": "เล็ก",
            "spent": "ใช้ (เวลา/เงิน)",
            "spent months": "ใช้เวลาหลายเดือน",
            "technology": "เทคโนโลยี",
            "test": "การทดสอบ",
            "that": "นั้น",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "this": "นี้",
            "thousands": "หลายพัน",
            "to": "ถึง/ไปยัง",
            "tools": "เครื่องมือ",
            "very": "มาก",
            "voices": "เสียง",
            "wants": "ต้องการ",
            "whole": "ทั้งหมด",
            "will": "จะ",
            "with": "กับ",
            "work": "งาน/ทำงาน",
            "written": "เขียน",
            "year": "ปี",
            "yesterday": "เมื่อวาน"
        }
    },
    {
        "id": "sleepy_owl_b1",
        "title": "Guardian of the Forest",
        "level": "B1",
        "cover": "images/b1/owl/cover.jpg",
        "description": "Ollie the owl protects the forest during the night.",
        "vocabulary": [
            {
                "word": "Nocturnal",
                "translation": "หากินกลางคืน"
            },
            {
                "word": "Observation",
                "translation": "การสังเกต"
            },
            {
                "word": "Territory",
                "translation": "อาณาเขต"
            }
        ],
        "chapters": [
            {
                "title": "Night Watch",
                "content": "Ollie is a nocturnal bird. He has guarded this forest for many years. While the other animals are sleeping, Ollie is busy observing the environment from his favorite tree.",
                "image": "images/b1/owl/ch1.jpg",
                "color": "#0f172a",
                "visual_type": "owl_watch"
            },
            {
                "title": "Unusual Sound",
                "content": "Last night, he heard an unusual sound near the river. He has never heard anything like it before. He decided to fly down and investigate the area.",
                "image": "images/b1/owl/ch2.jpg",
                "color": "#1e293b",
                "visual_type": "owl_investigation"
            },
            {
                "title": "The Intruder",
                "content": "He found a small fox that was lost. The fox had traveled far from its own territory. Ollie has used his wisdom to guide the young animal back to its home.",
                "image": "images/b1/owl/ch3.jpg",
                "color": "#334155",
                "visual_type": "owl_fox"
            },
            {
                "title": "Silent Wings",
                "content": "Ollie's wings are designed for silent flight. He has mastered the art of moving through the trees without a sound. This skill is essential for a nocturnal guardian.",
                "image": "images/b1/owl/ch4.jpg",
                "color": "#475569",
                "visual_type": "owl_flight"
            },
            {
                "title": "Morning Rest",
                "content": "As the sun comes up, Ollie's shift ends. He has finished his duty for the night. He will sleep until the stars appear again in the dark sky.",
                "image": "images/b1/owl/ch5.jpg",
                "color": "#f1f5f9",
                "visual_type": "owl_rest"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "again": "อีกครั้ง",
            "an": "หนึ่ง/อัน (ไม่เจาะจง)",
            "and": "และ",
            "animal": "สัตว์",
            "animals": "สัตว์",
            "anything": "บางอย่าง",
            "appear": "ปรากฏ",
            "are": "เป็น/อยู่/คือ",
            "area": "พื้นที่",
            "art": "ศิลปะ",
            "as": "ในฐานะ/ขณะที่",
            "back": "กลับ",
            "before": "ก่อน",
            "bird": "นก",
            "busy": "ยุ่ง",
            "comes": "มา",
            "comes up": "ขึ้นมา",
            "dark": "มืด",
            "dark sky": "ท้องฟ้าที่มืด",
            "decided": "ตัดสินใจ",
            "designed": "ถูกออกแบบ",
            "down": "ลง",
            "duty": "หน้าที่",
            "ends": "จบ",
            "environment": "สิ่งแวดล้อม",
            "essential": "จำเป็น",
            "far": "ไกล",
            "favorite": "ที่โปรดปราน",
            "favorite tree": "ต้นไม้โปรด",
            "finished": "เสร็จสิ้น",
            "flight": "การบิน",
            "fly": "บิน",
            "fly down": "บินลง",
            "for": "สำหรับ/เป็นเวลา",
            "forest": "ป่า",
            "found": "พบ",
            "fox": "สุนัขจิ้งจอก",
            "from": "จาก",
            "guarded": "เฝ้ายาม",
            "guardian": "ผู้พิทักษ์",
            "guide": "นำทาง",
            "had": "มี/ได้ (อดีต)",
            "had traveled": "ได้เดินทาง",
            "has": "มี/ได้ (ปัจจุบัน)",
            "he": "เขา",
            "heard": "ได้ยิน",
            "his": "ของเขา",
            "home": "บ้าน",
            "in": "ใน",
            "investigate": "สำรวจ/ตรวจสอบ",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "its": "ของมัน",
            "last": "ที่แล้ว/สุดท้าย",
            "last night": "เมื่อคืนนี้",
            "like": "ชอบ/เหมือน",
            "lost": "หลงทาง",
            "many": "มากมาย",
            "many years": "หลายปี",
            "mastered": "เชี่ยวชาญ",
            "moving": "การเคลื่อนที่",
            "near": "ใกล้",
            "never": "ไม่เคย",
            "night": "กลางคืน",
            "nocturnal": "หากินกลางคืน",
            "observing": "กำลังสังเกต",
            "of": "ของ",
            "ollie": "ออลลี่",
            "ollie's": "ของออลลี่",
            "other": "อื่น",
            "own": "ของตัวเอง",
            "river": "แม่น้ำ",
            "shift": "กะการทำงาน",
            "silent": "เงียบ",
            "silent flight": "การบินที่เงียบ",
            "skill": "ทักษะ",
            "sky": "ท้องฟ้า",
            "sleep": "นอน",
            "sleeping": "กำลังนอน",
            "small": "เล็ก",
            "small fox": "สุนัขจิ้งจอกตัวเล็ก",
            "sound": "เสียง",
            "stars": "ดวงดาว",
            "sun": "ดวงอาทิตย์",
            "territory": "อาณาเขต",
            "that": "นั้น",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "this": "นี้",
            "through": "ผ่าน",
            "to": "ถึง/ไปยัง",
            "traveled": "เดินทาง",
            "tree": "ต้นไม้",
            "trees": "ต้นไม้หลายต้น",
            "until": "จนกระทั่ง",
            "unusual": "ผิดปกติ",
            "up": "ขึ้น",
            "used": "ใช้",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "while": "ขณะที่",
            "will": "จะ",
            "wings": "ปีก",
            "wisdom": "ปัญญา",
            "without": "ปราศจาก",
            "years": "ปี (หลายปี)",
            "young animal": "สัตว์ที่อายุน้อย"
        }
    },
    {
        "id": "magic_park_b1",
        "title": "The Changing Garden",
        "level": "B1",
        "cover": "images/b1/park/cover.jpg",
        "description": "Leo discovers that the park changes with his emotions.",
        "vocabulary": [
            {
                "word": "Emotion",
                "translation": "อารมณ์"
            },
            {
                "word": "Atmosphere",
                "translation": "บรรยากาศ"
            },
            {
                "word": "Influence",
                "translation": "มีอิทธิพล"
            }
        ],
        "chapters": [
            {
                "title": "A Special Connection",
                "content": "Leo has always felt a special connection to the city park. Recently, he has noticed that the colors of the flowers change when he is happy or sad. It's a mysterious phenomenon.",
                "image": "images/b1/park/ch1.jpg",
                "color": "#f0fdf4",
                "visual_type": "park_connection"
            },
            {
                "title": "The Gloomy Rain",
                "content": "One day, Leo felt very disappointed. Suddenly, grey clouds covered the sky and it started to rain. He has realized that his emotions directly influence the park's atmosphere.",
                "image": "images/b1/park/ch2.jpg",
                "color": "#e2e8f0",
                "visual_type": "park_gloomy"
            },
            {
                "title": "Finding Peace",
                "content": "He sat under a large oak tree and started to meditate. He has learned to control his thoughts and find inner peace. Slowly, the rain stopped and a rainbow appeared.",
                "image": "images/b1/park/ch3.jpg",
                "color": "#fffbeb",
                "visual_type": "park_peace"
            },
            {
                "title": "A New Perspective",
                "content": "Leo has shared his secret with Anna. They have explored the park together and discovered that positive thoughts create a more harmonious environment for everyone.",
                "image": "images/b1/park/ch4.jpg",
                "color": "#fdf4ff",
                "visual_type": "park_perspective"
            },
            {
                "title": "The Living Garden",
                "content": "The park is now more beautiful than ever. Leo has become a guardian of this living garden. He believes that nature and the human heart are deeply connected.",
                "image": "images/b1/park/ch5.jpg",
                "color": "#86efac",
                "visual_type": "park_living"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "always": "เสมอ",
            "and": "และ",
            "anna": "แอนนา",
            "appeared": "ปรากฏ",
            "are": "เป็น/อยู่/คือ",
            "atmosphere": "บรรยากาศ",
            "beautiful": "สวยงาม",
            "become": "กลายเป็น",
            "believes": "เชื่อ",
            "change": "เปลี่ยน",
            "city": "เมือง",
            "clouds": "เมฆ",
            "colors": "สี",
            "connected": "ที่เชื่อมต่อกัน",
            "connection": "ความเชื่อมโยง",
            "control": "ควบคุม",
            "covered": "ปกคลุม",
            "create": "สร้าง",
            "day": "วัน",
            "deeply": "อย่างลึกซึ้ง",
            "deeply connected": "เชื่อมโยงกันอย่างลึกซึ้ง",
            "directly": "โดยตรง",
            "disappointed": "ผิดหวัง",
            "discovered": "ค้นพบ",
            "emotions": "อารมณ์",
            "environment": "สิ่งแวดล้อม",
            "ever": "เคย",
            "everyone": "ทุกคน",
            "explored": "สำรวจ",
            "felt": "รู้สึก",
            "find": "ค้นหา/พบ",
            "flowers": "ดอกไม้",
            "for": "สำหรับ/เป็นเวลา",
            "garden": "สวน",
            "grey": "สีเทา",
            "grey clouds": "เมฆสีเทา",
            "guardian": "ผู้พิทักษ์",
            "happy": "มีความสุข",
            "harmonious": "สอดประสาน",
            "has": "มี/ได้ (ปัจจุบัน)",
            "have": "มี/ได้ (ปัจจุบัน)",
            "he": "เขา",
            "heart": "หัวใจ",
            "his": "ของเขา",
            "human": "มนุษย์",
            "influence": "มีอิทธิพล",
            "inner": "ภายใน",
            "inner peace": "ความสงบภายใน",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "it's": "มันคือ",
            "large": "ใหญ่",
            "learned": "เรียนรู้",
            "leo": "ลีโอ",
            "living": "ที่มีชีวิต",
            "living garden": "สวนที่มีชีวิต",
            "meditate": "ทำสมาธิ",
            "more": "มากขึ้น",
            "mysterious": "ลึกลับ",
            "nature": "ธรรมชาติ",
            "noticed": "สังเกตเห็น",
            "now": "ตอนนี้",
            "oak": "ต้นโอ๊ก",
            "oak tree": "ต้นโอ๊ก",
            "of": "ของ",
            "one": "หนึ่ง",
            "one day": "วันหนึ่ง",
            "or": "หรือ",
            "park": "สวนสาธารณะ",
            "park's": "ของสวน",
            "peace": "ความสงบ",
            "phenomenon": "ปรากฏการณ์",
            "positive": "เชิงบวก",
            "positive thoughts": "ความคิดเชิงบวก",
            "rain": "ฝน",
            "rainbow": "สายรุ้ง",
            "realized": "ตระหนัก",
            "recently": "เมื่อเร็วๆ นี้",
            "sad": "เศร้า",
            "sat": "นั่ง",
            "secret": "ความลับ",
            "shared": "แบ่งปัน",
            "sky": "ท้องฟ้า",
            "slowly": "อย่างช้าๆ",
            "special": "พิเศษ",
            "special connection": "ความเชื่อมโยงที่พิเศษ",
            "started": "เริ่ม",
            "stopped": "หยุด",
            "suddenly": "ทันใดนั้น",
            "than": "กว่า",
            "that": "นั้น",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "they": "พวกเรา",
            "this": "นี้",
            "thoughts": "ความคิด",
            "to": "ถึง/ไปยัง",
            "together": "ด้วยกัน",
            "tree": "ต้นไม้",
            "under": "ใต้",
            "very": "มาก",
            "with": "กับ"
        }
    },
    {
        "id": "robot_companion",
        "title": "Modern Companion",
        "level": "B1",
        "cover": "images/b1/robot_comp/cover.jpg",
        "description": "The evolution of robots in our daily lives.",
        "vocabulary": [
            {
                "word": "Companion",
                "translation": "เพื่อนร่วมทาง"
            },
            {
                "word": "Evolution",
                "translation": "วิวัฒนาการ"
            },
            {
                "word": "Efficiency",
                "translation": "ประสิทธิภาพ"
            }
        ],
        "chapters": [
            {
                "title": "Robots Everywhere",
                "content": "In the modern world, we have used robots for many different tasks. They have helped us in factories and hospitals. Now, they are becoming our personal companions.",
                "image": "images/b1/robot_comp/ch1.jpg",
                "color": "#f1f5f9",
                "visual_type": "robots_everywhere"
            },
            {
                "title": "The Helper",
                "content": "Sarah has bought a small home assistant robot. It has already learned the layout of her apartment. It can clean the floor and remind her about important meetings.",
                "image": "images/b1/robot_comp/ch2.jpg",
                "color": "#f8fafc",
                "visual_type": "robot_helper"
            },
            {
                "title": "Complex Interaction",
                "content": "These robots can now interact with humans using natural language. They have improved their ability to understand emotions. Sarah feels less lonely with her robot helper.",
                "image": "images/b1/robot_comp/ch3.jpg",
                "color": "#eff6ff",
                "visual_type": "robot_interact"
            },
            {
                "title": "Improving Efficiency",
                "content": "Technology has advanced significantly in the last decade. Scientists have created more efficient batteries and faster processors for these smart machines.",
                "image": "images/b1/robot_comp/ch4.jpg",
                "color": "#f0fdf4",
                "visual_type": "robot_efficiency"
            },
            {
                "title": "Future Roles",
                "content": "We haven't seen the full potential of robots yet. In the future, they will likely help us explore space and protect our environment. The evolution continues.",
                "image": "images/b1/robot_comp/ch5.jpg",
                "color": "#e2e8f0",
                "visual_type": "robot_future"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "ability": "ความสามารถ",
            "about": "เกี่ยวกับ",
            "advanced": "ก้าวหน้า",
            "already": "แล้ว",
            "and": "และ",
            "apartment": "อพาร์ทเมนท์",
            "are": "เป็น/อยู่/คือ",
            "assistant": "ผู้ช่วย",
            "batteries": "แบตเตอรี่",
            "becoming": "กำลังกลายเป็น",
            "bought": "ซื้อ",
            "can": "สามารถ",
            "clean": "ทำความสะอาด",
            "companions": "เพื่อนร่วมทาง",
            "continues": "ดำเนินต่อไป",
            "created": "สร้าง",
            "decade": "ทศวรรษ",
            "different": "แตกต่าง",
            "different tasks": "งานที่แตกต่าง",
            "efficient": "มีประสิทธิภาพ",
            "emotions": "อารมณ์",
            "environment": "สิ่งแวดล้อม",
            "evolution": "วิวัฒนาการ",
            "explore": "สำรวจ",
            "explore space": "สำรวจอวกาศ",
            "factories": "โรงงาน",
            "faster": "เร็วกว่า",
            "faster processors": "ตัวประมวลผลที่เร็วขึ้น",
            "feels": "รู้สึก",
            "floor": "พื้น",
            "for": "สำหรับ/เป็นเวลา",
            "full": "เต็ม",
            "full potential": "ศักยภาพที่เต็มที่",
            "future": "อนาคต",
            "future roles": "บทบาทในอนาคต",
            "has": "มี/ได้ (ปัจจุบัน)",
            "have": "มี/ได้ (ปัจจุบัน)",
            "haven't": "ยังไม่มี/ยังไม่ได้",
            "haven't seen": "ยังไม่เห็น",
            "help": "ช่วย",
            "helped": "ช่วย",
            "helper": "ผู้ช่วย",
            "her": "ของเธอ/เธอ",
            "home": "บ้าน",
            "home assistant": "ผู้ช่วยในบ้าน",
            "hospitals": "โรงพยาบาล",
            "humans": "มนุษย์",
            "important": "สำคัญ",
            "important meetings": "การประชุมที่สำคัญ",
            "improved": "ปรับปรุง",
            "in": "ใน",
            "interact": "มีปฏิสัมพันธ์",
            "it": "มัน",
            "language": "ภาษา",
            "last": "ที่แล้ว/สุดท้าย",
            "last decade": "ทศวรรษที่แล้ว",
            "layout": "แผนผัง",
            "learned": "เรียนรู้",
            "less": "น้อยกว่า",
            "less lonely": "เหงาน้อยลง",
            "likely": "มีแนวโน้ม",
            "lonely": "เหงา",
            "machines": "เครื่องจักร",
            "many": "หลาย",
            "meetings": "การประชุม",
            "modern": "ทันสมัย",
            "modern world": "โลกสมัยใหม่",
            "more": "มากขึ้น",
            "natural": "ธรรมชาติ",
            "natural language": "ภาษาธรรมชาติ",
            "now": "ตอนนี้",
            "of": "ของ",
            "our": "ของเรา",
            "personal": "ส่วนตัว",
            "personal companions": "เพื่อนร่วมทางส่วนตัว",
            "potential": "ศักยภาพ",
            "processors": "ตัวประมวลผล",
            "protect": "ปกป้อง",
            "remind": "เตือน",
            "robot": "หุ่นยนต์",
            "robots": "หุ่นยนต์",
            "sarah": "ซาร่า",
            "scientists": "นักวิทยาศาสตร์",
            "seen": "เห็น (past participle)",
            "significantly": "อย่างมีนัยสำคัญ",
            "small": "เล็ก",
            "smart": "ฉลาด",
            "smart machines": "เครื่องจักรอัจฉริยะ",
            "space": "พื้นที่/อวกาศ",
            "tasks": "งาน",
            "technology": "เทคโนโลยี",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "their": "ของพวกเขา",
            "these": "เหล่านี้",
            "they": "พวกเรา",
            "to": "ถึง/ไปยัง",
            "understand": "เข้าใจ",
            "us": "พวกเรา (กรรม)",
            "used": "ใช้",
            "using": "การใช้",
            "we": "พวกเรา",
            "will": "จะ",
            "with": "กับ",
            "world": "โลก",
            "yet": "ยัง"
        }
    },
    {
        "id": "green_future",
        "title": "Sustainable Future",
        "level": "B1",
        "cover": "images/b1/green_future/cover.jpg",
        "description": "How technology and nature work together for a better world.",
        "vocabulary": [
            {
                "word": "Renewable",
                "translation": "พลังงานหมุนเวียน"
            },
            {
                "word": "Conservation",
                "translation": "การอนุรักษ์"
            },
            {
                "word": "Innovation",
                "translation": "นวัตกรรม"
            }
        ],
        "chapters": [
            {
                "title": "Clean Energy",
                "content": "The world has started to use more renewable energy sources like solar and wind power. These innovations have reduced our carbon footprint and helped protect the atmosphere.",
                "image": "images/b1/green_future/ch1.jpg",
                "color": "#ecfdf5",
                "visual_type": "clean_energy"
            },
            {
                "title": "Water Conservation",
                "content": "Many cities have implemented smart water systems. We have learned to use our resources more carefully. Saving water is essential for the future of our planet.",
                "image": "images/b1/green_future/ch2.jpg",
                "color": "#e0f2fe",
                "visual_type": "water_conserve"
            },
            {
                "title": "Forest Restoration",
                "content": "Volunteers have planted millions of trees in the last five years. Forest restoration helps to maintain biodiversity and provides a home for many animals.",
                "image": "images/b1/green_future/ch3.jpg",
                "color": "#dcfce7",
                "visual_type": "forest_restore"
            },
            {
                "title": "Reducing Waste",
                "content": "We have seen a significant change in how people manage waste. More people have started to use reusable bags and bottles. Small actions can have a big impact.",
                "image": "images/b1/green_future/ch4.jpg",
                "color": "#fef9c3",
                "visual_type": "reduce_waste"
            },
            {
                "title": "A Green Hope",
                "content": "If we continue to value nature, we can build a sustainable future. Everyone has a role to play in this global mission. Hope is growing.",
                "image": "images/b1/green_future/ch5.jpg",
                "color": "#86efac",
                "visual_type": "green_hope"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง/อัน (ไม่เจาะจง)",
            "actions": "การกระทำ",
            "and": "และ",
            "animals": "สัตว์",
            "atmosphere": "ชั้นบรรยากาศ",
            "bags": "ถุง",
            "big": "ใหญ่",
            "big impact": "ผลกระทบที่ยิ่งใหญ่",
            "biodiversity": "ความหลากหลายทางชีวภาพ",
            "bottles": "ขวด",
            "build": "สร้าง",
            "can": "สามารถ",
            "carbon": "คาร์บอน",
            "carbon footprint": "รอยเท้าคาร์บอน",
            "carefully": "อย่างระมัดระวัง",
            "change": "เปลี่ยนแปลง",
            "cities": "เมืองต่างๆ",
            "continue": "ทำต่อไป",
            "energy": "พลังงาน",
            "essential": "จำเป็น",
            "everyone": "ทุกคน",
            "five": "ห้า",
            "footprint": "รอยเท้า",
            "for": "สำหรับ/เป็นเวลา",
            "forest": "ป่า",
            "forest restoration": "การฟื้นฟูป่า",
            "future": "อนาคต",
            "global": "ระดับโลก",
            "global mission": "ภารกิจระดับโลก",
            "growing": "กำลังเติบโต",
            "has": "มี/ได้ (ปัจจุบัน)",
            "have": "มี/ได้ (ปัจจุบัน)",
            "helped": "ช่วย",
            "helps": "ช่วย",
            "home": "บ้าน",
            "hope": "ความหวัง",
            "how": "อย่างไร",
            "if": "ถ้า",
            "impact": "ผลกระทบ",
            "implemented": "นำไปใช้",
            "in": "ใน",
            "innovations": "นวัตกรรม",
            "is": "เป็น/อยู่/คือ",
            "last": "ที่แล้ว/สุดท้าย",
            "last five years": "ห้าปีที่แล้ว",
            "learned": "เรียนรู้",
            "like": "ชอบ/เหมือน",
            "maintain": "คงรักษา",
            "manage": "จัดการ",
            "manage waste": "จัดการขยะ",
            "many": "มากมาย",
            "many cities": "หลายเมือง",
            "millions": "ล้าน",
            "mission": "ภารกิจ",
            "more": "มากขึ้น",
            "nature": "ธรรมชาติ",
            "of": "ของ",
            "our": "ของเรา",
            "people": "ผู้คน",
            "planet": "โลก",
            "planted": "ปลูก",
            "play": "เล่น",
            "power": "พลัง",
            "protect": "ปกป้อง",
            "provides": "ให้",
            "reduced": "ลด",
            "renewable": "หมุนเวียน",
            "renewable energy": "พลังงานหมุนเวียน",
            "resources": "ทรัพยากร",
            "restoration": "การบูรณะ",
            "reusable": "นำกลับมาใช้ใหม่ได้",
            "reusable bags": "ถุงที่ใช้ซ้ำได้",
            "role": "บทบาท",
            "role to play": "บทบาทที่ต้องทำ",
            "saving": "การประหยัด/การรักษา",
            "saving water": "การประหยัดน้ำ",
            "seen": "เห็น",
            "significant": "สำคัญ",
            "significant change": "การเปลี่ยนแปลงที่สำคัญ",
            "small": "เล็ก",
            "small actions": "การกระทำเล็กๆ",
            "smart": "ฉลาด",
            "smart water systems": "ระบบน้ำอัจฉริยะ",
            "solar": "แสงอาทิตย์",
            "sources": "แหล่งกำเนิด",
            "started": "เริ่ม",
            "sustainable": "ยั่งยืน",
            "sustainable future": "อนาคตที่ยั่งยืน",
            "systems": "ระบบ",
            "the": "(คำนำหน้าคำนามชี้เฉพาะ)",
            "these": "เหล่านี้",
            "this": "นี้",
            "to": "ถึง/ไปยัง",
            "trees": "ต้นไม้หลายต้น",
            "use": "ใช้",
            "value": "คุณค่า",
            "value nature": "เห็นคุณค่าของธรรมชาติ",
            "volunteers": "อาสาสมัคร",
            "waste": "ขยะ",
            "water": "น้ำ",
            "we": "พวกเรา",
            "wind": "ลม",
            "wind power": "พลังงานลม",
            "world": "โลก",
            "years": "ปี (หลายปี)"
        }
    }
];
window.CURRENT_LEVEL_DATA = B1_STORIES;
