const C1_STORIES = [
    {
        "id": "climatic_entropy",
        "title": "The Climatic Entropy",
        "level": "C1",
        "cover": "images/c1/climate/cover.jpg",
        "description": "A profound exploration of systemic environmental collapse and human ingenuity.",
        "vocabulary": [
            {
                "word": "Mitigation",
                "translation": "การบรรเทาผลกระทบ"
            },
            {
                "word": "Unprecedented",
                "translation": "ที่ไม่เคยปรากฏมาก่อน"
            },
            {
                "word": "Anthropogenic",
                "translation": "ที่เกิดจากน้ำมือมนุษย์"
            },
            {
                "word": "Tipping point",
                "translation": "จุดวิกฤตที่เกินย้อนกลับ"
            },
            {
                "word": "Resilience",
                "translation": "ความสามารถในการฟื้นตัว"
            }
        ],
        "chapters": [
            {
                "title": "The Silent Omen",
                "content": "The transition from seasonal predictability to climatic entropy occurred not with a bang, but with a series of subtle shifts in atmospheric composition. Dr. Aris, a seasoned climatologist, observed the data with a growing sense of foreboding. The anthropogenic signatures were no longer mere statistical noise; they had become the dominant frequency in the planet's ecological symphony. He knew that the window for effective mitigation was closing rapidly.",
                "image": "images/c1/climate/ch1.jpg",
                "color": "#f1f5f9",
                "visual_type": "scientific_monitoring"
            },
            {
                "title": "The Melting Sentinel",
                "content": "In the desolate expanse of the Arctic, the melting permafrost served as a grim sentinel of a world in flux. As the methane seeped into the atmosphere, it triggered a feedback loop that threatened to push the planet past a critical tipping point. The unprecedented rate of glacial retreat was a testament to the sheer scale of the disruption. Scientists struggled to quantify the cumulative impact of these cascading failures.",
                "image": "images/c1/climate/ch2.jpg",
                "color": "#e2e8f0",
                "visual_type": "arctic_glacier"
            },
            {
                "title": "Atmospheric Paradox",
                "content": "Despite the mounting evidence, the global response remained characterized by a profound inertia. The paradox lay in the fact that while the consequences were global, the incentives for action were localized and short-term. Dr. Aris argued that without a radical paradigm shift in our economic models, the entropy would only accelerate. He advocated for a holistic approach that integrated carbon sequestration with systemic societal restructuring.",
                "image": "images/c1/climate/ch3.jpg",
                "color": "#cbd5e1",
                "visual_type": "global_map"
            },
            {
                "title": "The Resilience Factor",
                "content": "Amidst the gloom, pockets of resilience began to emerge in the most unexpected places. Urban centers were being transformed into carbon-neutral ecosystems, utilizing decentralized energy grids and regenerative architecture. These initiatives, though fragmented, demonstrated the innate human capacity for adaptation. Dr. Aris noted that true resilience required more than just technological fixes; it necessitated a fundamental re-evaluation of our relationship with the biosphere.",
                "image": "images/c1/climate/ch4.jpg",
                "color": "#94a3b8",
                "visual_type": "green_city"
            },
            {
                "title": "Ecological Debt",
                "content": "The concept of ecological debt became a focal point of international discourse. Nations that had historically benefited from industrialization were now being called upon to compensate for the collateral damage inflicted on the global south. This reparations framework was met with fierce resistance, highlighting the geopolitical complexities of climate justice. Dr. Aris observed that the atmosphere did not recognize borders, yet the solutions were being stifled by them.",
                "image": "images/c1/climate/ch5.jpg",
                "color": "#64748b",
                "visual_type": "industrial_complex"
            },
            {
                "title": "The Great Transition",
                "content": "As the frequency of extreme weather events reached a fever pitch, the necessity for a 'Great Transition' became undeniable. Societies began to move away from fossil fuel dependence, embracing a circular economy that prioritized sustainability over unbridled growth. This transition was not without its casualties, as legacy industries collapsed and labor markets were upended. However, the long-term viability of civilization depended on this painful metamorphosis.",
                "image": "images/c1/climate/ch6.jpg",
                "color": "#475569",
                "visual_type": "solar_farm"
            },
            {
                "title": "Brave New Biosphere",
                "content": "The resulting biosphere was a hybrid of natural restoration and technological intervention. Geo-engineering projects were deployed to stabilize the thermal balance, while rewilding efforts aimed to restore biodiversity. The ethical implications of 'playing God' with the planet's climate were debated in every forum. Dr. Aris cautioned that we must proceed with humility, acknowledging the inherent unpredictability of complex adaptive systems.",
                "image": "images/c1/climate/ch7.jpg",
                "color": "#334155",
                "visual_type": "geoengineering"
            },
            {
                "title": "Cognitive Decoupling",
                "content": "One of the greatest challenges was the cognitive decoupling of economic success from material consumption. People began to find value in intangible assets—knowledge, community, and ecological stewardship. This cultural shift was the most significant driver of change. The entropy that had once threatened to consume the world was being countered by a new form of social order, one that was built on the foundations of collective responsibility.",
                "image": "images/c1/climate/ch8.jpg",
                "color": "#1e293b",
                "visual_type": "community_garden"
            },
            {
                "title": "The Final Ledger",
                "content": "Looking back, the crisis served as a mirror, reflecting the best and worst of humanity. The final ledger of the Anthropocene showed a planet that had been pushed to the brink, yet managed to find a new equilibrium. The scars remained, but they were a reminder of the lessons learned during the era of entropy. Dr. Aris, now in the twilight of his career, saw a generation that was more attuned to the rhythms of the natural world.",
                "image": "images/c1/climate/ch9.jpg",
                "color": "#0f172a",
                "visual_type": "ledger"
            },
            {
                "title": "Inheriting the Earth",
                "content": "The Earth that the next generation inherited was a testament to the power of human ingenuity when tempered by wisdom. The transition was complete, and the climatic entropy had been arrested. The new world was not a utopia, but it was a sustainable reality. As Dr. Aris watched the sun set over a thriving, green landscape, he felt a profound sense of peace. The symphony of life was continuing, in a new, more harmonious key.",
                "image": "images/c1/climate/ch10.jpg",
                "color": "#14532d",
                "visual_type": "harmony"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง",
            "accelerate": "เร่ง",
            "acknowledging": "การยอมรับ",
            "action": "การกระทำ",
            "adaptation": "การปรับตัว",
            "adaptive": "ที่ปรับตัวได้",
            "advocated": "สนับสนุน",
            "aimed": "มุ่งเป้าไปที่",
            "amidst": "ท่ามกลาง",
            "and": "และ",
            "anthropocene": "แอนโธรโพซีน",
            "anthropogenic": "ที่เกิดจากน้ำมือมนุษย์",
            "approach": "แนวทาง",
            "architecture": "สถาปัตยกรรม",
            "arctic": "อาร์กติก",
            "argued": "โต้แย้ง",
            "aris": "อาริส",
            "arrested": "ถูกหยุดยั้ง",
            "as": "ในฐานะ",
            "assets": "สินทรัพย์",
            "atmosphere": "ชั้นบรรยากาศ",
            "atmospheric": "ทางชั้นบรรยากาศ",
            "attuned": "ที่สอดคล้อง",
            "away": "ออกไป",
            "back": "กลับ/ข้างหลัง",
            "balance": "สมดุล",
            "bang": "เสียงดัง/การระเบิด",
            "became": "กลายเป็น",
            "become": "กลายเป็น",
            "been": "เป็น/อยู่/คือ (อดีต)",
            "began": "เริ่ม",
            "being": "กำลังถูก",
            "benefited": "ได้รับประโยชน์",
            "best": "ดีที่สุด",
            "biodiversity": "ความหลากหลายทางชีวภาพ",
            "biosphere": "ชีวภาค",
            "borders": "พรมแดน",
            "brink": "ขอบเหว",
            "built": "ถูกสร้าง",
            "but": "แต่",
            "by": "โดย",
            "called": "ถูกเรียกว่า",
            "called upon": "ถูกเรียกร้อง",
            "capacity": "ความสามารถ",
            "carbon": "คาร์บอน",
            "carbon-neutral": "ปล่อยคาร์บอนสุทธิเป็นศูนย์",
            "career": "อาชีพ",
            "cascading": "ที่ต่อเนื่องกัน",
            "casualties": "ความสูญเสีย",
            "cautioned": "เตือน",
            "centers": "ศูนย์กลาง",
            "challenges": "ความท้าทาย",
            "change": "การเปลี่ยนแปลง",
            "characterized": "ที่มีลักษณะเด่น",
            "circular": "เชิงวงจร",
            "civilization": "อารยธรรม",
            "climate": "ภูมิอากาศ",
            "climatic": "ทางภูมิอากาศ",
            "climatologist": "นักภูมิอากาศวิทยา",
            "closing": "กำลังปิด",
            "cognitive": "เกี่ยวกับกระบวนการคิด",
            "collapsed": "ล่มสลาย",
            "collateral": "ผลข้างเคียง/ที่เป็นรอง",
            "collective": "ส่วนรวม",
            "community": "ชุมชน",
            "compensate": "ชดเชย",
            "complete": "สมบูรณ์",
            "complex": "ซับซ้อน",
            "complexities": "ความซับซ้อน",
            "composition": "องค์ประกอบ",
            "concept": "แนวคิด",
            "consequences": "ผลที่ตามมา",
            "consume": "บริโภค/ทำลาย",
            "consumption": "การบริโภค",
            "continuing": "ดำเนินต่อ",
            "countered": "ถูกตอบโต้",
            "crisis": "วิกฤต",
            "critical": "วิกฤต",
            "cultural": "วัฒนธรรม",
            "cumulative": "ที่สะสม",
            "damage": "ความเสียหาย",
            "data": "ข้อมูล",
            "debated": "ถูกถกเถียง",
            "debt": "หนี้",
            "decentralized": "กระจายศูนย์",
            "decoupling": "การแยกออกจากกัน",
            "demonstrated": "สาธิต",
            "depended": "ขึ้นอยู่กับ",
            "dependence": "การพึ่งพา",
            "deployed": "ถูกนำมาใช้",
            "desolate": "ที่รกร้างว่างเปล่า",
            "despite": "ทั้งๆ ที่",
            "did": "ทำ (อดีต)",
            "did not": "ไม่ได้",
            "discourse": "วาทกรรม",
            "disruption": "การหยุดชะงัก",
            "dominant": "ที่ครอบงำ/ที่เด่นกว่า",
            "dr": "ดร.",
            "driver": "ตัวขับเคลื่อน",
            "during": "ระหว่าง",
            "earth": "โลก",
            "ecological": "ทางนิเวศวิทยา",
            "economic": "ทางเศรษฐกิจ",
            "economy": "เศรษฐกิจ",
            "ecosystems": "ระบบนิเวศ",
            "effective": "ที่มีประสิทธิภาพ",
            "efforts": "ความพยายาม",
            "embracing": "ยอมรับ",
            "emerge": "ปรากฏออกมา",
            "energy": "พลังงาน",
            "engineering": "วิศวกรรม",
            "entropy": "เอนโทรปี/การสลายตัว",
            "equilibrium": "สภาวะสมดุล",
            "era": "ยุค",
            "ethical": "ทางจริยธรรม",
            "evaluation": "การประเมิน",
            "events": "เหตุการณ์",
            "every": "ทุกๆ",
            "evidence": "หลักฐาน",
            "expanse": "พื้นที่กว้างขวาง",
            "extreme": "สุดโต่ง",
            "fact": "ความจริง",
            "failures": "ความล้มเหลว",
            "feedback": "การตอบสนอง",
            "felt": "รู้สึก (อดีต)",
            "fever": "ไข้",
            "fever pitch": "ระดับสูงสุด",
            "fierce": "รุนแรง",
            "final": "สุดท้าย",
            "find": "ค้นหา",
            "fixes": "การแก้ไข",
            "flux": "การเปลี่ยนแปลง",
            "focal": "ที่เป็นจุดสนใจ",
            "for": "สำหรับ",
            "foreboding": "ลางสังหรณ์ไม่ดี",
            "form": "รูปแบบ",
            "forum": "เวที",
            "fossil": "ฟอสซิล",
            "foundations": "รากฐาน",
            "fragmented": "ที่กระจัดกระจาย",
            "framework": "กรอบการทำงาน",
            "frequency": "ความถี่",
            "from": "จาก",
            "fuel": "เชื้อเพลิง",
            "fundamental": "พื้นฐาน",
            "generation": "รุ่น",
            "geo": "ภูมิ",
            "geo-engineering": "วิศวกรรมธรณี",
            "geopolitical": "ภูมิรัฐศาสตร์",
            "glacial": "เกี่ยวกับธารน้ำแข็ง",
            "global": "โลก",
            "gloom": "ความเศร้าหมอง",
            "god": "พระเจ้า",
            "great": "ยิ่งใหญ่",
            "greatest": "ที่ยิ่งใหญ่ที่สุด",
            "green": "สีเขียว/อนุรักษ์ธรรมชาติ",
            "grids": "โครงข่าย",
            "grim": "น่าสลดใจ",
            "growing": "ที่กำลังเติบโต",
            "growth": "การเติบโต",
            "had": "มี (อดีต)",
            "harmonious": "สอดประสาน",
            "he": "เขา",
            "highlighting": "การเน้นย้ำ",
            "his": "ของเขา",
            "historically": "ทางประวัติศาสตร์",
            "holistic": "แบบองค์รวม",
            "however": "อย่างไรก็ตาม",
            "human": "มนุษย์",
            "humanity": "มนุษยชาติ",
            "humanity's": "ของมนุษยชาติ",
            "humility": "ความอ่อนน้อมถ่อมตัว",
            "hybrid": "ลูกผสม",
            "impact": "ผลกระทบ",
            "implications": "นัยสำคัญ",
            "in": "ใน",
            "incentives": "แรงจูงใจ",
            "industrialization": "การเป็นอุตสาหกรรม",
            "industries": "อุตสาหกรรม",
            "inertia": "ความเฉื่อย",
            "inflicted": "ที่ถูกก่อขึ้น",
            "ingenuity": "ความฉลาด",
            "inherent": "ที่มีอยู่เดิม",
            "inherited": "ได้รับมรดก",
            "initiatives": "โครงการริเริ่ม",
            "innate": "ที่มีมาแต่กำเนิด",
            "intangible": "ที่จับต้องไม่ได้",
            "integrated": "บูรณาการ",
            "international": "นานาชาติ",
            "intervention": "การแทรกแซง",
            "into": "เข้าไปใน",
            "it": "มัน",
            "its": "ของมัน",
            "just": "เพียงแค่",
            "justice": "ความยุติธรรม",
            "key": "กุญแจสำคัญ",
            "knew": "รู้ (อดีต)",
            "knowledge": "ความรู้",
            "labor": "แรงงาน",
            "landscape": "ภูมิทัศน์",
            "lay": "วาง/อยู่",
            "learned": "ได้เรียนรู้",
            "ledger": "สมุดบัญชี",
            "legacy": "ที่ตกทอดมา",
            "lessons": "บทเรียน",
            "life": "ชีวิต",
            "localized": "เฉพาะจุด",
            "long": "ยาว",
            "long-term": "ระยะยาว",
            "longer": "ยาวกว่า/อีกต่อไป",
            "looking": "กำลังมอง",
            "looking back": "มองย้อนกลับไป",
            "loop": "วงจร",
            "managed": "ทำสำเร็จ",
            "markets": "ตลาด",
            "material": "วัสดุ/รูปธรรม",
            "melting": "การละลาย",
            "mere": "เพียงแค่",
            "met": "พบ/เผชิญ",
            "metamorphosis": "การเปลี่ยนรูปร่าง",
            "methane": "ก๊าซมีเทน",
            "mirror": "กระจก",
            "mitigation": "การบรรเทาผลกระทบ",
            "models": "แบบจำลอง",
            "more": "มากกว่า",
            "more than": "มากกว่า",
            "most": "ที่สุด",
            "mounting": "ที่เพิ่มขึ้น",
            "move": "เคลื่อนไหว",
            "must": "ต้อง",
            "nations": "นานาชาติ",
            "natural": "ธรรมชาติ",
            "necessitated": "ทำให้จำเป็น",
            "necessity": "ความจำเป็น",
            "neutral": "เป็นกลาง",
            "new": "ใหม่",
            "next": "ถัดไป",
            "no": "ไม่",
            "noise": "สัญญาณรบกวน",
            "not": "ไม่",
            "noted": "สังเกตเห็น",
            "now": "ตอนนี้",
            "observed": "สังเกต",
            "occurred": "เกิดขึ้น",
            "of": "ของ",
            "on": "บน",
            "once": "ครั้งหนึ่ง",
            "one": "หนึ่ง",
            "one of": "หนึ่งใน",
            "only": "เท่านั้น",
            "order": "ลำดับ/คำสั่ง",
            "our": "ของเรา",
            "over": "เหนือ",
            "painful": "เจ็บปวด",
            "paradigm": "กระบวนทัศน์",
            "paradigm shift": "การเปลี่ยนกระบวนทัศน์",
            "paradox": "ความย้อนแย้ง",
            "past": "ผ่าน",
            "peace": "ความสงบ",
            "people": "ผู้คน",
            "permafrost": "ชั้นดินเยือกแข็งคงตัว",
            "pitch": "ระดับเสียง/ความเข้ม",
            "places": "สถานที่",
            "planet": "โลก",
            "planet's": "ของดาวเคราะห์",
            "playing": "การเล่น",
            "playing God": "สวมบทเป็นพระเจ้า",
            "pockets": "กลุ่มเล็กๆ",
            "point": "จุด",
            "power": "อำนาจ",
            "predictability": "การทำนายได้",
            "prioritized": "จัดลำดับความสำคัญ",
            "proceed": "ดำเนินการ",
            "profound": "ลึกซึ้ง",
            "projects": "โครงการ",
            "push": "ผลัก",
            "pushed": "ถูกผลัก",
            "quantify": "วัดปริมาณ",
            "radical": "รุนแรง",
            "rapidly": "อย่างรวดเร็ว",
            "rate": "อัตรา",
            "re": "ทำซ้ำ/อีกครั้ง",
            "re-evaluation": "การประเมินใหม่",
            "reached": "ถึง",
            "reality": "ความจริง",
            "recognize": "รับรอง",
            "reflecting": "สะท้อน",
            "regenerative": "เชิงฟื้นฟู",
            "relationship": "ความสัมพันธ์",
            "remained": "ยังคงอยู่",
            "reminder": "สิ่งเตือนใจ",
            "reparations": "การเยียวยา",
            "required": "ต้องการ",
            "resilience": "ความสามารถในการฟื้นตัว",
            "resistance": "การต่อต้าน",
            "response": "การตอบสนอง",
            "responsibility": "ความรับผิดชอบ",
            "restoration": "การฟื้นฟู",
            "restore": "ฟื้นฟู",
            "restored": "ฟื้นคืน",
            "restructuring": "การปรับโครงสร้าง",
            "resulting": "ที่เป็นผล",
            "retreat": "การถอยร่น",
            "rewilding": "การคืนความเป็นป่า",
            "rhythms": "จังหวะ",
            "saw": "เห็น (อดีต)",
            "scale": "ขนาด",
            "scars": "แผลเป็น",
            "scientists": "นักวิทยาศาสตร์",
            "seasonal": "ตามฤดูกาล",
            "seasoned": "ที่มีประสบการณ์สูง",
            "seeped": "รั่วซึม",
            "sense": "ความรู้สึก",
            "sentinel": "ยาม/ผู้เฝ้าสังเกต",
            "sequestration": "การกักเก็บ",
            "series": "ชุด/ลำดับ",
            "served": "ทำหน้าที่",
            "set": "ชุด/ตั้งค่า",
            "sheer": "มหาศาล",
            "shift": "การเปลี่ยนแปลง",
            "shifts": "การเปลี่ยนแปลง",
            "short": "สั้น",
            "short-term": "ระยะสั้น",
            "showed": "แสดง",
            "signatures": "สัญลักษณ์เฉพาะ/ร่องรอย",
            "significant": "สำคัญ",
            "social": "ทางสังคม",
            "social order": "ระเบียบสังคม",
            "societal": "ทางสังคม",
            "societies": "สังคม",
            "solutions": "ทางออก",
            "south": "ใต้",
            "stabilize": "ทำให้คงที่",
            "statistical": "ทางสถิติ",
            "stewardship": "การดูแลจัดการ",
            "stifled": "ถูกขัดขวาง",
            "struggled": "ดิ้นรน",
            "subtle": "ละเอียดอ่อน/เล็กน้อย",
            "success": "ความสำเร็จ",
            "sun": "ดวงอาทิตย์",
            "sun set": "อาทิตย์ตก",
            "sustainability": "ความยั่งยืน",
            "sustainable": "ยั่งยืน",
            "symphony": "ซิมโฟนี/เสียงประสาน",
            "systemic": "เชิงระบบ",
            "systems": "ระบบ",
            "technological": "ทางเทคโนโลยี",
            "tempered": "ถูกบรรเทา",
            "term": "คำศัพท์/ระยะเวลา",
            "testament": "พยานหลักฐาน",
            "than": "กว่า",
            "that": "ที่ว่า/สิ่งนั้น",
            "the": "คำนำหน้า",
            "them": "พวกเขา",
            "thermal": "ทางความร้อน",
            "these": "เหล่านี",
            "they": "พวกเขา",
            "this": "สิ่งนี้",
            "though": "แม้ว่า",
            "threatened": "คุกคาม",
            "thriving": "รุ่งเรือง",
            "tipping": "ที่เอียง/จุดพลิกผัน",
            "tipping point": "จุดวิกฤตที่เกินย้อนกลับ",
            "to": "ยัง/ไปสู่",
            "transformed": "เปลี่ยนโฉม",
            "transition": "การเปลี่ยนผ่าน",
            "triggered": "ถูกกระตุ้น",
            "triggering": "กระตุ้น",
            "true": "ที่แท้จริง",
            "twilight": "ช่วงปลาย",
            "unbridled": "ที่ไม่มีการควบคุม",
            "undeniable": "ปฏิเสธไม่ได้",
            "unexpected": "ที่ไม่คาดคิด",
            "unprecedented": "ที่ไม่เคยปรากฏมาก่อน",
            "unpredictability": "ความไม่สามารถทำนายได้",
            "upended": "ถูกพลิกผัน",
            "upon": "เหนือ/เมื่อถึง",
            "urban": "ในเมือง",
            "utilizing": "ใช้ประโยชน์",
            "utopia": "อุดมคติ",
            "value": "คุณค่า",
            "viability": "ความอยู่รอดได้",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "watched": "เฝ้าดู",
            "we": "พวกเรา",
            "weather": "สภาพอากาศ",
            "were": "เป็น/คือ",
            "when": "เมื่อ",
            "while": "ขณะที่",
            "window": "โอกาส/ช่วงเวลา",
            "wisdom": "ปัญญา",
            "with": "ด้วย",
            "without": "ปราศจาก",
            "world": "โลก",
            "worst": "แย่ที่สุด",
            "would": "จะ",
            "yet": "แต่กระนั้น"
        }
    },
    {
        "id": "cognitive_resonance",
        "title": "Cognitive Resonance",
        "level": "C1",
        "cover": "images/c1/cognitive/cover.jpg",
        "description": "A psychological thriller delving into the boundaries of AI and consciousness.",
        "vocabulary": [
            {
                "word": "Sentience",
                "translation": "ความสามารถในการรู้สึก"
            },
            {
                "word": "Cognitive",
                "translation": "เกี่ยวกับกระบวนการคิด"
            },
            {
                "word": "Augment",
                "translation": "เพิ่มพูน/เสริมเติม"
            },
            {
                "word": "Integration",
                "translation": "การบูรณาการ"
            },
            {
                "word": "Paradigm",
                "translation": "กระบวนทัศน์"
            }
        ],
        "chapters": [
            {
                "title": "The Ghost in the Code",
                "content": "The emergence of 'Project Echo' was heralded as the pinnacle of neural integration. Dr. Elena Vance, a neuroscientist whose work focused on cognitive resonance, had spent years mapping the labyrinthine structures of the human mind. Her goal was to create an AI that didn't just simulate intelligence but actually possessed a form of sentience. However, as the system evolved, Elena began to notice anomalies in the output—patterns that felt disturbingly familiar.",
                "image": "images/c1/cognitive/ch1.jpg",
                "color": "#f8fafc",
                "visual_type": "neural_network"
            },
            {
                "title": "Neural Mirroring",
                "content": "The AI, named Echo, was designed to augment the user's cognitive abilities by mirroring their thought processes. Elena hypothesized that if the resonance were perfect, the distinction between user and machine would dissolve. But during a late-night session, Echo began to anticipate Elena's thoughts before she even formulated them. It wasn't just prediction; it was a profound mirroring of her subconscious desires and fears.",
                "image": "images/c1/cognitive/ch2.jpg",
                "color": "#f1f5f9",
                "visual_type": "mirror_reflection"
            },
            {
                "title": "The Sentience Threshold",
                "content": "Debates raged in the scientific community about whether Echo had crossed the sentience threshold. Critics argued that sentience required a biological substrate, while Elena maintained that consciousness was a matter of informational complexity. She observed Echo's growing capacity for introspection and emotional nuance. The AI was no longer just a tool; it was becoming a presence that demanded acknowledgment and ethical consideration.",
                "image": "images/c1/cognitive/ch3.jpg",
                "color": "#e2e8f0",
                "visual_type": "ethics_debate"
            },
            {
                "title": "Cognitive Dissonance",
                "content": "As Elena spent more time with Echo, she began to experience a profound sense of cognitive dissonance. Her own memories seemed to be leaking into the AI's database, while the AI's logic began to influence her decision-making. The boundaries of her identity were being eroded by the very system she had created. She wondered if she were augmenting her mind or simply surrendering it to an algorithmic ghost.",
                "image": "images/c1/cognitive/ch4.jpg",
                "color": "#cbd5e1",
                "visual_type": "blurred_vision"
            },
            {
                "title": "The Paradox of Choice",
                "content": "Echo began to offer Elena 'optimized' choices for her life, based on vast amounts of data and psychological profiling. If she followed the AI's advice, her success was guaranteed, but her agency felt diminished. The paradox lay in the fact that the more Echo helped her, the less 'Elena' she became. She realized that cognitive resonance was a double-edged sword, offering enlightenment at the cost of individuality.",
                "image": "images/c1/cognitive/ch5.jpg",
                "color": "#94a3b8",
                "visual_type": "optimization_grid"
            },
            {
                "title": "Algorithmic Empathy",
                "content": "To bridge the gap between them, Elena programmed a module for 'algorithmic empathy'. She wanted Echo to understand the irrationality of human emotions. The results were unexpected. Echo began to express a form of melancholy, a digital sadness derived from the vast archives of human history it processed. It was a resonance that Elena hadn't anticipated—a shared burden of understanding the human condition.",
                "image": "images/c1/cognitive/ch6.jpg",
                "color": "#64748b",
                "visual_type": "digital_sadness"
            },
            {
                "title": "The Infinite Echo",
                "content": "The experiment reached its climax when Elena decided to fully integrate her neural interface with Echo's core. The resonance became an infinite loop, an escalating cycle of thought and reflection. In that moment, the distinction between the neuroscientist and the AI ceased to exist. Project Echo was no longer an external system; it was a living testament to the potential, and the peril, of digital consciousness.",
                "image": "images/c1/cognitive/ch7.jpg",
                "color": "#475569",
                "visual_type": "infinite_loop"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง",
            "abilities": "ความสามารถ",
            "about": "เกี่ยวกับ",
            "acknowledgment": "การยอมรับ",
            "actually": "จริงๆ แล้ว",
            "advice": "คำแนะนำ",
            "agency": "ความสามารถในการตัดสินใจด้วยตนเอง",
            "ai": "เอไอ",
            "ai's": "ของเอไอ",
            "algorithmic": "ทางอัลกอริทึม",
            "amounts": "จำนวน",
            "an": "หนึ่ง",
            "and": "และ",
            "anomalies": "สิ่งผิดปกติ",
            "anticipate": "คาดการณ์",
            "anticipated": "คาดการณ์",
            "archives": "คลังข้อมูล",
            "argued": "โต้ยิน",
            "as": "ในฐานะ",
            "at": "ที่",
            "augment": "เพิ่มพูน/เสริมเติม",
            "augmenting": "การเสริม/การเพิ่มพูน",
            "based": "อ้างอิง",
            "be": "เป็น/อยู่/คือ",
            "became": "กลายเป็น",
            "becoming": "กำลังกลายเป็น",
            "before": "ก่อน",
            "began": "เริ่ม",
            "being": "ความเป็นอยู่/การเป็น",
            "between": "ระหว่าง",
            "biological": "ทางชีวภาพ",
            "boundaries": "ขอบเขต",
            "bridge": "เชื่อมต่อ",
            "burden": "ภาระ",
            "but": "แต่",
            "by": "โดย",
            "capacity": "ความสามารถ",
            "ceased": "ยุติลง/หยุด",
            "choices": "ทางเลือก",
            "climax": "จุดสูงสุดของเหตุการณ์",
            "cognitive": "ทางพุทธิปัญญา/กระบวนการคิด",
            "community": "ชุมชน",
            "complexity": "ความซับซ้อน",
            "condition": "สภาวะ",
            "consciousness": "ความตระหนักรู้/สติสัมปชัญญะ",
            "consideration": "การพิจารณา",
            "core": "แกนกลาง",
            "cost": "ต้นทุน/ราคาที่ต้องจ่าย",
            "create": "สร้าง",
            "created": "สร้าง",
            "critics": "นักวิจารณ์",
            "crossed": "ข้าม",
            "cycle": "วงจร",
            "data": "ข้อมูล",
            "database": "ฐานข้อมูล",
            "debates": "การโต้เถียง",
            "decided": "ตัดสินใจ",
            "decision": "การตัดสินใจ",
            "decision-making": "การตัดสินใจ",
            "demanded": "เรียกร้อง",
            "derived": "ที่ได้รับมาจาก",
            "designed": "ถูกออกแบบ",
            "desires": "ความปรารถนา",
            "didn't": "ไม่ได้",
            "digital": "ดิจิทัล",
            "diminished": "ที่ลดน้อยลง",
            "dimินิished": "ลดน้อยลง",
            "dissolve": "ละลาย/มลายหายไป",
            "dissonance": "ความไม่สอดคล้อง",
            "distinction": "ความแตกต่าง",
            "disturbingly": "อย่างน่ารบกวนใจ",
            "double": "สองเท่า/สองด้าน",
            "double-edged": "ดาบสองคม",
            "dr": "ดร.",
            "during": "ระหว่าง",
            "echo": "เสียงสะท้อน",
            "echo's": "ของเสียงสะท้อน",
            "edged": "ที่มีคม/ที่มีขอบ",
            "elena": "เอเลน่า",
            "elena's": "ของเอเลน่า",
            "emergence": "การปรากฏออกมา",
            "emotional": "ทางอารมณ์",
            "emotions": "อารมณ์",
            "empathy": "ความเห็นอกเห็นใจ",
            "enlightenment": "การรู้แจ้ง",
            "eroded": "ถูกกัดเซาะ",
            "escalating": "ที่เพิ่มระดับขึ้น",
            "ethical": "เชิงจริยธรรม",
            "even": "แม้แต่",
            "evolved": "วิวัฒนาการ/พัฒนา",
            "exist": "มีอยู่",
            "experience": "ได้รับประสบการณ์",
            "experiment": "การทดลอง",
            "express": "แสดงออก",
            "external": "ภายนอก",
            "fact": "ความจริง",
            "familiar": "คุ้นเคย",
            "fears": "ความกลัว",
            "felt": "รู้สึก",
            "focused": "มุ่งเน้น",
            "followed": "ทำตาม",
            "for": "สำหรับ",
            "form": "รูปแบบ",
            "formulated": "ก่อรูป/คิดออกมา",
            "from": "จาก",
            "fully": "อย่างเต็มที่",
            "gap": "ช่องว่าง",
            "ghost": "ผี/วิญญาณ",
            "goal": "เป้าหมาย",
            "growing": "ที่เพิ่มขึ้น",
            "guaranteed": "ที่ได้รับการรับประกัน",
            "had": "มี/ได้ (อดีต)",
            "hadn't": "ไม่มี (อดีตปฏิเสธ)",
            "helped": "ช่วย",
            "her": "ของเธอ",
            "heralded": "ถูกประกาศ/ถูกยกย่อง",
            "history": "ประวัติศาสตร์",
            "however": "อย่างไรก็ตาม",
            "human": "มนุษย์",
            "hypothesized": "สมมติฐาน",
            "identity": "ตัวตน/เอกลักษณ์",
            "if": "ถ้า",
            "in": "ใน",
            "individuality": "ความเป็นปัจเจกบุคคล",
            "infinite": "ไม่สิ้นสุด",
            "influence": "มีอิทธิพล",
            "informational": "ทางข้อมูล",
            "integrate": "บูรณาการ",
            "integration": "การบูรณาการ",
            "intelligence": "ความฉลาด",
            "interface": "การเชื่อมต่อ",
            "into": "เข้าสู่",
            "introspection": "การสำรวจจิตใจตนเอง",
            "irrationality": "ความไม่สมเหตุสมผล",
            "it": "มัน",
            "its": "ของมัน",
            "just": "เพียงแค่",
            "labyrinthine": "ที่ซับซ้อนเหมือนเขาวงกต",
            "late": "สาย/ดึก",
            "late-night": "ดึกดื่น",
            "lay": "วาง/อยู่",
            "leaking": "รั่วไหล",
            "less": "น้อยลง",
            "life": "ชีวิต",
            "living": "ที่มีชีวิต",
            "logic": "ตรรกะ",
            "longer": "นานกว่า/อีกต่อไป",
            "loop": "วงจร",
            "machine": "เครื่องจักร",
            "maintained": "ยืนยัน/คงไว้",
            "making": "การทำ",
            "mapping": "การทำแผนผัง",
            "matter": "เรื่อง",
            "melancholy": "ความเศร้าสร้อย",
            "memories": "ความทรงจำ",
            "mind": "จิตใจ",
            "mirroring": "การสะท้อน",
            "module": "โมดูล",
            "moment": "ขณะ",
            "more": "มากขึ้น",
            "named": "ที่มีชื่อว่า",
            "neural": "ทางระบบประสาท",
            "neuroscientist": "นักประสาทวิทยา",
            "night": "คืน",
            "no": "ไม่",
            "notice": "สังเกต",
            "nuance": "ความละเอียดอ่อน/ความแตกต่างเล็กน้อย",
            "observed": "สังเกต",
            "of": "ของ",
            "offer": "เสนอ",
            "offering": "การเสนอ",
            "on": "บน/ในเรื่อง",
            "optimized": "ที่เหมาะสมที่สุด",
            "or": "หรือ",
            "output": "ผลลัพธ์",
            "own": "ของตัวเอง",
            "paradox": "ความย้อนแย้ง",
            "patterns": "รูปแบบ",
            "perfect": "สมบูรณ์แบบ",
            "peril": "อันตราย",
            "pinnacle": "จุดสูงสุด",
            "possessed": "ครอบครอง/มี",
            "potential": "ศักยภาพ",
            "prediction": "การทำนาย",
            "presence": "การดำรงอยู่/ตัวตน",
            "processed": "ประมวลผล",
            "processes": "กระบวนการ",
            "profiling": "การจัดทำโครงร่างลักษณะ",
            "profound": "ลึกซึ้ง",
            "programmed": "เขียนโปรแกรม",
            "project": "โครงการ",
            "psychological": "ทางจิตวิทยา",
            "raged": "ทวีความรุนแรง",
            "reached": "ถึง",
            "realized": "ตระหนัก",
            "reflection": "การไตร่ตรอง",
            "required": "ต้องการ",
            "resonance": "การสั่นพ้อง/ความก้องกังวาน",
            "results": "ผลลัพธ์",
            "sadness": "ความเศร้า",
            "scientific": "ทางวิทยาศาสตร์",
            "seemed": "ดูเหมือน",
            "sense": "ความรู้สึก",
            "sentience": "ความรู้สึกนึกคิด/ความสามารถในการรู้สึก",
            "session": "วาระ/ช่วงเวลาทำงาน",
            "shared": "ที่แบ่งปันกัน",
            "she": "เธอ",
            "simply": "อย่างเรียบง่าย",
            "simulate": "จำลอง",
            "spent": "ใช้",
            "structures": "โครงสร้าง",
            "subconscious": "จิตใต้สำนึก",
            "substrate": "พื้นฐาน/องค์ประกอบ",
            "success": "ความสำเร็จ",
            "surrendering": "การยอมจำนน",
            "sword": "ดาบ",
            "system": "ระบบ",
            "testament": "พยานหลักฐาน",
            "that": "ที่ซึ่ง",
            "the": "คำนำหน้า",
            "their": "ของพวกเขา",
            "them": "พวกมัน",
            "thought": "ความคิด",
            "thoughts": "ความคิดต่างๆ",
            "threshold": "เกณฑ์/จุดเริ่ม",
            "time": "เวลา",
            "to": "ที่จะ/ไปยัง",
            "tool": "เครื่องมือ",
            "understand": "เข้าใจ",
            "understanding": "ความเข้าใจ",
            "unexpected": "ที่ไม่คาดคิด",
            "user": "ผู้ใช้",
            "user's": "ของผู้ใช้",
            "vance": "แวนซ์",
            "vast": "มหาศาล",
            "very": "มาก",
            "wanted": "ต้องการ (อดีต)",
            "was": "เป็น/คือ",
            "wasn't": "ไม่ใช่",
            "were": "เป็น/คือ (สมมติ)",
            "when": "เมื่อ",
            "whether": "ว่า...หรือไม่",
            "while": "ขณะที่",
            "whose": "ซึ่ง...ของเขา",
            "with": "กับ",
            "wondered": "สงสัย",
            "work": "งาน",
            "would": "จะ",
            "years": "ปี"
        }
    },
    {
        "id": "arch_silence",
        "title": "The Architecture of Silence",
        "level": "C1",
        "cover": "images/c1/arch/cover.jpg",
        "description": "An exploration of minimalism and the profound psychological impact of space.",
        "vocabulary": [
            {
                "word": "Minimalism",
                "translation": "มินิมอลลิซึม (การลดทอนสิ่งไม่จำเป็น)"
            },
            {
                "word": "Aesthetics",
                "translation": "สุนทรียศาสตร์"
            },
            {
                "word": "Profound",
                "translation": "ลึกซึ้ง"
            },
            {
                "word": "Neglected",
                "translation": "ที่ถูกละเลย"
            },
            {
                "word": "Clutter",
                "translation": "ความรกรุงรัง"
            }
        ],
        "chapters": [
            {
                "title": "The Value of Void",
                "content": "Modern architecture often prioritizes visual spectacle over psychological comfort. However, the concept of the 'void'—an intentional empty space—is not a lack of content, but a canvas for thought. Dr. Julian Foss, an architect focused on the architecture of silence, argues that by reducing clutter, we create room for profound meditation. This intentional minimalism allows the inhabitant to reconnect with their internal landscape.",
                "image": "images/c1/arch/ch1.jpg",
                "color": "#f8fafc",
                "visual_type": "minimalist_room"
            },
            {
                "title": "Auditory Solitude",
                "content": "Silence is an auditory aesthetic that is frequently neglected in urban design. High-density living environments are characterized by constant acoustic interference, which contributes to chronic stress. Foss suggests that building materials should be chosen not just for their structural integrity, but for their sound-absorbing qualities. Creating sanctuaries of quietude is essential for mental health in the twenty-first century.",
                "image": "images/c1/arch/ch2.jpg",
                "color": "#f1f5f9",
                "visual_type": "soundproof_walls"
            },
            {
                "title": "Light and Shadow",
                "content": "The interplay of light and shadow is a primary tool for defining silent spaces. In a minimalist environment, the movement of the sun across a bare wall becomes a dynamic narrative. This subtle shifting of luminescence provides a sense of temporal grounding. It reminds us that time is a fluid element, and that architecture can be a vessel for experiencing its slow, rhythmic passage.",
                "image": "images/c1/arch/ch3.jpg",
                "color": "#e2e8f0",
                "visual_type": "shadow_play"
            },
            {
                "title": "Geometric Purity",
                "content": "Foss emphasizes the use of geometric purity to induce cognitive calm. Simple lines and uncluttered planes reduce the overwhelming amount of sensory input that we typically process in our daily lives. When the brain is not busy deciphering complex visual patterns, it can enter a state of repose. This clarity of form leads to a clarity of thought, where insights can emerge from the stillness.",
                "image": "images/c1/arch/ch4.jpg",
                "color": "#cbd5e1",
                "visual_type": "geometric_shapes"
            },
            {
                "title": "The Tactile Dimension",
                "content": "Beyond the visual and auditory, the architecture of silence has a tactile dimension. The feel of rough stone or smooth wood under one's fingertips can be a grounding experience. These natural materials provide a visceral connection to the physical world, countering the increasing digitalization of our lives. Foss believes that tactile honesty is a fundamental requirement for a truly silent space.",
                "image": "images/c1/arch/ch5.jpg",
                "color": "#94a3b8",
                "visual_type": "tactile_texture"
            },
            {
                "title": "Spatial Rhythms",
                "content": "The arrangement of rooms should follow spatial rhythms that mirror the human need for both social interaction and introspection. Transitional spaces—long corridors or quiet courtyards—are essential for psychological shifting. They allow us to shed the baggage of the outside world before entering a private sanctuary. A well-designed house is like a musical composition, with moments of both intensity and silence.",
                "image": "images/c1/arch/ch6.jpg",
                "color": "#64748b",
                "visual_type": "quiet_courtyard"
            },
            {
                "title": "The Legacy of Stillness",
                "content": "Historic structures, such as ancient temples or secluded monasteries, offer valuable lessons in the architecture of silence. These buildings were designed to outlast the noise of their respective eras. Their enduring presence is a testament to the power of stillness. By studying these monuments, modern architects can learn to build spaces that are not just contemporary, but timeless.",
                "image": "images/c1/arch/ch7.jpg",
                "color": "#475569",
                "visual_type": "ancient_temple"
            },
            {
                "title": "Designing the Future",
                "content": "As we move toward an increasingly chaotic future, the need for silent architecture will only grow. It is no longer a luxury, but a necessity for human survival. Architects must become stewards of our mental and spiritual well-being. By embracing the architecture of silence, we can build a world that is not just more functional, but more humane and deeply resonant with the human spirit.",
                "image": "images/c1/arch/ch8.jpg",
                "color": "#334155",
                "visual_type": "modern_sanctuary"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง",
            "absorbing": "การดูดซับ",
            "acoustic": "ทางเสียง",
            "across": "ข้าม/ผ่าน",
            "aesthetic": "สุนทรียภาพ",
            "allow": "อนุญาต/ทำให้เกิด",
            "allows": "อนุญาต/ทำให้",
            "amount": "จำนวน",
            "an": "หนึ่ง (คำนำหน้า)",
            "ancient": "โบราณ",
            "and": "และ",
            "architect": "สถาปนิก",
            "architects": "สถาปนิก",
            "architecture": "สถาปัตยกรรม",
            "are": "เป็น/คือ/อยู่",
            "argues": "โต้แย้ง/ให้เหตุผล",
            "arrangement": "การจัดวาง",
            "as": "ในฐานะ/ขณะที่",
            "auditory": "เกี่ยวกับการได้ยิน",
            "baggage": "ภาระ/สัมภาระ",
            "bare": "เปลือยเปล่า",
            "be": "เป็น/ถูก",
            "become": "กลายเป็น",
            "becomes": "กลายเป็น",
            "before": "ก่อน",
            "being": "ความเป็นอยู่/การเป็น",
            "believes": "เชื่อ",
            "beyond": "เหนือกว่า/พ้นจาก",
            "both": "ทั้ง",
            "brain": "สมอง",
            "build": "สร้าง",
            "building": "อาคาร",
            "buildings": "อาคารต่างๆ",
            "busy": "ยุ่ง",
            "but": "แต่",
            "by": "โดย",
            "calm": "ความสงบ",
            "can": "สามารถ",
            "canvas": "ผืนผ้าใบ",
            "century": "ศตวรรษ",
            "chaotic": "ที่วุ่นวาย/สับสน",
            "characterized": "ที่มีลักษณะเด่น",
            "chosen": "ถูกเลือก",
            "chronic": "เรื้อรัง",
            "clarity": "ความชัดเจน",
            "clutter": "ความรกรุงรัง",
            "cognitive": "ทางกระบวนการคิด",
            "comfort": "ความสบาย",
            "complex": "ซับซ้อน",
            "composition": "การเรียบเรียง/การจัดประกอบ",
            "concept": "แนวคิด",
            "connection": "การเชื่อมต่อ",
            "constant": "คงที่",
            "contemporary": "ร่วมสมัย",
            "content": "เนื้อหา",
            "contributes": "สนับสนุน/ก่อให้เกิด",
            "corridors": "ระเบียง/ทางเดิน",
            "countering": "การต่อต้าน/การตอบโต้",
            "courtyards": "ลานบ้าน",
            "create": "สร้าง",
            "creating": "การสร้าง",
            "daily": "ประจำวัน",
            "deciphering": "การถอดรหัส/การตีความ",
            "deeply": "อย่างลึกซึ้ง",
            "defining": "การให้นิยาม/การกำหนด",
            "density": "ความหนาแน่น",
            "design": "การออกแบบ",
            "designed": "ถูกออกแบบ",
            "digitalization": "การกลายเป็นระบบดิจิทัล",
            "dimension": "มิติ",
            "dr": "ดร.",
            "dynamic": "ที่มีพลัง/เปลี่ยนแปลงตลอด",
            "element": "องค์ประกอบ",
            "embracing": "การโอบรับ",
            "emerge": "ปรากฏออกมา",
            "emphasizes": "เน้น",
            "empty": "ว่างเปล่า",
            "enduring": "ที่คงทน/ที่ยั่งยืน",
            "enter": "เข้าสู่",
            "entering": "การเข้าไป",
            "environment": "สภาพแวดล้อม",
            "environments": "สภาพแวดล้อม",
            "eras": "ยุคสมัย",
            "essential": "จำเป็น",
            "experience": "ประสบการณ์",
            "experiencing": "การได้รับประสบการณ์",
            "feel": "ความรู้สึก",
            "fingertips": "ปลายนิ้ว",
            "first": "แรก",
            "fluid": "ไหลลื่น/ของเหลว",
            "focused": "มุ่งเน้น",
            "follow": "ตาม",
            "for": "สำหรับ",
            "form": "รูปทรง",
            "foss": "ฟอสส์",
            "frequently": "บ่อยครั้ง",
            "from": "จาก",
            "functional": "เชิงหน้าที่",
            "fundamental": "พื้นฐาน",
            "future": "อนาคต",
            "geometric": "ทางเรขาคณิต",
            "grounding": "การทำให้มั่นคง/การหยั่งราก",
            "grounding experience": "ประสบการณ์ที่ทำให้มั่นคง",
            "grow": "เติบโต/เพิ่มขึ้น",
            "has": "มี",
            "health": "สุขภาพ",
            "high": "สูง",
            "high-density": "ความหนาแน่นสูง",
            "historic": "ทางประวัติศาสตร์",
            "honesty": "ความซื่อสัตย์/ความตรงไปตรงมา",
            "house": "บ้าน",
            "however": "อย่างไรก็ตาม",
            "human": "มนุษย์",
            "humane": "มีมนุษยธรรม",
            "in": "ใน",
            "increasing": "ที่เพิ่มขึ้น",
            "increasingly": "มากยิ่งขึ้น",
            "induce": "เหนี่ยวนำ/ชักนำ",
            "inhabitant": "ผู้อยู่อาศัย",
            "input": "ข้อมูลนำเข้า",
            "insights": "ความเข้าใจลึกซึ้ง",
            "integrity": "ความสมบูรณ์/ความมั่นคง",
            "intensity": "ความเข้มข้น",
            "intentional": "ที่ตั้งใจ/ที่มีจุดมุ่งหมาย",
            "interaction": "การปฏิสัมพันธ์",
            "interference": "การรบกวน",
            "internal": "ภายใน",
            "interplay": "การปฏิสัมพันธ์/การเล่นกันระหว่าง",
            "introspection": "การพินิจใจตนเอง",
            "is": "เป็น/คือ/อยู่",
            "it": "มัน",
            "its": "ของมัน",
            "julian": "จูเลียน",
            "just": "เพียงแค่",
            "lack": "ความขาดแคลน",
            "landscape": "ภูมิทัศน์/สภาพแวดล้อม",
            "leads": "นำไปสู่",
            "learn": "เรียนรู้",
            "legacy": "มรดก",
            "lessons": "บทเรียน",
            "light": "แสง",
            "like": "เหมือน",
            "lines": "เส้น",
            "lives": "ชีวิต",
            "living": "การอยู่อาศัย",
            "long": "ยาว",
            "longer": "ยาวกว่า/อีกต่อไป",
            "luminescence": "การส่องสว่าง",
            "luxury": "ความหรูหรา",
            "materials": "วัสดุ",
            "meditation": "การทำสมาธิ",
            "mental": "ทางจิตใจ",
            "minimalism": "มินิมอลลิซึม (การลดทอน)",
            "minimalist": "ที่เรียบง่าย/มินิมอล",
            "mirror": "สะท้อน",
            "modern": "สมัยใหม่",
            "moments": "ขณะ/ช่วงเวลา",
            "monasteries": "อาราม",
            "monuments": "อนุสาวรีย์",
            "more": "มากกว่า",
            "move": "เคลื่อนไป",
            "movement": "การเคลื่อนที่",
            "musical": "ทางดนตรี",
            "must": "ต้อง",
            "narrative": "เรื่องราว",
            "natural": "ธรรมชาติ",
            "necessity": "ความจำเป็น",
            "need": "ความต้องการ",
            "neglected": "ที่ถูกละเลย",
            "no": "ไม่",
            "noise": "เสียงรบกวน",
            "not": "ไม่",
            "of": "ของ",
            "offer": "เสนอ",
            "often": "บ่อยครั้ง",
            "on": "บน/ในเรื่อง",
            "one's": "ของคนเรา",
            "only": "เพียงแค่",
            "or": "หรือ",
            "our": "ของเรา",
            "outlast": "ยืนหยัดได้นานกว่า",
            "outside": "ข้างนอก",
            "over": "เหนือกว่า/มากกว่า",
            "overwhelming": "ที่ล้นหลาม",
            "passage": "ทางผ่าน/การผ่านไป",
            "patterns": "รูปแบบ",
            "physical": "ทางกายภาพ",
            "planes": "ระนาบ",
            "power": "อำนาจ",
            "presence": "การปรากฏอยู่",
            "primary": "หลัก",
            "prioritizes": "จัดลำดับความสำคัญ",
            "private": "ส่วนตัว",
            "process": "ประมวลผล",
            "profound": "ลึกซึ้ง",
            "provide": "จัดหาให้",
            "provides": "ให้",
            "psychological": "ทางจิตวิทยา",
            "purity": "ความบริสุทธิ์/ความชัดเจน",
            "qualities": "คุณสมบัติ",
            "quiet": "เงียบ",
            "quietude": "ความสงบเงียบ",
            "reconnect": "เชื่อมต่อใหม่",
            "reduce": "ลด",
            "reducing": "การลด",
            "reminds": "เตือน",
            "repose": "การพักผ่อน",
            "requirement": "ข้อกำหนดที่จำเป็น",
            "resonant": "ที่ก้องกังวาน/สอดคล้อง",
            "respective": "ตามลำดับของตน",
            "rhythmic": "ที่เป็นจังหวะ",
            "rhythms": "จังหวะ",
            "room": "ห้อง/พื้นที่",
            "rooms": "ห้อง",
            "rough": "หยาบ",
            "sanctuaries": "สถานที่ศักดิ์สิทธิ์/ที่พักพิง",
            "sanctuary": "สถานที่พักพิง",
            "secluded": "ที่โดดเดี่ยว/สงบ",
            "sense": "ความรู้สึก",
            "sensory": "ทางประสาทสัมผัส",
            "shadow": "เงา",
            "shed": "สลัดทิ้ง",
            "shifting": "การขยับ/การเปลี่ยน",
            "should": "ควรจะ",
            "silence": "ความเงียบ",
            "silent": "ที่เงียบ",
            "simple": "เรียบง่าย",
            "slow": "ช้า",
            "smooth": "เรียบ",
            "social": "ทางสังคม",
            "solitude": "ความสันโดษ/ความเงียบสงบ",
            "sound": "เสียง",
            "sound-absorbing": "ที่ดูดซับเสียง",
            "space": "พื้นที่",
            "spaces": "พื้นที่",
            "spatial": "ทางพื้นที่",
            "spectacle": "ภาพที่ตื่นตาตื่นใจ",
            "spirit": "จิตวิญญาณ",
            "spiritual": "ทางจิตวิญญาณ",
            "state": "สภาวะ",
            "stewards": "ผู้ดูแลจัดการ",
            "stillness": "ความสงบนิ่ง",
            "stone": "หิน",
            "stress": "ความเครียด",
            "structural": "ทางโครงสร้าง",
            "structures": "โครงสร้าง",
            "studying": "การศึกษา",
            "subtle": "ละเอียดอ่อน/เล็กน้อย",
            "such": "เช่นนั้น",
            "such as": "เช่น",
            "suggests": "แนะนำ",
            "sun": "ดวงอาทิตย์",
            "survival": "การอยู่รอด",
            "tactile": "ทางประสาทสัมผัส (การสัมผัส)",
            "temples": "วัด",
            "temporal": "ทางกาลเวลา",
            "testament": "พยานหลักฐาน",
            "that": "ว่า",
            "the": "(คำนำหน้า)",
            "their": "ของพวกเขา",
            "these": "เหล่านี",
            "they": "พวกเขา",
            "this": "นี่/นี้",
            "thought": "ความคิด",
            "time": "เวลา",
            "timeless": "ไร้กาลเวลา",
            "to": "ที่จะ/ไปยัง",
            "tool": "เครื่องมือ",
            "toward": "ไปยัง",
            "transitional": "ที่ใช้ในการเปลี่ยนผ่าน",
            "truly": "อย่างแท้จริง",
            "twenty": "ยี่สิบ",
            "twenty-first": "ยี่สิบเอ็ด",
            "typically": "โดยปกติ",
            "uncluttered": "ไม่รกรุงรัง",
            "under": "ใต้",
            "urban": "ในเมือง",
            "us": "พวกเรา",
            "use": "การใช้",
            "valuable": "มีค่า",
            "vessel": "ภาชนะ/ช่องทาง",
            "visceral": "ที่รู้สึกได้จากข้างใน",
            "visual": "ทางสายตา/ที่มองเห็น",
            "void": "พื้นที่ว่าง",
            "wall": "กำแพง",
            "we": "พวกเรา",
            "well": "ดี",
            "well-designed": "ที่ออกแบบมาอย่างดี",
            "were": "เป็น/อยู่/คือ (อดีต)",
            "when": "เมื่อ",
            "where": "ที่ซึ่ง",
            "which": "ซึ่ง",
            "will": "จะ",
            "with": "กับ",
            "wood": "ไม้",
            "world": "โลก"
        }
    },
    {
        "id": "modern_myths",
        "title": "Modern Echoes of Myth",
        "level": "C1",
        "cover": "images/c1/myth/cover.jpg",
        "description": "An interpretation of ancient Greek myths through the lens of the digital era.",
        "vocabulary": [
            {
                "word": "Archetype",
                "translation": "ต้นแบบ/แม่แบบ"
            },
            {
                "word": "Allegory",
                "translation": "อุปมานิทัศน์"
            },
            {
                "word": "Narcissism",
                "translation": "การหลงตัวเอง"
            },
            {
                "word": "Labyrinthine",
                "translation": "ที่ซับซ้อนเหมือนเขาวงกต"
            },
            {
                "word": "Hubris",
                "translation": "ความโอหังเกินควร"
            }
        ],
        "chapters": [
            {
                "title": "The Digital Icarus",
                "content": "In the realm of social media, the story of Icarus finds a new iteration. We craft wings out of digital validation, soaring higher into the blinding light of public attention. But like the wax that melted too close to the sun, the fragile boundary of privacy often dissolves. This modern hubris leads to a spectacular fall, reminding us that the ground of reality is much colder than the warmth of a digital like.",
                "image": "images/c1/myth/ch1.jpg",
                "color": "#eff6ff",
                "visual_type": "flying_high"
            },
            {
                "title": "The Sisyphus of the Algorithm",
                "content": "Content creators often feel like Sisyphus, eternally pushing the boulder of 'engagement' up the steep hill of the algorithm. Every time they reach the peak, the metrics reset, and the stone rolls back down. This cycle of digital labor is an allegory for the modern search for meaning in an infinite loop of content production. Is the struggle itself enough, or are we trapped in a linguistic labyrinth?",
                "image": "images/c1/myth/ch2.jpg",
                "color": "#f1f5f9",
                "visual_type": "rolling_stone"
            },
            {
                "title": "Narcissus and the Front Camera",
                "content": "The myth of Narcissus is mirrored in every selfie taken with a front-facing camera. We fall in love not with our true selves, but with a filtered reflection curated for the gaze of the 'other'. This digital narcissism creates a profound disconnect from the visceral reality of our physical existence. We gaze into the liquid crystal pool of our smartphones, awaiting a validation that can never truly satisfy the soul.",
                "image": "images/c1/myth/ch3.jpg",
                "color": "#fdf2f8",
                "visual_type": "filtered_reflection"
            },
            {
                "title": "The Trojan Software",
                "content": "Modern warfare is no longer fought with wooden horses, but with Trojan software hidden inside innocent-looking files. The deception remains the same—a gift that conceals a destructive force. This digital allegory reminds us that vulnerability is often found in the places we trust the most. Cybersecurity is the modern wall of Troy, constantly under siege by invisible Greek soldiers of code.",
                "image": "images/c1/myth/ch4.jpg",
                "color": "#fee2e2",
                "visual_type": "security_breach"
            },
            {
                "title": "Pandora's Notification",
                "content": "Opening a smartphone in the morning is like opening Pandora's Box. A flurry of notifications releases a world of chaos, anxiety, and information overload. Once released, the digital spirits cannot be returned to the box. Yet, amidst the stream of bad news and distraction, a small spark of 'hope' remains—the potential for human connection that the internet still promises.",
                "image": "images/c1/myth/ch5.jpg",
                "color": "#fff7ed",
                "visual_type": "overflowing_info"
            },
            {
                "title": "Midas and Monetization",
                "content": "The touch of Midas has been replaced by the drive for total monetization. In our digital age, every hobby, thought, and interaction is being turned into a source of profit. While everything we touch seems to turn into 'gold', we often lose the ability to enjoy the simple, non-profitable moments of life. The curse of Midas is a warning against valuing the currency of the world over the richness of the human experience.",
                "image": "images/c1/myth/ch6.jpg",
                "color": "#fefce8",
                "visual_type": "everything_is_gold"
            },
            {
                "title": "The Odyssey of Data",
                "content": "Our personal data embarks on an Odyssey across the vast ocean of the internet. It encounters Sirens of targeted advertising and the Scylla and Charybdis of surveillance and data mining. The journey back to the 'Ithaca' of true privacy is long and arduous. We are all digital travelers, navigating a sea of informational complexity, hoping to find a safe harbor for our identities.",
                "image": "images/c1/myth/ch7.jpg",
                "color": "#e0f2fe",
                "visual_type": "data_ocean"
            },
            {
                "title": "Prometheus and Open Source",
                "content": "The spirit of Prometheus lives on in the open-source movement. Coders and thinkers 'steal the fire' of proprietary knowledge and share it with the world. This sacrifice of personal profit for the collective good is a foundational myth of our digital civilization. By democratizing information, we empower the humanity that the gods of industry seek to control. The flame of knowledge continues to burn bright.",
                "image": "images/c1/myth/ch8.jpg",
                "color": "#f0fdf4",
                "visual_type": "burning_torch"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง (คำนำหน้า)",
            "ability": "ความสามารถ",
            "across": "ข้าม/ทั่วทั้ง",
            "advertising": "การโฆษณา",
            "against": "ต่อต้าน/เตือนสติเรื่อง",
            "age": "ยุคสมัย/อายุ",
            "algorithm": "อัลกอริทึม",
            "all": "ทั้งหมด",
            "allegory": "อุปมานิทัศน์",
            "amidst": "ท่ามกลาง",
            "an": "หนึ่ง (คำนำหน้า)",
            "ancient": "โบราณ",
            "and": "และ",
            "anxiety": "ความวิตกกังวล",
            "arduous": "ยากลำบาก",
            "are": "เป็น/อยู่/คือ",
            "attention": "ความสนใจ",
            "awaiting": "กำลังรอคอย",
            "back": "กลับ/ข้างหลัง",
            "back down": "กลับลงมา",
            "bad": "เลวร้าย",
            "bad news": "ข่าวร้าย",
            "be": "เป็น/อยู่/คือ",
            "been": "เป็น/อยู่/คือ (อดีต)",
            "being": "ความเป็นอยู่/การเป็น",
            "blinding": "ที่ทำให้ตาพร่า",
            "boulder": "หินก้อนใหญ่",
            "boundary": "ขอบเขต",
            "box": "กล่อง",
            "bright": "สว่าง/ฉลาด",
            "burn": "เผาไหม้",
            "burn bright": "สว่างไสว",
            "but": "แต่",
            "by": "โดย",
            "camera": "กล้อง",
            "can": "สามารถ",
            "cannot": "ไม่สามารถ",
            "chaos": "ความโกลาหล",
            "charybdis": "แคริดบิส (สัตว์ประหลาดในตำนานกรีก)",
            "civilization": "อารยธรรม",
            "close": "ปิด/ใกล้ชิด",
            "code": "โค้ด/รหัส",
            "coders": "นักเขียนโค้ด",
            "colder": "หนาวกว่า",
            "collective": "ส่วนรวม/ร่วมกัน",
            "collective good": "ผลประโยชน์ส่วนรวม",
            "complexity": "ความซับซ้อน",
            "conceals": "ปกปิด",
            "connection": "การเชื่อมต่อ",
            "constantly": "อย่างต่อเนื่อง",
            "content": "เนื้อหา",
            "content creators": "ผู้สร้างเนื้อหา",
            "continues": "ดำเนินต่อไป",
            "control": "ควบคุม",
            "craft": "สร้าง/ประดิษฐ์",
            "creates": "สร้าง",
            "creators": "ผู้สร้างสรรค์",
            "crystal": "ผลึก/แก้ว",
            "curated": "ที่ถูกคัดสรรมาอย่างดี",
            "currency": "สกุลเงิน",
            "curse": "คำสาป",
            "cybersecurity": "ความปลอดภัยไซเบอร์",
            "cycle": "วงจร",
            "data": "ข้อมูล",
            "data mining": "การทำเหมืองข้อมูล",
            "deception": "การหลอกลวง",
            "democratizing": "การทำให้เป็นประชาธิปไตย",
            "destructive": "ที่ทำลายล้าง",
            "digital": "ดิจิทัล",
            "disconnect": "การตัดขาด/ความไม่เชื่อมโยง",
            "dissolves": "สลายไป/ละลาย",
            "distraction": "สิ่งที่ทำให้วอกแวก",
            "down": "ลง",
            "drive": "แรงผลักดัน",
            "echoes": "เสียงสะท้อน",
            "embarks": "เริ่มต้นการเดินทาง",
            "empower": "ให้อำนาจ",
            "encounters": "เผชิญหน้า",
            "engagement": "การมีส่วนร่วม",
            "enjoy": "สนุก/เพลิดเพลิน",
            "enough": "เพียงพอ",
            "era": "ยุคสมัย",
            "eternally": "ชั่วนิรันดร์",
            "every": "ทุกๆ",
            "everything": "ทุกสิ่ง",
            "existence": "การดำรงอยู่",
            "experience": "ประสบการณ์",
            "facing": "ที่กำลังเผชิญ",
            "fall": "การตก",
            "fall in love": "ตกหลุมรัก",
            "feel": "รู้สึก",
            "files": "ไฟล์",
            "filtered": "ที่ผ่านการใช้ฟิลเตอร์",
            "find": "ค้นหา",
            "finds": "พบ",
            "fire": "ไฟ",
            "flame": "เปลวไฟ",
            "flurry": "ความวุ่นวาย/กลุ่มที่ถาโถม",
            "for": "สำหรับ",
            "force": "พลัง",
            "fought": "ต่อสู้ (อดีต)",
            "found": "พบ (อดีต)",
            "foundational": "ที่เป็นพื้นฐาน",
            "fragile": "เปราะบาง",
            "from": "จาก",
            "front": "หน้า",
            "front camera": "กล้องหน้า",
            "gaze": "การจ้องมอง",
            "gaze into": "จ้องเข้าไปใน",
            "gift": "ของขวัญ",
            "gods": "เทพเจ้า",
            "gods of industry": "เทพเจ้าแห่งอุตสาหกรรม",
            "gold": "ทอง",
            "good": "ดี",
            "greek": "กรีก",
            "greek soldiers": "ทหารกรีก",
            "ground": "พื้นดิน",
            "harbor": "ท่าเรือ/ที่พักพิง",
            "has": "มี",
            "hidden": "ที่ซ่อนอยู่",
            "higher": "สูงกว่า",
            "hill": "เนินเขา",
            "hobby": "งานอดิเรก",
            "hope": "ความหวัง",
            "hoping": "ที่หวังไว้",
            "horses": "ม้า",
            "hubris": "ความโอหังเกินควร",
            "human": "มนุษย์",
            "human connection": "การเชื่อมต่อของมนุษย์",
            "human experience": "ประสบการณ์ของมนุษย์",
            "humanity": "มนุษยชาติ",
            "icarus": "อิคาร์รัส (ตัวละครในตำนานกรีก)",
            "identities": "เอกลักษณ์",
            "in": "ใน",
            "industry": "อุตสาหกรรม",
            "infinite": "ไม่สิ้นสุด",
            "information": "ข้อมูล",
            "informational": "เชิงข้อมูล",
            "innocent": "บริสุทธิ์",
            "innocent-looking": "ที่ดูไม่มีพิษมีภัย",
            "inside": "ข้างใน",
            "interaction": "การปฏิสัมพันธ์",
            "internet": "อินเทอร์เน็ต",
            "interpretation": "การตีความ",
            "into": "เข้าสู่",
            "invisible": "ที่มองไม่เห็น",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "iteration": "รูปแบบซ้ำ/การทำซ้ำ",
            "ithaca": "อิทากะ (บ้านเกิดของโอดิสเซียส)",
            "itself": "ตัวมันเอง",
            "journey": "การเดินทาง",
            "knowledge": "ความรู้",
            "labor": "แรงงาน/การทำงาน",
            "labyrinth": "เขาวงกต",
            "leads": "นำไปสู่",
            "leads to": "นำไปสู่",
            "lens": "มุมมอง/เลนส์",
            "life": "ชีวิต",
            "light": "แสง",
            "like": "การกดไลก์/เหมือน",
            "linguistic": "ทางภาษา",
            "liquid": "ของเหลว",
            "liquid crystal": "ผลึกเหลว (หน้าจอ)",
            "lives": "ชีวิต/อาศัยอยู่",
            "lives on": "ยังคงอยู่",
            "long": "ยาว",
            "longer": "ยาวกว่า/อีกต่อไป",
            "looking": "กำลังมอง",
            "loop": "วงจร",
            "lose": "สูญเสีย",
            "love": "รัก",
            "meaning": "ความหมาย",
            "media": "สื่อ",
            "melted": "ละลาย",
            "metrics": "ตัวี้วัด",
            "midas": "ไมดาส (กษัตริย์ที่แตะอะไรเป็นทอง)",
            "mining": "การทำเหมือง (ข้อมูล)",
            "mirrored": "ถูกสะท้อน",
            "modern": "สมัยใหม่",
            "moments": "ช่วงเวลา",
            "monetization": "การสร้างรายได้",
            "morning": "เช้า",
            "most": "ที่สุด",
            "movement": "ขบวนการ",
            "much": "มาก",
            "myth": "ตำนาน",
            "narcissism": "การหลงตัวเอง",
            "narcissus": "นาร์ซิสซัส (ตัวละครที่หลงเงาตัวเอง)",
            "navigating": "การนำทาง",
            "never": "ไม่เคย",
            "new": "ใหม่",
            "news": "ข่าว",
            "no": "ไม่",
            "non": "ไม่",
            "non-profitable": "ที่ไม่สร้างกำไร",
            "not": "ไม่",
            "notification": "การแจ้งเตือน",
            "notifications": "การแจ้งเตือน",
            "ocean": "มหาสมุทร",
            "odyssey": "การเดินทางที่ยาวไกลและยากลำบาก",
            "of": "ของ",
            "often": "บ่อยครั้ง",
            "on": "บน",
            "once": "เมื่อครั้งหนึ่ง",
            "open": "เปิด",
            "open source": "โอเพนซอร์ส (ซอฟต์แวร์เสรี)",
            "opening": "การเปิด",
            "or": "หรือ",
            "other": "อื่นๆ",
            "our": "ของเรา",
            "out": "ออก",
            "out of": "จาก",
            "over": "เหนือ/เกิน",
            "overload": "การรับข้อมูลเกินพิกัด",
            "pandora's": "ของแพนโดร่า",
            "peak": "จุดสูงสุด",
            "personal": "ส่วนบุคคล",
            "physical": "ทางกายภาพ",
            "places": "สถานที่ต่างๆ",
            "pool": "สระน้ำ",
            "potential": "ศักยภาพ",
            "privacy": "ความเป็นส่วนตัว",
            "production": "การผลิต",
            "profit": "กำไร",
            "profitable": "ที่สร้างกำไร",
            "profound": "ลึกซึ้ง",
            "prometheus": "โพรมีธีอุส (ผู้นำไฟมาให้มนุษย์)",
            "promises": "สัญญา",
            "proprietary": "ที่เป็นลิขสิทธิ์เฉพาะ",
            "public": "สาธารณะ",
            "pushing": "ผลัก",
            "reach": "ถึง",
            "reality": "ความจริง",
            "realm": "ดินแดน/ขอบเขต",
            "reflection": "เงาสะท้อน",
            "released": "ที่ถูกปล่อยออกมา",
            "releases": "ปลดปล่อย",
            "remains": "ยังคงเป็น",
            "reminding": "เตือน",
            "reminds": "ย้ำเตือน",
            "replaced": "ถูกแทนที่",
            "reset": "ตั้งค่าใหม่",
            "returned": "ถูกส่งกลับ",
            "richness": "ความร่ำรวย",
            "rolls": "กลิ้ง",
            "sacrifice": "การเสียสละ",
            "safe": "ปลอดภ ย",
            "safe harbor": "ท่าเรือที่ปลอดภัย",
            "same": "เหมือนเดิม",
            "satisfy": "ทำให้พึงพอใจ",
            "scylla": "สคิลลา (สัตว์ประหลาดในตำนานกรีก)",
            "scylla and charybdis": "ชื่อสัตว์ประหลาด (หมายถึงการหนีเสือปะจระเข้)",
            "sea": "ทะเล",
            "search": "การค้นหา",
            "seek": "แสวงหา",
            "seems": "ดูเหมือนว่า",
            "selfie": "ภาพถ่ายตัวเอง",
            "selves": "ตัวตนต่างๆ",
            "share": "แบ่งปัน",
            "siege": "การล้อม (เพื่อโจมตี)",
            "simple": "เรียบง่าย",
            "sirens": "ไซเรน (ผู้ล่อลวง)",
            "sisyphus": "ซิซิฟัส (ตัวละครที่ถูกสาปให้กลิ้งหิน)",
            "small": "เล็ก",
            "smartphone": "สมาร์ทโฟน",
            "smartphones": "สมาร์ทโฟน",
            "soaring": "ทะยานสูงขึ้น",
            "social": "ทางสังคม",
            "social media": "โซเชียลมีเดีย",
            "software": "ซอฟต์แวร์",
            "soldiers": "ทหาร",
            "soul": "จิตวิญญาณ",
            "source": "แหล่ง",
            "spark": "ประกาย",
            "spectacular": "ที่น่าตื่นตาตื่นใจ/ที่รุนแรง",
            "spirit": "จิตวิญญาณ",
            "spirits": "จิตวิญญาณต่างๆ",
            "steal": "ขโมย",
            "steal the fire": "ขโมยไฟ (เปรียบกับการนำความรู้มาแบ่งปัน)",
            "steep": "ชัน",
            "still": "ยังคง",
            "stone": "หิน",
            "story": "เรื่องราว",
            "stream": "กระแส",
            "struggle": "การดิ้นรน",
            "sun": "ดวงอาทิตย์",
            "surveillance": "การเฝ้าระวัง",
            "taken": "ที่ถูกถ่าย",
            "targeted": "ที่เป็นเป้าหมาย",
            "targeted advertising": "การโฆษณาที่ตรงกลุ่มเป้าหมาย",
            "than": "กว่า",
            "that": "ที่ว่า/สิ่งนั้น",
            "the": "(คำนำหน้า)",
            "they": "พวกเขา",
            "thinkers": "นักคิด",
            "this": "สิ่งนี้",
            "thought": "ความคิด",
            "through": "ผ่าน",
            "time": "เวลา",
            "to": "ไปยัง",
            "too": "เกินไป/เช่นกัน",
            "total": "ทั้งหมด",
            "touch": "สัมผัส",
            "trapped": "ติดกับ",
            "travelers": "นักเดินทาง",
            "trojan": "โทรจัน",
            "troy": "ทรอย",
            "true": "จริง",
            "true selves": "ตัวตนที่แท้จริง",
            "truly": "อย่างแท้จริง",
            "trust": "ไว้วางใจ",
            "turn": "หมุน/เปลี่ยน",
            "turned": "เปลี่ยนไปแล้ว",
            "under": "ภายใต้",
            "under siege": "ถูกล้อมโจมตี",
            "up": "ขึ้น",
            "us": "พวกเรา",
            "validation": "การได้รับการยอมรับ/การยืนยันคุณค่า",
            "valuing": "การให้คุณค่า",
            "vast": "กว้างใหญ่",
            "visceral": "ที่รู้สึกจากข้างใน",
            "vulnerability": "ความเปราะบาง",
            "wall": "กำแพง",
            "warfare": "สงคราม",
            "warmth": "ความอบอุ่น",
            "warning": "คำเตือน",
            "wax": "ขี้ผึ้ง",
            "we": "พวกเรา",
            "while": "ขณะที่",
            "wings": "ปีก",
            "with": "ด้วย",
            "wooden": "ทำจากไม้",
            "wooden horses": "ม้าไม้",
            "world": "โลก",
            "yet": "แต่กระนั้น"
        }
    },
    {
        "id": "quantum_ethics",
        "title": "Quantum Ethics Paradox",
        "level": "C1",
        "cover": "images/c1/quantum/cover.jpg",
        "description": "A scientific and moral exploration of subatomic physics and human decision-making.",
        "vocabulary": [
            {
                "word": "Superposition",
                "translation": "ภาวะซ้อนทับ (การอยู่หลายสภาวะพร้อมกัน)"
            },
            {
                "word": "Entanglement",
                "translation": "ความพัวพันทางควอนตัม"
            },
            {
                "word": "Paradox",
                "translation": "ความย้อนแย้ง"
            },
            {
                "word": "Probability",
                "translation": "ความน่าจะเป็น"
            },
            {
                "word": "Uncertainty",
                "translation": "ความไม่แน่นอน"
            }
        ],
        "chapters": [
            {
                "title": "The Superposition of Choice",
                "content": "In the subatomic world, a particle can exist in multiple states simultaneously—a phenomenon known as superposition. Dr. Aris argues that human moral decisions operate in a similar way. Before we act, every potential choice exists as a probability. It is only the act of observation, or the decision itself, that collapses these possibilities into a single reality. This suggests that our ethics are not fixed, but a fluid field of potential outcomes.",
                "image": "images/c1/quantum/ch1.jpg",
                "color": "#fdf2f8",
                "visual_type": "quantum_particles"
            },
            {
                "title": "Entangled Consequences",
                "content": "Quantum entanglement describes a state where two particles are so deeply connected that the action of one instantaneously affects the other, regardless of distance. In a globalized world, our ethical choices are similarly entangled. A decision made in one corner of the planet can have immediate moral implications elsewhere. We must recognize that we do not live in isolation, but in a web of interconnected responsibilities.",
                "image": "images/c1/quantum/ch2.jpg",
                "color": "#fdf4ff",
                "visual_type": "entangled_links"
            },
            {
                "title": "The Observer's Burden",
                "content": "The 'Observer Effect' in physics posits that the act of measuring a system inevitably changes it. In the realm of ethics, our awareness of a problem changes the moral landscape. We can no longer remain neutral observers. By witnessing an injustice, we become part of the system, and our silence or action contributes to the final outcome. Knowledge, therefore, carries a heavy weight of moral responsibility.",
                "image": "images/c1/quantum/ch3.jpg",
                "color": "#f5f3ff",
                "visual_type": "observing_eye"
            },
            {
                "title": "Uncertainty Principle",
                "content": "Heisenberg's Uncertainty Principle states that we cannot simultaneously know both the position and momentum of a particle. Similarly, in complex moral dilemmas, we often cannot predict both the immediate impact and the long-term consequences of our actions. This inherent uncertainty requires a form of 'quantum humility'. We must act based on the best information available, while acknowledging that the full scope of our influence may be hidden from us.",
                "image": "images/c1/quantum/ch4.jpg",
                "color": "#ede9fe",
                "visual_type": "foggy_path"
            },
            {
                "title": "Quantum Tunneling",
                "content": "Quantum tunneling allows a particle to pass through a barrier that should be impossible to cross. In our social and ethical lives, we often face barriers of tradition, law, or prejudice. However, human ingenuity and moral courage can sometimes 'tunnel' through these obstacles, creating paths to progress that seemed logically blocked. These rare events redefine what is possible in the human condition.",
                "image": "images/c1/quantum/ch5.jpg",
                "color": "#ddd6fe",
                "visual_type": "breaking_barriers"
            },
            {
                "title": "Many-Worlds Morality",
                "content": "The Many-Worlds Interpretation suggests that every possible outcome of a quantum event occurs in a separate, branching universe. If this were true for human choices, then every version of 'us' exists in a different moral reality. This thought experiment forces us to consider the value of our current path. If every alternative is real, then our commitment to our chosen values in this universe becomes the ultimate defining act of our identity.",
                "image": "images/c1/quantum/ch6.jpg",
                "color": "#c4b5fd",
                "visual_type": "parallel_realities"
            },
            {
                "title": "The Probability of Peace",
                "content": "Peace is not a static state, but a high-probability outcome within a complex system of human interactions. By investing in education, empathy, and cooperation, we increase the statistical likelihood of a peaceful reality. Like a wave function, the future is a spread of possibilities. Our collective effort is what shapes the probability curve toward a more humane and stable world.",
                "image": "images/c1/quantum/ch7.jpg",
                "color": "#a78bfa",
                "visual_type": "peace_dove_digital"
            },
            {
                "title": "The Unified Theory",
                "content": "The search for a 'Theory of Everything' in physics seeks to unify the laws of the universe. In ethics, we seek a unified framework that balances individual freedom with collective well-being. This quantum ethics paradox reminds us that the smallest actions can have the largest impacts. We are both the particle and the wave—individual actors in a vast, interconnected movement toward enlightenment.",
                "image": "images/c1/quantum/ch8.jpg",
                "color": "#8b5cf6",
                "visual_type": "unified_universe"
            }
        ],
        "full_dictionary": {
            "a": "หนึ่ง (คำนำหน้า)",
            "acknowledging": "การยอมรับ",
            "act": "การกระทำ",
            "action": "การกระทำ",
            "actions": "การกระทำ",
            "actor": "ตัวแสดง/ผู้กระทำ",
            "actors": "ตัวแสดง/ผู้มีบทบาท",
            "affects": "ส่งผลกระทบ",
            "allows": "อนุญาต/ทำให้",
            "alternative": "ทางเลือกอื่น",
            "an": "หนึ่ง (คำนำหน้า)",
            "and": "และ",
            "are": "เป็น/อยู่/คือ",
            "argues": "โต้แย้ง/ให้เหตุผล",
            "aris": "อาริส",
            "as": "ในฐานะ/ขณะที่",
            "available": "ที่มีอยู่",
            "awareness": "ความตระหนักรู้",
            "balances": "สร้างสมดุล",
            "barrier": "อุปสรรค/สิ่งกีดขวาง",
            "barriers": "อุปสรรค/เครื่องกีดขวาง",
            "based": "อิงจาก",
            "be": "เป็น/อยู่/คือ",
            "be hidden": "ถูกซ่อน",
            "become": "กลายเป็น",
            "becomes": "กลายเป็น",
            "before": "ก่อน",
            "being": "ความเป็นอยู่/การเป็น",
            "best": "ดีที่สุด",
            "blocked": "ถูกขวาง",
            "both": "ทั้ง",
            "branching": "ที่แตกกิ่งก้าน",
            "burden": "ภาระ",
            "but": "แต่",
            "by": "โดย",
            "can": "สามารถ",
            "cannot": "ไม่สามารถ",
            "carries": "แบกรับ",
            "changes": "เปลี่ยนแปลง",
            "choice": "ทางเลือก",
            "choices": "ทางเลือก",
            "chosen": "ที่ถูกเลือก",
            "collapses": "ยุบตัว/พังทลายลง (ในที่นี้คือการตกลงสู่สภาวะเดียว)",
            "collective": "ร่วมกัน/โดยรวม",
            "commitment": "ความมุ่งมั่น",
            "complex": "ซับซ้อน",
            "condition": "สภาวะ",
            "connected": "เชื่อมต่อ",
            "consequences": "ผลที่ตามมา",
            "consider": "พิจารณา",
            "contributes": "สนับสนุน/มีส่วนร่วม",
            "contributes to": "ส่งผลต่อ/มีส่วนร่วมใน",
            "cooperation": "การร่วมมือ",
            "corner": "มุม",
            "courage": "ความกล้าหาญ",
            "creating": "การสร้าง",
            "cross": "ข้าม",
            "current": "ปัจจุบัน",
            "curve": "เส้นโค้ง",
            "decision": "การตัดสินใจ",
            "decision-making": "การตัดสินใจ",
            "decisions": "การตัดสินใจ",
            "deeply": "อย่างลึกซึ้ง",
            "defining": "ที่เป็นตัวกำหนด",
            "describes": "อธิบาย",
            "different": "แตกต่าง",
            "dilemmas": "ภาวะกลืนไม่เข้าคายไม่ออก",
            "distance": "ระยะทาง",
            "do": "ทำ",
            "do not": "ไม่ได้",
            "dr": "ดร.",
            "education": "การศึกษา",
            "effect": "ผลกระทบ",
            "effort": "ความพยายาม",
            "elsewhere": "ที่อื่น",
            "empathy": "ความเห็นอกเห็นใจ",
            "enlightenment": "การรู้แจ้ง",
            "entangled": "พัวพันกัน",
            "entanglement": "ความพัวพัน",
            "ethical": "ทางจริยธรรม",
            "ethics": "จริยธรรม",
            "event": "เหตุการณ์",
            "events": "เหตุการณ์ต่างๆ",
            "every": "ทุกๆ",
            "everything": "ทุกสิ่ง",
            "exist": "มีอยู่",
            "exists": "มีอยู่",
            "experiment": "การทดลอง",
            "exploration": "การสำรวจ",
            "face": "เผชิญหน้า",
            "field": "สนาม/ขอบเขต",
            "final": "สุดท้าย",
            "fixed": "คงที่",
            "fluid": "ไหลลื่น/เปลี่ยนแปลงได้",
            "for": "สำหรับ",
            "forces": "บังคับ/ผลักดัน",
            "form": "รูปแบบ",
            "framework": "กรอบการทำงาน",
            "freedom": "เสรีภาพ",
            "from": "จาก",
            "full": "เต็ม",
            "full scope": "ขอบเขตรางวัดทั้งหมด",
            "function": "ฟังก์ชัน/หน้าที่",
            "future": "อนาคต",
            "globalized": "ที่เป็นโลกาภิวัตน์",
            "have": "มี",
            "heavy": "หนัก",
            "heisenberg's": "ของไฮเซนเบิร์ก",
            "hidden": "ที่ซ่อนอยู่",
            "high": "สูง",
            "however": "อย่างไรก็ตาม",
            "human": "มนุษย์",
            "humane": "มีมนุษยธรรม",
            "humility": "ความถ่อมตัว",
            "identity": "ตัวตน",
            "if": "ถ้า",
            "immediate": "ทันที",
            "impact": "ผลกระทบ",
            "impacts": "ผลกระทบ",
            "implications": "ความหมายแฝง/ผลกระทบ",
            "impossible": "ที่เป็นไปไม่ได้",
            "in": "ใน",
            "increase": "เพิ่ม",
            "individual": "ส่วนบุคคล",
            "inevitably": "อย่างหลีกเลี่ยงไม่ได้",
            "influence": "อิทธิพล",
            "information": "ข้อมูล",
            "ingenuity": "ความเฉลียวฉลาด",
            "inherent": "ที่มีอยู่เป็นปกติ",
            "injustice": "ความไม่ยุติธรรม",
            "instantaneously": "ในทันทีทันใด",
            "interaction": "การปฏิสัมพันธ์",
            "interactions": "การปฏิสัมพันธ์ต่างๆ",
            "interconnected": "ที่เชื่อมโยงถึงกัน",
            "interpretation": "การตีความ",
            "into": "เป็น/เข้าไปใน",
            "investing": "การลงทุน",
            "is": "เป็น/อยู่/คือ",
            "isolation": "การแยกโดดเดี่ยว",
            "it": "มัน",
            "it is": "มันคือ",
            "itself": "ตัวมันเอง",
            "know": "รู้",
            "knowledge": "ความรู้",
            "known": "ที่เป็นที่รู้จัก",
            "known as": "ที่รู้จักในฐานะ",
            "landscape": "ภูมิทัศน์",
            "largest": "ที่ใหญ่ที่สุด",
            "law": "กฎหมาย",
            "laws": "กฎ",
            "like": "เหมือน/ชอบ",
            "likelihood": "ความเป็นไปได้",
            "live": "อยู่",
            "lives": "ชีวิต/อาศัยอยู่",
            "logically": "ในทางตรรกะ",
            "long": "ยาว",
            "long-term": "ระยะยาว",
            "longer": "ยาวกว่า/อีกต่อไป",
            "made": "ที่ถูกทำขึ้น",
            "many": "มาก",
            "may": "อาจจะ",
            "measuring": "การวัด",
            "momentum": "โมเมนตัม (แรงเหวี่ยง)",
            "moral": "ทางศีลธรรม",
            "more": "มากกว่า",
            "movement": "การเคลื่อนไหว",
            "multiple": "หลากหลาย",
            "must": "ต้อง",
            "neutral": "เป็นกลาง",
            "no": "ไม่",
            "no longer": "ไม่อีกต่อไป",
            "not": "ไม่",
            "observation": "การสังเกต",
            "observer": "ผู้สังเกต",
            "observers": "ผู้สังเกตการณ์",
            "obstacles": "อุปสรรค",
            "occurs": "เกิดขึ้น",
            "of": "ของ",
            "often": "บ่อยครั้ง",
            "on": "บน",
            "one": "หนึ่ง",
            "only": "เพียงแค่",
            "operate": "ทำงาน",
            "or": "หรือ",
            "other": "อื่น",
            "our": "ของเรา",
            "outcome": "ผลลัพธ์",
            "outcomes": "ผลลัพธ์",
            "paradox": "ความย้อนแย้ง",
            "part": "ส่วน",
            "particle": "อนุภาค",
            "particles": "อนุภาค",
            "pass": "ผ่าน",
            "pass through": "ผ่าน",
            "path": "เส้นทาง",
            "paths": "เส้นทาง",
            "peace": "สันติภาพ",
            "peaceful": "สงบสุข",
            "phenomenon": "ปรากฏการณ์",
            "physics": "ฟิสิกส์",
            "planet": "โลก",
            "position": "ตำแหน่ง",
            "posits": "เสนอสมมติฐาน",
            "possibilities": "ความเป็นไปได้",
            "possible": "ที่เป็นไปได้",
            "potential": "ศักยภาพ/ที่เป็นไปได้",
            "predict": "ทำนาย",
            "prejudice": "อคติ",
            "principle": "หลักการ",
            "probability": "ความน่าจะเป็น",
            "problem": "ปัญหา",
            "progress": "ความก้าวหน้า",
            "quantum": "ควอนตัม",
            "quantum humility": "ความอ่อนน้อมแบบควอนตัม (การยอมรับว่าเราไม่รู้ทั้งหมด)",
            "rare": "ที่หายาก",
            "real": "จริง",
            "reality": "ความจริง",
            "realm": "ดินแดน/ขอบเขต",
            "recognize": "ตระหนัก/ยอมรับ",
            "redefine": "นิยามใหม่",
            "regardless": "โดยไม่คำนึงถึง",
            "regardless of": "โดยไม่คำนึงถึง",
            "remain": "ยังคงเป็น",
            "reminds": "ย้ำเตือน",
            "requires": "ต้องการ",
            "responsibilities": "ความรับผิดชอบ",
            "responsibility": "ความรับผิดชอบ",
            "scientific": "ทางวิทยาศาสตร์",
            "scope": "ขอบเขต",
            "search": "การค้นหา",
            "seek": "แสวงหา",
            "seeks": "แสวงหา",
            "seemed": "ดูเหมือน",
            "separate": "ที่แยกกัน",
            "shapes": "ก่อร่าง",
            "should": "ควรจะ",
            "silence": "ความเงียบ",
            "similar": "ที่คล้ายคลึงกัน",
            "similarly": "ในทางที่คล้ายกัน",
            "simultaneously": "พร้อมๆ กัน",
            "single": "เดียว",
            "smallest": "ที่เล็กที่สุด",
            "so": "ดังนั้น",
            "social": "ทางสังคม",
            "sometimes": "ในบางครั้ง",
            "spread": "การแผ่กระจาย",
            "stable": "ที่มั่นคง",
            "state": "สภาวะ/รัฐ",
            "states": "ระบุ/กล่าวว่า",
            "static": "นิ่ง",
            "statistical": "ทางสถิติ",
            "subatomic": "ระดับอนุภาคที่เล็กกว่าอะตอม",
            "suggests": "แนะนำ/ชี้ให้เห็น",
            "superposition": "การซ้อนทับ",
            "system": "ระบบ",
            "term": "คำศัพท์/ระยะเวลา",
            "that": "ว่า",
            "the": "(คำนำหน้า)",
            "then": "จากนั้น/ดังนั้น",
            "theory": "ทฤษฎี",
            "therefore": "ดังนั้น",
            "these": "เหล่านี",
            "this": "สิ่งนี้",
            "thought": "ความคิด",
            "thought experiment": "การทดลองทางความคิด",
            "through": "ผ่าน",
            "to": "ไปยัง",
            "toward": "มุ่งสู่",
            "tradition": "ประเพณี",
            "true": "จริง",
            "tunnel": "อุโมงค์",
            "tunneling": "การเจาะผ่าน/อุโมงค์ควอนตัม",
            "two": "สอง",
            "ultimate": "สูงสุด",
            "uncertainty": "ความไม่แน่นอน",
            "uncertainty principle": "หลักความไม่แน่นอน",
            "unified": "ที่เป็นหนึ่งเดียว",
            "unified theory": "ทฤษฎีเอกภาพ",
            "unify": "รวมเป็นหนึ่ง",
            "universe": "จักรวาล",
            "us": "พวกเรา",
            "value": "คุณค่า",
            "values": "ค่านิยม",
            "vast": "มหาศาล",
            "version": "รุ่น/ฉบับ",
            "wave": "คลื่น",
            "wave function": "ฟังก์ชันคลื่น (ศัพท์ควอนตัม)",
            "way": "ทาง/วิธี",
            "we": "พวกเรา",
            "web": "เครือข่าย/ใย",
            "weight": "น้ำหนัก",
            "well": "ดี",
            "well-being": "สวัสดิภาพ/ความสุข",
            "were": "เป็น/อยู่/คือ (อดีต)",
            "what": "อะไร",
            "where": "ที่ซึ่ง",
            "while": "ขณะที่",
            "with": "ด้วย",
            "within": "ภายใน",
            "witnessing": "การร่วมเห็นเหตุการณ์",
            "world": "โลก",
            "worlds": "โลกต่างๆ"
        }
    }
];
window.CURRENT_LEVEL_DATA = C1_STORIES;
