const A2_STORIES = [
    {
        "id": "brave_knight",
        "title": "The Brave Knight",
        "level": "A2",
        "cover": "images/a2/knight/cover.jpg",
        "description": "Sir Leo was a brave knight who met a dragon.",
        "vocabulary": [
            {
                "word": "Knight",
                "translation": "อัศวิน"
            },
            {
                "word": "Brave",
                "translation": "กล้าหาญ"
            },
            {
                "word": "Castle",
                "translation": "ปราสาท"
            },
            {
                "word": "Strange",
                "translation": "แปลก"
            },
            {
                "word": "Dragon",
                "translation": "มังกร"
            }
        ],
        "chapters": [
            {
                "title": "The Knight",
                "content": "Sir Leo lived in a very old castle. The castle was made of large stones. He was a brave knight. He had a shining sword.",
                "image": "images/a2/knight/ch1.jpg",
                "color": "#f1f5f9",
                "visual_type": "knight_castle"
            },
            {
                "title": "Strange Sound",
                "content": "Last night, he heard a strange sound from the dark forest. It was loud and heavy. He held his sword and went into the forest.",
                "image": "images/a2/knight/ch2.jpg",
                "color": "#1e293b",
                "visual_type": "knight_forest"
            },
            {
                "title": "The Cave",
                "content": "Deep in the forest, Sir Leo found a large cave. Inside, there was a big dragon. It looked sad, not angry. It had a thorn in its wing.",
                "image": "images/a2/knight/ch3.jpg",
                "color": "#450a0a",
                "visual_type": "knight_dragon"
            },
            {
                "title": "Helping",
                "content": "Sir Leo put his sword down. He walked slowly. \"I want to help you,\" he said. He pulled the thorn out. The dragon felt better.",
                "image": "images/a2/knight/ch4.jpg",
                "color": "#fefce8",
                "visual_type": "knight_help"
            },
            {
                "title": "Friends",
                "content": "The dragon and the knight became friends. Now, the village was even safer. Sir Leo was a brave knight with a magic friend.",
                "image": "images/a2/knight/ch5.jpg",
                "color": "#eff6ff",
                "visual_type": "knight_friends"
            }
        ],
        "full_dictionary": {
            "sir": "ท่าน",
            "leo": "ลีโอ",
            "lived": "อาศัยอยู่",
            "old": "เก่า",
            "castle": "ปราสาท",
            "made": "ทำจาก",
            "large": "ใหญ่",
            "stones": "หิน",
            "brave": "กล้าหาญ",
            "knight": "อัศวิน",
            "had": "มี",
            "shining": "สว่าง",
            "sword": "ดาบ",
            "last": "ที่แล้ว",
            "night": "คืน",
            "heard": "ได้ยิน",
            "strange": "แปลก",
            "sound": "เสียง",
            "forest": "ป่า",
            "loud": "ดัง",
            "heavy": "หนัก",
            "held": "ถือ",
            "went": "ไป",
            "deep": "ลึก",
            "found": "พบ",
            "cave": "ถ้ำ",
            "dragon": "มังกร",
            "looked": "ดูเหมือน",
            "sad": "เศร้า",
            "angry": "โกรธ",
            "thorn": "หนาม",
            "wing": "ปีก",
            "put": "วาง",
            "down": "ลง",
            "slowly": "อย่างช้าๆ",
            "said": "พูด",
            "pulled": "ดึง",
            "out": "ออก",
            "better": "ดีขึ้น",
            "became": "กลายเป็น",
            "friends": "เพื่อน",
            "safer": "ปลอดภัยกว่า",
            "magic": "เวทมนตร์",
            "the": "คำนำหน้า",
            "very": "มาก",
            "was": "เป็น",
            "he": "เขา",
            "a": "หนึ่ง",
            "from": "จาก",
            "dark": "มืด",
            "it": "มัน",
            "and": "และ",
            "his": "ของเขา",
            "into": "เข้าไป",
            "there": "มี",
            "its": "ของมัน",
            "could": "สามารถ",
            "fly": "บิน",
            "up": "ขึ้น",
            "i": "ฉัน",
            "want": "ต้องการ",
            "help": "ช่วย",
            "you": "คุณ",
            "felt": "รู้สึก",
            "wings": "ปีก",
            "at": "ที่",
            "with": "กับ",
            "eyes": "ตา",
            "flew": "บิน",
            "over": "เหนือ",
            "now": "ตอนนี้",
            "village": "หมู่บ้าน",
            "even": "แม้แต่",
            "still": "ยังคง",
            "big": "ใหญ่",
            "friend": "เพื่อน",
            "helping": "กำลังช่วย",
            "in": "ใน",
            "inside": "ข้างใน",
            "not": "ไม่",
            "of": "ของ",
            "to": "ถึง/เพื่อ",
            "walked": "เดิน (อดีต)"
        }
    },
    {
        "id": "yesterday_london",
        "title": "Yesterday in London",
        "level": "A2",
        "cover": "images/a2/london/cover.jpg",
        "description": "Mark's trip to the famous city of London.",
        "vocabulary": [
            {
                "word": "Visit",
                "translation": "เยี่ยมชม"
            },
            {
                "word": "Famous",
                "translation": "มีชื่อเสียง"
            },
            {
                "word": "Museum",
                "translation": "พิพิธภัณฑ์"
            },
            {
                "word": "Bridge",
                "translation": "สะพาน"
            },
            {
                "word": "Tower",
                "translation": "หอคอย"
            }
        ],
        "chapters": [
            {
                "title": "Arrival",
                "content": "Yesterday, Mark arrived in London by train. The station was very busy. He carried a small map. He wanted to see the famous city.",
                "image": "images/a2/london/ch1.jpg",
                "color": "#f1f5f9",
                "visual_type": "london_station"
            },
            {
                "title": "Red Bus",
                "content": "He bought a ticket for a red bus. The bus was tall. Mark sat at the top. He saw many old buildings.",
                "image": "images/a2/london/ch2.jpg",
                "color": "#e0f2fe",
                "visual_type": "london_bus"
            },
            {
                "title": "Big Ben",
                "content": "The bus stopped near Big Ben. It was a very high tower. Then, Mark walked across the Tower Bridge. The river was wide.",
                "image": "images/a2/london/ch3.jpg",
                "color": "#f8fafc",
                "visual_type": "london_bigben"
            },
            {
                "title": "The Museum",
                "content": "Mark visited a museum. He saw many old things. He stayed there for three hours. He was very tired but interested.",
                "image": "images/a2/london/ch4.jpg",
                "color": "#fefce8",
                "visual_type": "london_museum"
            },
            {
                "title": "Fish and Chips",
                "content": "For dinner, he ate fish and chips. It was a traditional meal. London was a great city. Mark wants to visit again next year.",
                "image": "images/a2/london/ch5.jpg",
                "color": "#fff7ed",
                "visual_type": "london_food"
            }
        ],
        "full_dictionary": {
            "yesterday": "เมื่อวานนี้",
            "arrived": "ถึง",
            "station": "สถานี",
            "busy": "ยุ่ง/คึกคัก",
            "carried": "ถือ/แบก",
            "map": "แผนที่",
            "wanted": "ต้องการ",
            "see": "เห็น",
            "famous": "มีชื่อเสียง",
            "city": "เมือง",
            "bought": "ซื้อ",
            "ticket": "ตั๋ว",
            "tall": "สูง",
            "sat": "นั่ง",
            "top": "ด้านบน",
            "buildings": "อาคาร",
            "stopped": "หยุด",
            "near": "ใกล้",
            "high": "สูง",
            "tower": "หอคอย",
            "walked": "เดิน",
            "across": "ข้าม",
            "bridge": "สะพาน",
            "river": "แม่น้ำ",
            "wide": "กว้าง",
            "visited": "เยี่ยมชม",
            "museum": "พิพิธภัณฑ์",
            "things": "สิ่งของ",
            "stayed": "พัก/อยู่",
            "three hours": "สามชั่วโมง",
            "tired": "เหนื่อย",
            "interested": "สนใจ",
            "ate": "กิน",
            "traditional": "ดั้งเดิม",
            "meal": "มื้ออาหาร",
            "great": "ยอดเยี่ยม",
            "next year": "ปีหน้า",
            "mark": "มาร์ค",
            "london": "ลอนดอน",
            "by": "โดย",
            "train": "รถไฟ",
            "the": "คำนำหน้า",
            "was": "เป็น/คือ",
            "very": "มาก",
            "he": "เขา",
            "a": "หนึ่ง",
            "small": "เล็ก",
            "for": "สำหรับ",
            "red": "สีแดง",
            "bus": "รถบัส",
            "many": "มาก",
            "old": "เก่า",
            "then": "จากนั้น",
            "and": "และ",
            "there": "ที่นั่น",
            "again": "อีกครั้ง",
            "arrival": "การมาถึง",
            "at": "ที่",
            "ben": "เบน",
            "big": "ใหญ่",
            "but": "แต่",
            "chips": "มันฝรั่งทอด",
            "dinner": "อาหารเย็น",
            "fish": "ปลา",
            "hours": "ชั่วโมง",
            "in": "ใน",
            "it": "มัน",
            "next": "ถัดไป",
            "saw": "เห็น (อดีต)",
            "three": "สาม",
            "to": "ถึง/เพื่อ",
            "visit": "เยี่ยมชม",
            "wants": "ต้องการ",
            "year": "ปี"
        }
    },
    {
        "id": "dinosaur_egg",
        "title": "The Dinosaur Egg",
        "level": "A2",
        "cover": "images/a2/dino/cover.jpg",
        "description": "Sam found a rock that turned out to be an egg.",
        "vocabulary": [
            {
                "word": "Dinosaur",
                "translation": "ไดโนเสาร์"
            },
            {
                "word": "Egg",
                "translation": "ไข่"
            },
            {
                "word": "Rock",
                "translation": "หิน"
            },
            {
                "word": "Heavy",
                "translation": "หนัก"
            },
            {
                "word": "Hatch",
                "translation": "ฟัก"
            }
        ],
        "chapters": [
            {
                "title": "The Discovery",
                "content": "Sam was walking on the beach. He found a very large, round rock. It was very heavy. He took it home in his wagon.",
                "image": "images/a2/dino/ch1.jpg",
                "color": "#fefce8",
                "visual_type": "dino_discovery"
            },
            {
                "title": "Cleaning",
                "content": "Sam cleaned the rock with water. He saw strange patterns on it. \"This is not a normal rock,\" Sam said. He put it near a lamp.",
                "image": "images/a2/dino/ch2.jpg",
                "color": "#f8fafc",
                "visual_type": "dino_cleaning"
            },
            {
                "title": "The Crack",
                "content": "The next morning, Sam heard a small sound. 'Crack!' The rock was breaking. He saw a tiny green tail. It was a dinosaur egg!",
                "image": "images/a2/dino/ch3.jpg",
                "color": "#f0fdf4",
                "visual_type": "dino_crack"
            },
            {
                "title": "Baby Dino",
                "content": "A baby dinosaur came out of the egg. It was small and green. It was very hungry. Sam gave it some fruit and leaves.",
                "image": "images/a2/dino/ch4.jpg",
                "color": "#ecfdf5",
                "visual_type": "dino_baby"
            },
            {
                "title": "The Park",
                "content": "The dinosaur grew very fast. Sam took it to a special park for dinosaurs. Now, many children visit the park to see the baby dino.",
                "image": "images/a2/dino/ch5.jpg",
                "color": "#eff6ff",
                "visual_type": "dino_park"
            }
        ],
        "full_dictionary": {
            "sam": "แซม",
            "walking": "กำลังเดิน",
            "beach": "ชายหาด",
            "found": "พบ/เจอ",
            "large": "ใหญ่",
            "round": "กลม",
            "rock": "หิน",
            "heavy": "หนัก",
            "took": "หยิบ/นำไป",
            "home": "บ้าน",
            "wagon": "รถลาก",
            "cleaned": "ทำความสะอาด",
            "with": "ด้วย",
            "water": "น้ำ",
            "strange": "แปลก",
            "patterns": "รูปแบบ",
            "normal": "ปกติ",
            "said": "พูด",
            "lamp": "ตะกิ่ง/โคมไฟ",
            "next morning": "เช้าวันถัดไป",
            "heard": "ได้ยิน",
            "sound": "เสียง",
            "crack": "เสียงแตก",
            "breaking": "กำลังแตก",
            "tiny": "เล็กจิ๋ว",
            "tail": "หาง",
            "dinosaur": "ไดโนเสาร์",
            "egg": "ไข่",
            "baby": "ทารก",
            "hungry": "หิว",
            "gave": "ให้",
            "fruit": "ผลไม้",
            "leaves": "ใบไม้",
            "grew": "เติบโต",
            "fast": "เร็ว",
            "special": "พิเศษ",
            "park": "สวน",
            "visit": "เยี่ยมชม",
            "children": "เด็กๆ",
            "on": "บน",
            "it": "มัน",
            "he": "เขา",
            "his": "ของเขา",
            "near": "ใกล้",
            "some": "บ้าง",
            "a": "หนึ่ง",
            "and": "และ",
            "came": "มา (อดีต)",
            "cleaning": "การทำความสะอาด",
            "dino": "ไดโน",
            "dinosaurs": "ไดโนเสาร์",
            "discovery": "การค้นพบ",
            "for": "สำหรับ",
            "green": "สีเขียว",
            "in": "ใน",
            "is": "เป็น/อยู่/คือ",
            "many": "มากมาย",
            "morning": "ตอนเช้า",
            "next": "ถัดไป",
            "not": "ไม่",
            "now": "ตอนนี้",
            "of": "ของ",
            "out": "ออก",
            "put": "วาง",
            "saw": "เห็น (อดีต)",
            "see": "เห็น",
            "small": "เล็ก",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "this": "นี่",
            "to": "ถึง/เพื่อ",
            "very": "มาก",
            "was": "เป็น/อยู่/คือ (อดีต)"
        }
    },
    {
        "id": "hospital_day",
        "title": "Day at the Hospital",
        "level": "A2",
        "cover": "images/a2/hospital/cover.jpg",
        "description": "Sarah is a nurse who helps many people every day.",
        "vocabulary": [
            {
                "word": "Nurse",
                "translation": "พยาบาล"
            },
            {
                "word": "Hospital",
                "translation": "โรงพยาบาล"
            },
            {
                "word": "Patient",
                "translation": "คนไข้"
            },
            {
                "word": "Medicine",
                "translation": "ยา"
            },
            {
                "word": "Healthy",
                "translation": "สุขภาพดี"
            }
        ],
        "chapters": [
            {
                "title": "The Morning Shift",
                "content": "Sarah is a nurse. She works at a large hospital in the city. She starts her shift at 7 a.m. She wears a white uniform.",
                "image": "images/a2/hospital/ch1.jpg",
                "color": "#eff6ff",
                "visual_type": "nurse_start"
            },
            {
                "title": "Helping Patients",
                "content": "Sarah visits many patients. She gives them medicine and food. She talks to them kindly. She wants everyone to feel better.",
                "image": "images/a2/hospital/ch2.jpg",
                "color": "#f1f5f9",
                "visual_type": "nurse_helping"
            },
            {
                "title": "Emergency",
                "content": "Suddenly, there was an emergency. A man had a broken leg. Sarah and the doctors worked fast. They helped the man quickly.",
                "image": "images/a2/hospital/ch3.jpg",
                "color": "#fee2e2",
                "visual_type": "hospital_emergency"
            },
            {
                "title": "Lunch Break",
                "content": "Sarah has a small break at 1 p.m. She eats lunch with other nurses. They talk about their families. Sarah loves her job.",
                "image": "images/a2/hospital/ch4.jpg",
                "color": "#f8fafc",
                "visual_type": "nurse_lunch"
            },
            {
                "title": "Going Home",
                "content": "Sarah goes home at 5 p.m. She is tired, but she is happy. Helping people is important. She wants everyone to be healthy.",
                "image": "images/a2/hospital/ch5.jpg",
                "color": "#f0fdf4",
                "visual_type": "nurse_home"
            }
        ],
        "full_dictionary": {
            "nurse": "พยาบาล",
            "hospital": "โรงพยาบาล",
            "patients": "คนไข้",
            "medicine": "ยา",
            "shift": "กะการทำงาน",
            "uniform": "เครื่องแบบ",
            "kindly": "อย่างใจดี",
            "everyone": "ทุกคน",
            "feel": "รู้สึก",
            "emergency": "ฉุกเฉิน",
            "broken leg": "ขาหัก",
            "doctors": "หมอ",
            "quickly": "อย่างรวดเร็ว",
            "break": "การพัก",
            "important": "สำคัญ",
            "healthy": "สุขภาพดี",
            "sarah": "ซาร่า",
            "works": "ทำงาน",
            "at": "ที่",
            "starts": "เริ่ม",
            "wears": "สวมใส่",
            "visits": "เยี่ยมชม",
            "gives": "ให้",
            "talks": "พูดคุย",
            "wants": "ต้องการ",
            "better": "ดีขึ้น",
            "suddenly": "ทันใดนั้น",
            "worked": "ทำงาน (อดีต)",
            "helped": "ช่วยเหลือ (อดีต)",
            "eats": "กิน",
            "lunch": "อาหารกลางวัน",
            "other": "อื่นๆ",
            "job": "งาน",
            "goes": "ไป",
            "tired": "เหนื่อย",
            "happy": "มีความสุข",
            "a": "หนึ่ง",
            "about": "เกี่ยวกับ",
            "an": "หนึ่ง",
            "and": "และ",
            "be": "เป็น/อยู่/คือ",
            "broken": "หัก/พัง",
            "but": "แต่",
            "city": "เมือง",
            "day": "วัน",
            "families": "ครอบครัวหลายครอบครัว",
            "fast": "เร็ว",
            "food": "อาหาร",
            "going": "กำลังไป",
            "had": "มี (อดีต)",
            "has": "มี",
            "helping": "กำลังช่วย",
            "her": "ของเธอ",
            "home": "บ้าน",
            "in": "ใน",
            "is": "เป็น/อยู่/คือ",
            "large": "ใหญ่",
            "leg": "ขา",
            "loves": "รัก",
            "m": "เช้า",
            "man": "ผู้ชาย",
            "many": "มากมาย",
            "morning": "ตอนเช้า",
            "nurses": "พยาบาลหลายคน",
            "p": "บ่าย",
            "people": "ผู้คน",
            "she": "เธอ",
            "small": "เล็ก",
            "talk": "พูดคุย",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "their": "ของพวกเขา",
            "them": "พวกเรา (กรรม)",
            "there": "มี/ที่นั่น",
            "they": "พวกเรา/พวกเขา",
            "to": "ถึง/เพื่อ",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "white": "สีขาว",
            "with": "กับ"
        }
    },
    {
        "id": "chef_challenge",
        "title": "The Chef's Challenge",
        "level": "A2",
        "cover": "images/a2/chef/cover.jpg",
        "description": "Marco entered a big cooking competition to win a prize.",
        "vocabulary": [
            {
                "word": "Chef",
                "translation": "เชฟ/พ่อครัว"
            },
            {
                "word": "Competition",
                "translation": "การแข่งขัน"
            },
            {
                "word": "Ingredient",
                "translation": "วัตถุดิบ"
            },
            {
                "word": "Kitchen",
                "translation": "ห้องครัว"
            },
            {
                "word": "Prize",
                "translation": "รางวัล"
            }
        ],
        "chapters": [
            {
                "title": "The Plan",
                "content": "Marco is a chef. He loves cooking Italian food. He wanted to enter a big competition. He practiced every day for a month.",
                "image": "images/a2/chef/ch1.jpg",
                "color": "#fffbeb",
                "visual_type": "chef_plan"
            },
            {
                "title": "Ingredients",
                "content": "He went to the market. He bought fresh tomatoes, pasta, and cheese. \"Quality is important,\" Marco said. He was very careful.",
                "image": "images/a2/chef/ch2.jpg",
                "color": "#f8fafc",
                "visual_type": "chef_ingredients"
            },
            {
                "title": "The Kitchen",
                "content": "The competition was in a very large kitchen. Many other chefs were there. Marco felt a bit nervous, but he started to cook.",
                "image": "images/a2/chef/ch3.jpg",
                "color": "#f1f5f9",
                "visual_type": "chef_kitchen"
            },
            {
                "title": "Cooking",
                "content": "He made a special pasta dish. The smell was wonderful. The judges tasted his food. They smiled at Marco. He felt proud.",
                "image": "images/a2/chef/ch4.jpg",
                "color": "#fff1f2",
                "visual_type": "chef_cooking"
            },
            {
                "title": "The Winner",
                "content": "Finally, the judges announced the winner. \"The prize goes to Marco!\" everyone cheered. Marco was the best chef of the day.",
                "image": "images/a2/chef/ch5.jpg",
                "color": "#fefce8",
                "visual_type": "chef_winner"
            }
        ],
        "full_dictionary": {
            "chef": "เชฟ/พ่อครัว",
            "cooking": "การทำอาหาร",
            "food": "อาหาร",
            "competition": "การแข่งขัน",
            "practiced": "ฝึกซ้อม",
            "month": "เดือน",
            "market": "ตลาด",
            "fresh": "สดใหม่",
            "tomatoes": "มะเขือเทศ",
            "pasta": "พาสต้า",
            "cheese": "ชีส",
            "quality": "คุณภาพ",
            "careful": "ระมัดระวัง",
            "nervous": "ประหม่า/ตื่นเต้น",
            "special": "พิเศษ",
            "wonderful": "มหัศจรรย์",
            "judges": "กรรมการ",
            "tasted": "ชิม",
            "proud": "ภูมิใจ",
            "announced": "ประกาศ",
            "winner": "ผู้ชนะ",
            "cheered": "โห่ร้องยินดี",
            "prize": "รางวัล",
            "marco": "มาร์โก้",
            "italian": "อิตาลี",
            "enter": "เข้าร่วม",
            "for": "สำหรับ",
            "bought": "ซื้อ",
            "important": "สำคัญ",
            "kitchen": "ห้องครัว",
            "felt": "รู้สึก",
            "made": "ทำ",
            "dish": "เมนูอาหาร/จาน",
            "smiled": "ยิ้ม",
            "best": "ดีที่สุด",
            "a": "หนึ่ง",
            "and": "และ",
            "at": "ที่",
            "big": "ใหญ่",
            "bit": "เล็กน้อย",
            "but": "แต่",
            "challenge": "ความท้าทาย",
            "chef's": "ของเชฟ",
            "chefs": "เชฟหลายคน",
            "cook": "ทำอาหาร",
            "day": "วัน",
            "every": "ทุกๆ",
            "everyone": "ทุกคน",
            "finally": "ในที่สุด",
            "goes": "ไป",
            "he": "เขา",
            "his": "ของเขา",
            "in": "ใน",
            "ingredients": "วัตถุดิบ",
            "is": "เป็น/อยู่/คือ",
            "large": "ใหญ่",
            "loves": "รัก",
            "many": "มากมาย",
            "of": "ของ",
            "other": "อื่นๆ",
            "plan": "แผนการ",
            "said": "พูด (อดีต)",
            "smell": "กลิ่น",
            "started": "เริ่ม (อดีต)",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "there": "มี/ที่นั่น",
            "they": "พวกเรา/พวกเขา",
            "to": "ถึง/เพื่อ",
            "very": "มาก",
            "wanted": "ต้องการ (อดีต)",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "went": "ไป (อดีต)",
            "were": "เป็น/อยู่/คือ (อดีต)"
        }
    },
    {
        "id": "space_journey",
        "title": "Journey to Mars",
        "level": "A2",
        "cover": "images/a2/space/cover.jpg",
        "description": "Five astronauts traveled to the Red Planet.",
        "vocabulary": [
            {
                "word": "Astronaut",
                "translation": "นักบินอวกาศ"
            },
            {
                "word": "Rocket",
                "translation": "จรวด"
            },
            {
                "word": "Mars",
                "translation": "ดาวอังคาร"
            },
            {
                "word": "Travel",
                "translation": "เดินทาง"
            },
            {
                "word": "Planet",
                "translation": "ดาวเคราะห์"
            }
        ],
        "chapters": [
            {
                "title": "Preparation",
                "content": "Five astronauts were ready for a journey. They trained for many years. Their goal was to visit Mars, the Red Planet.",
                "image": "images/a2/space/ch1.jpg",
                "color": "#f8fafc",
                "visual_type": "space_training"
            },
            {
                "title": "Launch",
                "content": "The rocket was very big. It moved very fast into the dark sky. The astronauts looked at the Earth. It was blue and small.",
                "image": "images/a2/space/ch2.jpg",
                "color": "#1e293b",
                "visual_type": "rocket_launch"
            },
            {
                "title": "The Trip",
                "content": "They spent seven months in space. They ate special food and exercised every day. They were excited to reach their goal.",
                "image": "images/a2/space/ch3.jpg",
                "color": "#334155",
                "visual_type": "space_trip"
            },
            {
                "title": "Landing",
                "content": "Finally, the rocket landed on Mars. The ground was red and dusty. There were many mountains and large rocks.",
                "image": "images/a2/space/ch4.jpg",
                "color": "#450a0a",
                "visual_type": "mars_landing"
            },
            {
                "title": "Discovery",
                "content": "The astronauts explored the planet. They found some ice under the ground. \"Mars is amazing!\" they said. They stayed for a week.",
                "image": "images/a2/space/ch5.jpg",
                "color": "#0f172a",
                "visual_type": "space_discovery"
            }
        ],
        "full_dictionary": {
            "astronauts": "นักบินอวกาศ",
            "journey": "การเดินทาง",
            "trained": "ฝึกฝน",
            "goal": "เป้าหมาย",
            "visit": "เยี่ยมชม",
            "mars": "ดาวอังคาร",
            "rocket": "จรวด",
            "fast": "เร็ว",
            "earth": "โลก",
            "space": "อวกาศ",
            "reach": "ถึง",
            "landed": "ลงจอด",
            "ground": "พื้น",
            "dusty": "เต็มไปด้วยฝุ่น",
            "explored": "สำรวจ",
            "amazing": "น่าทึ่ง",
            "week": "สัปดาห์",
            "five": "ห้า",
            "ready": "พร้อม",
            "years": "ปี",
            "planet": "ดาวเคราะห์",
            "moved": "เคลื่อนที่",
            "dark": "มืด",
            "sky": "ท้องฟ้า",
            "spent": "ใช้เวลา",
            "months": "เดือน",
            "ate": "กิน",
            "exercised": "ออกกำลังกาย",
            "red": "แดง",
            "rocks": "หิน",
            "ice": "น้ำแข็ง",
            "under": "ใต้",
            "a": "หนึ่ง",
            "and": "และ",
            "at": "ที่",
            "big": "ใหญ่",
            "blue": "สีน้ำเงิน",
            "day": "วัน",
            "discovery": "การค้นพบ",
            "every": "ทุกๆ",
            "excited": "ตื่นเต้น",
            "finally": "ในที่สุด",
            "food": "อาหาร",
            "for": "สำหรับ",
            "found": "พบ (อดีต)",
            "in": "ใน",
            "into": "เข้าไปใน",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "landing": "การลงจอด",
            "large": "ใหญ่",
            "launch": "การปล่อย (เช่น จรวด)",
            "looked": "ดูเหมือน/มอง (อดีต)",
            "many": "มากมาย",
            "mountains": "ภูเขาหลายลูก",
            "on": "บน",
            "preparation": "การเตรียมตัว",
            "said": "พูด (อดีต)",
            "seven": "เจ็ด",
            "small": "เล็ก",
            "some": "บ้าง",
            "special": "พิเศษ",
            "stayed": "พัก/อยู่ (อดีต)",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "their": "ของพวกเขา",
            "there": "มี/ที่นั่น",
            "they": "พวกเรา/พวกเขา",
            "to": "ถึง/เพื่อ",
            "trip": "การเดินทาง",
            "very": "มาก",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "were": "เป็น/อยู่/คือ (อดีต)"
        }
    },
    {
        "id": "talking_mountain",
        "title": "The Talking Mountain",
        "level": "A2",
        "cover": "images/a2/mountain/cover.jpg",
        "description": "Toby climbed a mountain that spoke in the wind.",
        "vocabulary": [
            {
                "word": "Mountain",
                "translation": "ภูเขา"
            },
            {
                "word": "Climb",
                "translation": "ปีน"
            },
            {
                "word": "Wind",
                "translation": "ลม"
            },
            {
                "word": "Whisper",
                "translation": "กระซิบ"
            },
            {
                "word": "Top",
                "translation": "จุดสูงสุด"
            }
        ],
        "chapters": [
            {
                "title": "Toby's Goal",
                "content": "Toby loved nature. He wanted to climb the highest mountain in his village. People said it was a magic mountain.",
                "image": "images/a2/mountain/ch1.jpg",
                "color": "#f0fdf4",
                "visual_type": "mountain_intro"
            },
            {
                "title": "The Wind",
                "content": "While Toby was climbing, the wind started to blow. He heard a soft sound. It was like a whisper. \"Keep going,\" the wind said.",
                "image": "images/a2/mountain/ch2.jpg",
                "color": "#eff6ff",
                "visual_type": "mountain_wind"
            },
            {
                "title": "The Cave",
                "content": "It started to rain. Toby found a small cave to stay dry. Inside, he saw old paintings on the wall. They showed the sun and moon.",
                "image": "images/a2/mountain/ch3.jpg",
                "color": "#f1f5f9",
                "visual_type": "mountain_cave"
            },
            {
                "title": "The Top",
                "content": "Finally, Toby reached the top. The view was wonderful. He saw the whole village and the blue river. He felt very strong.",
                "image": "images/a2/mountain/ch4.jpg",
                "color": "#f8fafc",
                "visual_type": "mountain_top"
            },
            {
                "title": "The Secret",
                "content": "The mountain spoke to him again. \"Nature is your friend,\" it whispered. Toby went back down. He was happy with his adventure.",
                "image": "images/a2/mountain/ch5.jpg",
                "color": "#fefce8",
                "visual_type": "mountain_secret"
            }
        ],
        "full_dictionary": {
            "nature": "ธรรมชาติ",
            "highest": "สูงที่สุด",
            "magic": "เวทมนตร์",
            "climbing": "กำลังปีน",
            "whisper": "การกระซิบ",
            "cave": "ถ้ำ",
            "dry": "แห้ง",
            "paintings": "ภาพวาด",
            "reached": "ถึง",
            "view": "วิว/ทิวทัศน์",
            "strong": "แข็งแรง",
            "adventure": "การผจญภัย",
            "toby": "โทบี้",
            "loved": "รัก",
            "wanted": "ต้องการ",
            "climb": "ปีน",
            "mountain": "ภูเขา",
            "people": "ผู้คน",
            "wind": "ลม",
            "heard": "ได้ยิน",
            "soft": "นุ่มนวล/เบา",
            "like": "เหมือน",
            "started": "เริ่ม",
            "rain": "ฝน",
            "saw": "เห็น",
            "wonderful": "มหัศจรรย์",
            "whole": "ทั้งหมด",
            "river": "แม่น้ำ",
            "spoke": "พูด",
            "a": "หนึ่ง",
            "again": "อีกครั้ง",
            "and": "และ",
            "back": "กลับ",
            "blow": "เป่า",
            "blue": "สีน้ำเงิน",
            "down": "ลง",
            "felt": "รู้สึก (อดีต)",
            "finally": "ในที่สุด",
            "found": "พบ (อดีต)",
            "friend": "เพื่อน",
            "goal": "เป้าหมาย",
            "going": "กำลังไป",
            "happy": "มีความสุข",
            "he": "เขา",
            "him": "เขา (กรรม)",
            "his": "ของเขา",
            "in": "ใน",
            "inside": "ข้างใน",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "keep": "เก็บ",
            "moon": "พระจันทร์",
            "old": "เก่า",
            "on": "บน",
            "said": "พูด (อดีต)",
            "secret": "ความลับ",
            "showed": "แสดงให้ดู (อดีต)",
            "small": "เล็ก",
            "sound": "เสียง",
            "stay": "พัก/อยู่",
            "sun": "ดวงอาทิตย์",
            "talking": "กำลังพูดคุย",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "they": "พวกเรา/พวกเขา",
            "to": "ถึง/เพื่อ",
            "toby's": "ของโทบี้",
            "top": "จุดสูงสุด/ด้านบน",
            "very": "มาก",
            "village": "หมู่บ้าน",
            "wall": "กำแพง",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "went": "ไป (อดีต)",
            "while": "ขณะที่",
            "whispered": "กระซิบ (อดีต)",
            "with": "กับ",
            "your": "ของคุณ"
        }
    },
    {
        "id": "farm_day",
        "title": "My Grandfather's Farm",
        "level": "A2",
        "cover": "images/a2/farm/cover.jpg",
        "description": "Tess spent a busy day on the farm with animals.",
        "vocabulary": [
            {
                "word": "Farm",
                "translation": "ฟาร์ม/ไร่นา"
            },
            {
                "word": "Animal",
                "translation": "สัตว์"
            },
            {
                "word": "Sheep",
                "translation": "แกะ"
            },
            {
                "word": "Harvest",
                "translation": "การเก็บเกี่ยว"
            },
            {
                "word": "Garden",
                "translation": "สวน"
            }
        ],
        "chapters": [
            {
                "title": "The Morning",
                "content": "Tess visited her grandfather's farm. It was very big. In the morning, she helped to feed the white sheep and cows.",
                "image": "images/a2/farm/ch1.jpg",
                "color": "#fefce8",
                "visual_type": "farm_morning"
            },
            {
                "title": "Vegetable Garden",
                "content": "They went to the garden. Tess picked some fresh carrots and potatoes. Her grandfather said, \"Our vegetables are the best.\"",
                "image": "images/a2/farm/ch2.jpg",
                "color": "#f0fdf4",
                "visual_type": "farm_garden"
            },
            {
                "title": "The Tractor",
                "content": "Her grandfather has a big red tractor. He showed Tess how it works. They drove it across the large field to harvest corn.",
                "image": "images/a2/farm/ch3.jpg",
                "color": "#fff7ed",
                "visual_type": "farm_tractor"
            },
            {
                "title": "Afternoon",
                "content": "In the afternoon, they sat under an old oak tree. They drank cold milk and ate cookies. The farm was very quiet and peaceful.",
                "image": "images/a2/farm/ch4.jpg",
                "color": "#fffbeb",
                "visual_type": "farm_afternoon"
            },
            {
                "title": "Going Home",
                "content": "Tess took some eggs and fruit home. She said goodbye to the animals. She wants to come back to the farm very soon.",
                "image": "images/a2/farm/ch5.jpg",
                "color": "#fdf4ff",
                "visual_type": "farm_home"
            }
        ],
        "full_dictionary": {
            "visited": "เยี่ยมชม",
            "grandfather's": "ของคุณปู่/คุณตา",
            "feed": "ให้อาหาร",
            "sheep": "แกะ",
            "cows": "วัว",
            "picked": "เก็บ",
            "vegetables": "ผัก",
            "tractor": "รถแทรกเตอร์",
            "works": "ทำงาน",
            "drove": "ขับ",
            "harvest": "เก็บเกี่ยว",
            "corn": "ข้าวโพด",
            "peaceful": "สงบสุข",
            "soon": "ในไม่ช้า",
            "tess": "เทสส์",
            "farm": "ฟาร์ม",
            "morning": "เช้า",
            "some": "บ้าง",
            "afternoon": "บ่าย",
            "sat": "นั่ง",
            "ate": "กิน",
            "eggs": "ไข่",
            "fruit": "ผลไม้",
            "a": "หนึ่ง",
            "across": "ข้าม",
            "an": "หนึ่ง",
            "and": "และ",
            "animals": "สัตว์ต่างๆ",
            "are": "เป็น/อยู่/คือ",
            "back": "กลับ",
            "best": "ดีที่สุด",
            "big": "ใหญ่",
            "carrots": "แครอท",
            "cold": "เย็น",
            "come": "มา",
            "cookies": "คุกกี้",
            "drank": "ดื่ม (อดีต)",
            "field": "ทุ่งนา/สนาม",
            "fresh": "สดใหม่",
            "garden": "สวน",
            "going": "กำลังไป",
            "goodbye": "ลาก่อน",
            "grandfather": "คุณปู่/คุณตา",
            "has": "มี",
            "he": "เขา",
            "helped": "ช่วย (อดีต)",
            "her": "ของเธอ",
            "home": "บ้าน",
            "how": "อย่างไร",
            "in": "ใน",
            "it": "มัน",
            "large": "ใหญ่",
            "milk": "นม",
            "my": "ของฉัน",
            "oak": "โอ๊ค (ต้นไม้)",
            "old": "เก่า",
            "our": "ของเรา",
            "potatoes": "มันฝรั่ง",
            "quiet": "เงียบ",
            "red": "สีแดง",
            "said": "พูด (อดีต)",
            "she": "เธอ",
            "showed": "แสดงให้ดู (อดีต)",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "they": "พวกเรา/พวกเขา",
            "to": "ถึง/เพื่อ",
            "took": "หยิบ/เอาไป (อดีต)",
            "tree": "ต้นไม้",
            "under": "ใต้",
            "vegetable": "ผัก",
            "very": "มาก",
            "wants": "ต้องการ",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "went": "ไป (อดีต)",
            "white": "สีขาว"
        }
    },
    {
        "id": "underwater_city",
        "title": "The Underwater City",
        "level": "A2",
        "cover": "images/a2/ocean/cover.jpg",
        "description": "Diver Dan discovered a city deep under the sea.",
        "vocabulary": [
            {
                "word": "Diver",
                "translation": "นักดำน้ำ"
            },
            {
                "word": "Ocean",
                "translation": "มหาสมุทร"
            },
            {
                "word": "Discover",
                "translation": "ค้นพบ"
            },
            {
                "word": "Ruins",
                "translation": "ซากปรักหักพัง"
            },
            {
                "word": "Fish",
                "translation": "ปลา"
            }
        ],
        "chapters": [
            {
                "title": "The Dive",
                "content": "Dan is a famous diver. He loves the blue ocean. One day, he dived very deep. He saw many colorful fish and coral.",
                "image": "images/a2/ocean/ch1.jpg",
                "color": "#e0f2fe",
                "visual_type": "ocean_dive"
            },
            {
                "title": "The Ruins",
                "content": "Suddenly, Dan saw something strange. There were large stone buildings under the water. It was an old city from the past.",
                "image": "images/a2/ocean/ch2.jpg",
                "color": "#1e293b",
                "visual_type": "ocean_ruins"
            },
            {
                "title": "Inside a House",
                "content": "Dan swam inside a large house. He found a gold cup and old plates. He was very surprised. \"Who lived here?\" he thought.",
                "image": "images/a2/ocean/ch3.jpg",
                "color": "#0f172a",
                "visual_type": "ocean_house"
            },
            {
                "title": "The Giant Turtle",
                "content": "A giant turtle swam near Dan. It looked very old. The turtle showed him the way to a large palace. The palace was beautiful.",
                "image": "images/a2/ocean/ch4.jpg",
                "color": "#334155",
                "visual_type": "ocean_turtle"
            },
            {
                "title": "The Secret",
                "content": "Dan took a photo of the city. He went back to his boat. He told everyone about the underwater city. It was a big secret.",
                "image": "images/a2/ocean/ch5.jpg",
                "color": "#bae6fd",
                "visual_type": "ocean_secret"
            }
        ],
        "full_dictionary": {
            "diver": "นักดำน้ำ",
            "dived": "ดำน้ำ (อดีต)",
            "colorful": "มีสีสัน",
            "coral": "ปะการัง",
            "ruins": "ซากปรักหักพัง",
            "swam": "ว่ายน้ำ (อดีต)",
            "surprised": "ประหลาดใจ",
            "giant": "ยักษ์/ใหญ่โต",
            "turtle": "เต่า",
            "palace": "พระราชวัง",
            "photo": "รูปภาพ",
            "dan": "แดน",
            "famous": "มีชื่อเสียง",
            "ocean": "มหาสมุทร",
            "one day": "วันหนึ่ง",
            "deep": "ลึก",
            "stone": "หิน",
            "gold cup": "ถ้วยทอง",
            "plates": "จาน",
            "lived": "อาศัยอยู่",
            "thought": "คิด",
            "way": "ทาง",
            "boat": "เรือ",
            "told": "บอก",
            "everyone": "ทุกคน",
            "secret": "ความลับ",
            "a": "หนึ่ง",
            "about": "เกี่ยวกับ",
            "an": "หนึ่ง",
            "and": "และ",
            "back": "กลับ",
            "beautiful": "สวยงาม",
            "big": "ใหญ่",
            "blue": "สีน้ำเงิน",
            "buildings": "ตึก/อาคาร",
            "city": "เมือง",
            "cup": "ถ้วย",
            "day": "วัน",
            "dive": "ดำน้ำ",
            "fish": "ปลา",
            "found": "พบ (อดีต)",
            "from": "จาก",
            "gold": "ทอง",
            "he": "เขา",
            "here": "ที่นี่",
            "him": "เขา (กรรม)",
            "his": "ของเขา",
            "house": "บ้าน",
            "inside": "ข้างใน",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "large": "ใหญ่",
            "looked": "ดูเหมือน/มอง (อดีต)",
            "loves": "รัก",
            "many": "มากมาย",
            "near": "ใกล้",
            "of": "ของ",
            "old": "เก่า",
            "one": "หนึ่ง",
            "past": "อดีต",
            "saw": "เห็น (อดีต)",
            "showed": "แสดงให้ดู (อดีต)",
            "something": "บางอย่าง",
            "strange": "แปลก",
            "suddenly": "ทันใดนั้น",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "there": "มี/ที่นั่น",
            "to": "ถึง/เพื่อ",
            "took": "หยิบ/เอาไป (อดีต)",
            "under": "ใต้",
            "underwater": "ใต้น้ำ",
            "very": "มาก",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "water": "น้ำ",
            "went": "ไป (อดีต)",
            "were": "เป็น/อยู่/คือ (อดีต)",
            "who": "ใคร"
        }
    },
    {
        "id": "silver_flute",
        "title": "The Silver Flute",
        "level": "A2",
        "cover": "images/a2/mystery/cover.jpg",
        "description": "Detective Daisy searched for a missing instrument.",
        "vocabulary": [
            {
                "word": "Detective",
                "translation": "นักสืบ"
            },
            {
                "word": "Mystery",
                "translation": "ความลับ/ปริศนา"
            },
            {
                "word": "Flute",
                "translation": "ขลุ่ย"
            },
            {
                "word": "Search",
                "translation": "ค้นหา"
            },
            {
                "word": "Museum",
                "translation": "พิพิธภัณฑ์"
            }
        ],
        "chapters": [
            {
                "title": "The Theft",
                "content": "The silver flute was missing. It was a very expensive instrument. Detective Daisy went to the music school to look for it.",
                "image": "images/a2/mystery/ch1.jpg",
                "color": "#f1f5f9",
                "visual_type": "mystery_theft"
            },
            {
                "title": "The Clue",
                "content": "Daisy found a small blue feather near the window. She also saw a muddy footprint on the floor. \"This is interesting,\" she said.",
                "image": "images/a2/mystery/ch2.jpg",
                "color": "#cbd5e1",
                "visual_type": "mystery_clue"
            },
            {
                "title": "Questioning",
                "content": "She talked to the teacher and the students. One student was very nervous. His name was Leo. He liked to play the flute.",
                "image": "images/a2/mystery/ch3.jpg",
                "color": "#f8fafc",
                "visual_type": "mystery_question"
            },
            {
                "title": "The Discovery",
                "content": "Daisy followed the muddy footprints to a large locker. Inside the locker, she found the silver flute. It was under a blue coat.",
                "image": "images/a2/mystery/ch4.jpg",
                "color": "#e2e8f0",
                "visual_type": "mystery_find"
            },
            {
                "title": "The Truth",
                "content": "Leo said he wanted to practice more. He did not want to steal it. Daisy helped him. Now Leo is a great flute player.",
                "image": "images/a2/mystery/ch5.jpg",
                "color": "#eff6ff",
                "visual_type": "mystery_truth"
            }
        ],
        "full_dictionary": {
            "detective": "นักสืบ",
            "flute": "ขลุ่ย",
            "missing": "หายไป",
            "expensive": "แพง",
            "instrument": "เครื่องดนตรี",
            "theft": "การขโมย",
            "clue": "เบาะแส",
            "feather": "ขนนก",
            "muddy": "เปื้อนโคลน",
            "footprint": "รอยเท้า",
            "nervous": "ตื่นเต้น/ประหม่า",
            "locker": "ล็อกเกอร์",
            "truth": "ความจริง",
            "steal": "ขโมย",
            "practice": "ฝึกซ้อม",
            "daisy": "เดซี่",
            "silver": "เงิน",
            "went": "ไป",
            "school": "โรงเรียน",
            "window": "หน้าต่าง",
            "floor": "พื้น",
            "teacher": "ครู",
            "students": "นักเรียน",
            "followed": "ตาม",
            "inside": "ข้างใน",
            "a": "หนึ่ง",
            "also": "อีกด้วย",
            "and": "และ",
            "blue": "สีน้ำเงิน",
            "coat": "เสื้อโค้ท",
            "did": "ทำ (อดีต)",
            "discovery": "การค้นพบ",
            "footprints": "รอยเท้า",
            "for": "สำหรับ",
            "found": "พบ (อดีต)",
            "great": "ยอดเยี่ยม",
            "he": "เขา",
            "helped": "ช่วย (อดีต)",
            "him": "เขา (กรรม)",
            "his": "ของเขา",
            "interesting": "น่าสนใจ",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "large": "ใหญ่",
            "leo": "ลีโอ",
            "liked": "ชอบ (อดีต)",
            "look": "ดู",
            "more": "มากขึ้น",
            "music": "ดนตรี",
            "name": "ชื่อ",
            "near": "ใกล้",
            "not": "ไม่",
            "now": "ตอนนี้",
            "on": "บน",
            "one": "หนึ่ง",
            "play": "เล่น",
            "player": "ผู้เล่น",
            "questioning": "การตั้งคำถาม/การสอบถาม",
            "said": "พูด (อดีต)",
            "saw": "เห็น (อดีต)",
            "she": "เธอ",
            "small": "เล็ก",
            "student": "นักเรียน",
            "talked": "พูดคุย (อดีต)",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "this": "นี่",
            "to": "ถึง/เพื่อ",
            "under": "ใต้",
            "very": "มาก",
            "want": "ต้องการ",
            "wanted": "ต้องการ (อดีต)",
            "was": "เป็น/อยู่/คือ (อดีต)"
        }
    },
    {
        "id": "time_machine",
        "title": "The Time Machine",
        "level": "A2",
        "cover": "images/a2/time/cover.jpg",
        "description": "Two friends traveled to the past and the future.",
        "vocabulary": [
            {
                "word": "Future",
                "translation": "อนาคต"
            },
            {
                "word": "Past",
                "translation": "อดีต"
            },
            {
                "word": "Invention",
                "translation": "สิ่งประดิษฐ์"
            },
            {
                "word": "History",
                "translation": "ประวัติศาสตร์"
            },
            {
                "word": "Travel",
                "translation": "เดินทาง"
            }
        ],
        "chapters": [
            {
                "title": "The Lab",
                "content": "Professor Piff was an inventor. He built a large time machine in his lab. His friend, Ben, wanted to see it work.",
                "image": "images/a2/time/ch1.jpg",
                "color": "#f8fafc",
                "visual_type": "time_lab"
            },
            {
                "title": "The Past",
                "content": "They pressed a red button. Suddenly, they were in the past. They saw knights on horses and large castles. It was amazing.",
                "image": "images/a2/time/ch2.jpg",
                "color": "#f1f5f9",
                "visual_type": "time_past"
            },
            {
                "title": "The Future",
                "content": "Next, they went to the future. They saw flying cars and tall, silver buildings. People had robots to help them at home.",
                "image": "images/a2/time/ch3.jpg",
                "color": "#eff6ff",
                "visual_type": "time_future"
            },
            {
                "title": "The Problem",
                "content": "Suddenly, the machine stopped working. \"We need a battery!\" Professor Piff said. They looked for a way to go home.",
                "image": "images/a2/time/ch4.jpg",
                "color": "#fee2e2",
                "visual_type": "time_problem"
            },
            {
                "title": "Back Home",
                "content": "Ben found a small battery in a robot shop. They fixed the machine. Now they are back in their lab. \"What an adventure!\" they said.",
                "image": "images/a2/time/ch5.jpg",
                "color": "#fdf4ff",
                "visual_type": "time_back"
            }
        ],
        "full_dictionary": {
            "professor": "ศาสตราจารย์",
            "inventor": "นักประดิษฐ์",
            "machine": "เครื่องจักร",
            "pressed": "กด",
            "past": "อดีต",
            "knights": "อัศวิน",
            "horses": "ม้า",
            "castles": "ปราสาท",
            "future": "อนาคต",
            "flying cars": "รถบินได้",
            "battery": "แบตเตอรี่",
            "adventure": "การผจญภัย",
            "piff": "พิฟฟ์",
            "lab": "ห้องแล็บ",
            "built": "สร้าง",
            "work": "ทำงาน",
            "red button": "ปุ่มแดง",
            "silver": "เงิน",
            "stopped": "หยุด",
            "shop": "ร้าน",
            "fixed": "ซ่อม",
            "a": "หนึ่ง",
            "amazing": "น่าทึ่ง",
            "an": "หนึ่ง",
            "and": "และ",
            "are": "เป็น/อยู่/คือ",
            "at": "ที่",
            "back": "กลับ",
            "ben": "เบน",
            "buildings": "ตึก/อาคาร",
            "button": "ปุ่ม",
            "cars": "รถยนต์หลายคัน",
            "flying": "กำลังบิน",
            "for": "สำหรับ",
            "found": "พบ (อดีต)",
            "friend": "เพื่อน",
            "go": "ไป",
            "had": "มี (อดีต)",
            "he": "เขา",
            "help": "ช่วย",
            "his": "ของเขา",
            "home": "บ้าน",
            "in": "ใน",
            "it": "มัน",
            "large": "ใหญ่",
            "looked": "ดูเหมือน/มอง (อดีต)",
            "need": "ต้องการ/จำเป็น",
            "next": "ถัดไป",
            "now": "ตอนนี้",
            "on": "บน",
            "people": "ผู้คน",
            "problem": "ปัญหา",
            "red": "สีแดง",
            "robot": "หุ่นยนต์",
            "robots": "หุ่นยนต์หลายตัว",
            "said": "พูด (อดีต)",
            "saw": "เห็น (อดีต)",
            "see": "เห็น",
            "small": "เล็ก",
            "suddenly": "ทันใดนั้น",
            "tall": "สูง",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "their": "ของพวกเขา",
            "them": "พวกเรา (กรรม)",
            "they": "พวกเรา/พวกเขา",
            "time": "เวลา",
            "to": "ถึง/เพื่อ",
            "wanted": "ต้องการ (อดีต)",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "way": "ทาง",
            "we": "พวกเรา",
            "went": "ไป (อดีต)",
            "were": "เป็น/อยู่/คือ (อดีต)",
            "what": "อะไร",
            "working": "กำลังทำงาน"
        }
    },
    {
        "id": "tokyo_summer",
        "title": "A Summer in Tokyo",
        "level": "A2",
        "cover": "images/a2/tokyo/cover.jpg",
        "description": "Mark visited Japan and learned about a new culture.",
        "vocabulary": [
            {
                "word": "Culture",
                "translation": "วัฒนธรรม"
            },
            {
                "word": "Travel",
                "translation": "เดินทาง"
            },
            {
                "word": "Language",
                "translation": "ภาษา"
            },
            {
                "word": "City",
                "translation": "เมือง"
            },
            {
                "word": "Summer",
                "translation": "ฤดูร้อน"
            }
        ],
        "chapters": [
            {
                "title": "Tokyo Station",
                "content": "Mark arrived in Tokyo in July. It was very hot. He saw many people and bright lights. He was excited to be in Japan.",
                "image": "images/a2/tokyo/ch1.jpg",
                "color": "#fffbeb",
                "visual_type": "tokyo_station"
            },
            {
                "title": "Sushi Lunch",
                "content": "For lunch, Mark ate sushi at a small restaurant. It was fresh and delicious. He learned how to use chopsticks.",
                "image": "images/a2/tokyo/ch2.jpg",
                "color": "#f8fafc",
                "visual_type": "tokyo_sushi"
            },
            {
                "title": "The Temple",
                "content": "He visited a very old temple. He saw people wearing traditional clothes. He took many photos of the beautiful gardens.",
                "image": "images/a2/tokyo/ch3.jpg",
                "color": "#f0fdf4",
                "visual_type": "tokyo_temple"
            },
            {
                "title": "Technology",
                "content": "Tokyo has a lot of technology. Mark saw robots in a shop. He also traveled on a very fast train called the Shinkansen.",
                "image": "images/a2/tokyo/ch4.jpg",
                "color": "#eff6ff",
                "visual_type": "tokyo_tech"
            },
            {
                "title": "Saying Goodbye",
                "content": "His trip was over. Mark learned some Japanese words. \"Arigato,\" he said. He had a wonderful summer in Tokyo.",
                "image": "images/a2/tokyo/ch5.jpg",
                "color": "#fefce8",
                "visual_type": "tokyo_bye"
            }
        ],
        "full_dictionary": {
            "arrived": "ถึง",
            "bright lights": "ไฟสว่าง",
            "sushi": "ซูชิ",
            "restaurant": "ร้านอาหาร",
            "delicious": "อร่อย",
            "chopsticks": "ตะเกียบ",
            "temple": "วัด",
            "traditional": "ดั้งเดิม",
            "clothes": "เสื้อผ้า",
            "japanese": "ญี่ปุ่น",
            "wonderful": "มหัศจรรย์",
            "mark": "มาร์ค",
            "tokyo": "โตเกียว",
            "july": "กรกฎาคม",
            "hot": "ร้อน",
            "japan": "ญี่ปุ่น",
            "fresh": "สด",
            "photos": "รูปถ่าย",
            "technology": "เทคโนโลยี",
            "shinkansen": "ชินคันเซ็น",
            "words": "คำ",
            "a": "หนึ่ง",
            "also": "อีกด้วย",
            "and": "และ",
            "arigato": "ขอบคุณ (ภาษาญี่ปุ่น)",
            "at": "ที่",
            "ate": "กิน (อดีต)",
            "be": "เป็น/อยู่/คือ",
            "beautiful": "สวยงาม",
            "bright": "สว่าง",
            "called": "ถูกเรียกว่า",
            "excited": "ตื่นเต้น",
            "fast": "เร็ว",
            "for": "สำหรับ",
            "gardens": "สวนหลายแห่ง",
            "goodbye": "ลาก่อน",
            "had": "มี (อดีต)",
            "has": "มี",
            "he": "เขา",
            "his": "ของเขา",
            "how": "อย่างไร",
            "in": "ใน",
            "it": "มัน",
            "learned": "เรียนรู้ (อดีต)",
            "lights": "ไฟ/แสงสี",
            "lot": "มาก",
            "lunch": "อาหารกลางวัน",
            "many": "มากมาย",
            "of": "ของ",
            "old": "เก่า",
            "on": "บน",
            "over": "เหนือ/ผ่านไปแล้ว",
            "people": "ผู้คน",
            "robots": "หุ่นยนต์หลายตัว",
            "said": "พูด (อดีต)",
            "saw": "เห็น (อดีต)",
            "saying": "การพูด/กำลังพูด",
            "shop": "ร้านค้า",
            "small": "เล็ก",
            "some": "บ้าง",
            "station": "สถานี",
            "summer": "ฤดูร้อน",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "to": "ถึง/เพื่อ",
            "took": "หยิบ/เอาไป (อดีต)",
            "train": "รถไฟ",
            "traveled": "เดินทาง (อดีต)",
            "trip": "การเดินทาง",
            "use": "ใช้",
            "very": "มาก",
            "visited": "เยี่ยมชม (อดีต)",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "wearing": "กำลังสวมใส่"
        }
    },
    {
        "id": "firefighter_hero",
        "title": "The Brave Firefighter",
        "level": "A2",
        "cover": "images/a2/fire/cover.jpg",
        "description": "Leo the firefighter saved a little cat from a tree.",
        "vocabulary": [
            {
                "word": "Firefighter",
                "translation": "นักดับเพลิง"
            },
            {
                "word": "Hero",
                "translation": "ฮีโร่/วีรบุรุษ"
            },
            {
                "word": "Ladder",
                "translation": "บันได"
            },
            {
                "word": "Rescue",
                "translation": "การช่วยเหลือ"
            },
            {
                "word": "Safety",
                "translation": "ความปลอดภัย"
            }
        ],
        "chapters": [
            {
                "title": "At the Station",
                "content": "Leo is a firefighter. He works at a small fire station. He is brave and strong. He wants to keep everyone safe.",
                "image": "images/a2/fire/ch1.jpg",
                "color": "#fef2f2",
                "visual_type": "fire_station"
            },
            {
                "title": "The Alarm",
                "content": "Suddenly, the alarm rang. There was a problem in the park. Leo and his team drove the big red truck quickly.",
                "image": "images/a2/fire/ch2.jpg",
                "color": "#fee2e2",
                "visual_type": "fire_alarm"
            },
            {
                "title": "The Cat",
                "content": "A small cat was high in a tree. It was very scared. A little girl was crying. \"Please help my cat!\" she said.",
                "image": "images/a2/fire/ch3.jpg",
                "color": "#fff7ed",
                "visual_type": "fire_cat"
            },
            {
                "title": "The Rescue",
                "content": "Leo used a long ladder. He climbed up slowly. He took the cat in his arms. Everyone was watching him.",
                "image": "images/a2/fire/ch4.jpg",
                "color": "#f8fafc",
                "visual_type": "fire_rescue"
            },
            {
                "title": "Safe",
                "content": "Leo gave the cat back to the girl. She was very happy. \"Thank you, Leo!\" she said. Leo was a hero in the village.",
                "image": "images/a2/fire/ch5.jpg",
                "color": "#f0fdf4",
                "visual_type": "fire_hero"
            }
        ],
        "full_dictionary": {
            "firefighter": "นักดับเพลิง",
            "safe": "ปลอดภัย",
            "alarm": "สัญญาณเตือน",
            "truck": "รถบรรทุก",
            "quickly": "อย่างรวดเร็ว",
            "scared": "กลัว",
            "crying": "กำลังร้องไห้",
            "ladder": "บันได",
            "arms": "แขน",
            "watching": "กำลังดู",
            "hero": "ฮีโร่",
            "leo": "ลีโอ",
            "works": "ทำงาน",
            "station": "สถานี",
            "brave": "กล้าหาญ",
            "strong": "แข็งแรง",
            "park": "สวน",
            "team": "ทีม",
            "drove": "ขับ",
            "high": "สูง",
            "rescued": "ช่วยชีวิต",
            "gave": "ให้",
            "back": "คืน",
            "a": "หนึ่ง",
            "and": "และ",
            "at": "ที่",
            "big": "ใหญ่",
            "cat": "แมว",
            "climbed": "ปีน (อดีต)",
            "everyone": "ทุกคน",
            "fire": "ไฟ",
            "girl": "เด็กผู้หญิง",
            "happy": "มีความสุข",
            "he": "เขา",
            "help": "ช่วย",
            "him": "เขา (กรรม)",
            "his": "ของเขา",
            "in": "ใน",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "keep": "เก็บ",
            "little": "เล็กน้อย",
            "long": "ยาว",
            "my": "ของฉัน",
            "please": "ได้โปรด",
            "problem": "ปัญหา",
            "rang": "ดัง (อดีต - เสียงกริ่ง)",
            "red": "สีแดง",
            "rescue": "การช่วยเหลือ",
            "said": "พูด (อดีต)",
            "she": "เธอ",
            "slowly": "อย่างช้าๆ",
            "small": "เล็ก",
            "suddenly": "ทันใดนั้น",
            "thank": "ขอบคุณ",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "there": "มี/ที่นั่น",
            "to": "ถึง/เพื่อ",
            "took": "หยิบ/เอาไป (อดีต)",
            "tree": "ต้นไม้",
            "up": "ขึ้น",
            "used": "ใช้ (อดีต)",
            "very": "มาก",
            "village": "หมู่บ้าน",
            "wants": "ต้องการ",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "you": "คุณ"
        }
    },
    {
        "id": "jungle_adventure",
        "title": "Lost in the Jungle",
        "level": "A2",
        "cover": "images/a2/jungle/cover.jpg",
        "description": "Toby explored a deep jungle and found a waterfall.",
        "vocabulary": [
            {
                "word": "Jungle",
                "translation": "ป่าดิบชื้น"
            },
            {
                "word": "Adventure",
                "translation": "การผจญภัย"
            },
            {
                "word": "Waterfall",
                "translation": "น้ำตก"
            },
            {
                "word": "Compass",
                "translation": "เข็มทิศ"
            },
            {
                "word": "Exotic",
                "translation": "แปลกตา"
            }
        ],
        "chapters": [
            {
                "title": "The Expedition",
                "content": "Toby went on an expedition. He had a large backpack and a compass. He wanted to find a hidden waterfall in the jungle.",
                "image": "images/a2/jungle/ch1.jpg",
                "color": "#f0fdf4",
                "visual_type": "jungle_intro"
            },
            {
                "title": "The Monkey",
                "content": "The jungle was very green. Toby saw a small monkey. The monkey was eating a banana. It showed Toby a narrow path.",
                "image": "images/a2/jungle/ch2.jpg",
                "color": "#ecfdf5",
                "visual_type": "jungle_monkey"
            },
            {
                "title": "The River",
                "content": "Toby walked near a wide river. He saw many exotic flowers. They were purple and yellow. He felt like a real explorer.",
                "image": "images/a2/jungle/ch3.jpg",
                "color": "#eff6ff",
                "visual_type": "jungle_river"
            },
            {
                "title": "Found It!",
                "content": "Finally, he heard the sound of water. He found the waterfall! It was very beautiful and high. Toby took many photos.",
                "image": "images/a2/jungle/ch4.jpg",
                "color": "#f8fafc",
                "visual_type": "jungle_waterfall"
            },
            {
                "title": "Campfire",
                "content": "It was evening. Toby built a small campfire. He sat and looked at the stars. The jungle was a wonderful place for adventure.",
                "image": "images/a2/jungle/ch5.jpg",
                "color": "#1e293b",
                "visual_type": "jungle_camp"
            }
        ],
        "full_dictionary": {
            "expedition": "การสำรวจ",
            "backpack": "เป้สะพายหลัง",
            "compass": "เข็มทิศ",
            "hidden": "ที่ซ่อนอยู่",
            "waterfall": "น้ำตก",
            "monkey": "ลิง",
            "narrow path": "ทางแคบ",
            "exotic": "แปลกตา/มาจากต่างถิ่น",
            "explorer": "นักสำรวจ",
            "campfire": "กองไฟ",
            "toby": "โทบี้",
            "jungle": "ป่า",
            "went": "ไป",
            "had": "มี",
            "wanted": "ต้องการ",
            "green": "เขียว",
            "banana": "กล้วย",
            "showed": "แสดง/ชี้ทาง",
            "river": "แม่น้ำ",
            "purple": "ม่วง",
            "yellow": "เหลือง",
            "felt": "รู้สึก",
            "beautiful": "สวยงาม",
            "photos": "รูปภาพ",
            "adventure": "การผจญภัย",
            "a": "หนึ่ง",
            "an": "หนึ่ง",
            "and": "และ",
            "at": "ที่",
            "built": "สร้าง (อดีต)",
            "eating": "กำลังกิน",
            "evening": "ตอนเย็น",
            "finally": "ในที่สุด",
            "find": "หา",
            "flowers": "ดอกไม้หลายดอก",
            "for": "สำหรับ",
            "found": "พบ (อดีต)",
            "he": "เขา",
            "heard": "ได้ยิน (อดีต)",
            "high": "สูง",
            "in": "ใน",
            "it": "มัน",
            "large": "ใหญ่",
            "like": "ชอบ/เหมือน",
            "looked": "ดูเหมือน/มอง (อดีต)",
            "lost": "หาย",
            "many": "มากมาย",
            "narrow": "แคบ",
            "near": "ใกล้",
            "of": "ของ",
            "on": "บน",
            "path": "เส้นทาง",
            "place": "สถานที่",
            "real": "จริง",
            "sat": "นั่ง (อดีต)",
            "saw": "เห็น (อดีต)",
            "small": "เล็ก",
            "sound": "เสียง",
            "stars": "ดวงดาว",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "they": "พวกเรา/พวกเขา",
            "to": "ถึง/เพื่อ",
            "took": "หยิบ/เอาไป (อดีต)",
            "very": "มาก",
            "walked": "เดิน (อดีต)",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "water": "น้ำ",
            "were": "เป็น/อยู่/คือ (อดีต)",
            "wide": "กว้าง",
            "wonderful": "มหัศจรรย์"
        }
    },
    {
        "id": "science_fair",
        "title": "The School Science Fair",
        "level": "A2",
        "cover": "images/a2/science/cover.jpg",
        "description": "Ben and Anna built a cool project for the school fair.",
        "vocabulary": [
            {
                "word": "Science",
                "translation": "วิทยาศาสตร์"
            },
            {
                "word": "Project",
                "translation": "โครงงาน"
            },
            {
                "word": "Experiment",
                "translation": "การทดลอง"
            },
            {
                "word": "Electricity",
                "translation": "ไฟฟ้า"
            },
            {
                "word": "Fair",
                "translation": "งานเทศกาล/นิทรรศการ"
            }
        ],
        "chapters": [
            {
                "title": "The Idea",
                "content": "Next week is the science fair. Ben and Anna wanted to build a cool project. \"Let's make a lemon battery!\" Anna said.",
                "image": "images/a2/science/ch1.jpg",
                "color": "#fefce8",
                "visual_type": "science_idea"
            },
            {
                "title": "Preparation",
                "content": "They bought five lemons and some copper wire. They worked together in the classroom. Their teacher, Mr. Jones, helped them.",
                "image": "images/a2/science/ch2.jpg",
                "color": "#f8fafc",
                "visual_type": "science_prep"
            },
            {
                "title": "The Experiment",
                "content": "They connected the wires to the lemons. Suddenly, a small light bulb turned on. \"It works!\" Ben cheered. Science was fun.",
                "image": "images/a2/science/ch3.jpg",
                "color": "#fdfcf0",
                "visual_type": "science_work"
            },
            {
                "title": "The Presentation",
                "content": "On Friday, the school hall was full of people. Many parents came to see the projects. Ben and Anna explained their lemon battery.",
                "image": "images/a2/science/ch4.jpg",
                "color": "#eff6ff",
                "visual_type": "science_fair_hall"
            },
            {
                "title": "Winning",
                "content": "The judges liked their experiment. They won a small trophy. Ben and Anna were very proud of their science project.",
                "image": "images/a2/science/ch5.jpg",
                "color": "#f0fdf4",
                "visual_type": "science_winner"
            }
        ],
        "full_dictionary": {
            "science fair": "งานนิทรรศการวิทยาศาสตร์",
            "project": "โครงงาน",
            "lemon battery": "แบตเตอรี่มะนาว",
            "copper wire": "สายทองแดง",
            "classroom": "ห้องเรียน",
            "light bulb": "หลอดไฟ",
            "cheered": "โห่ร้องยินดี",
            "presentation": "การนำเสนอ",
            "hall": "หอประชุม",
            "explained": "อธิบาย",
            "trophy": "ถ้วยรางวัล",
            "ben": "เบน",
            "anna": "แอนนา",
            "wanted": "ต้องการ",
            "build": "สร้าง",
            "bought": "ซื้อ",
            "together": "ด้วยกัน",
            "teacher": "ครู",
            "connected": "เชื่อมต่อ",
            "turned on": "เปิด/ติด",
            "full": "เต็ม",
            "parents": "ผู้ปกครอง",
            "judges": "กรรมการ",
            "won": "ชนะ",
            "proud": "ภูมิใจ",
            "a": "หนึ่ง",
            "and": "และ",
            "battery": "แบตเตอรี่",
            "bulb": "หลอดไฟ",
            "came": "มา (อดีต)",
            "cool": "เจ๋ง",
            "copper": "ทองแดง",
            "experiment": "การทดลอง",
            "fair": "งานเทศกาล/งานนิทรรศการ",
            "five": "ห้า",
            "friday": "วันศุกร์",
            "fun": "สนุก",
            "helped": "ช่วย (อดีต)",
            "idea": "ความคิด",
            "in": "ใน",
            "is": "เป็น/อยู่/คือ",
            "it": "มัน",
            "jones": "โจนส์",
            "lemon": "มะนาว",
            "lemons": "มะนาวหลายลูก",
            "let's": "กันเถอะ",
            "light": "ไฟ/แสง",
            "liked": "ชอบ (อดีต)",
            "make": "ทำ",
            "many": "มากมาย",
            "mr": "นาย",
            "next": "ถัดไป",
            "of": "ของ",
            "on": "บน",
            "people": "ผู้คน",
            "preparation": "การเตรียมตัว",
            "projects": "โครงงานหลายอย่าง",
            "said": "พูด (อดีต)",
            "school": "โรงเรียน",
            "science": "วิทยาศาสตร์",
            "see": "เห็น",
            "small": "เล็ก",
            "some": "บ้าง",
            "suddenly": "ทันใดนั้น",
            "the": "คำนำหน้า (ระบุเจาะจง)",
            "their": "ของพวกเขา",
            "them": "พวกเรา (กรรม)",
            "they": "พวกเรา/พวกเขา",
            "to": "ถึง/เพื่อ",
            "turned": "เปลี่ยน/หมุน",
            "very": "มาก",
            "was": "เป็น/อยู่/คือ (อดีต)",
            "week": "สัปดาห์",
            "were": "เป็น/อยู่/คือ (อดีต)",
            "winning": "ชนะ/กำลังชนะ",
            "wire": "สายไฟ",
            "wires": "สายไฟหลายเส้น",
            "worked": "ทำงาน (อดีต)",
            "works": "ทำงาน"
        }
    }
];
window.CURRENT_LEVEL_DATA = A2_STORIES;
