// --- STORIES_DATA - VERSION 5.1 (FIXED & FULL CONTENT) ---
const STORIES_DATA = {
    "A1": [
        {
            "id": "lost_key", "title": "The Lost Key", "level": "A1", "cover": "images/lost_key/cover.svg", "description": "A mysterious discovery in an old garden.",
            "vocabulary": [{"word":"Key","translation":"กุญแจ"},{"word":"Lost","translation":"หาย"},{"word":"Find","translation":"หา"},{"word":"Garden","translation":"สวน"},{"word":"Box","translation":"กล่อง"}],
            "chapters": [
                { "title": "The Small Box", "content": "Tom is at home. He lives in a small house. Today, he finds an old box. The box is beautiful, but it is closed. Tom wants to open the box. He looks for a key. \"Where is the key?\" he asks. The key is lost. He needs to find it.", "image": "images/lost_key/ch1.svg", "color": "#fef9c3", "visual_type": "box" },
                { "title": "Looking in the Garden", "content": "Tom goes to the garden. The garden is big and green. He looks under a big tree. He looks inside the grass. He is looking for the small key. \"Is the key here?\" he asks. He cannot find the lost key. He is not happy. He looks at the old house again.", "image": "images/lost_key/ch2.svg", "color": "#f0fdf4", "visual_type": "garden" },
                { "title": "A Helping Friend", "content": "Anna is Tom's friend. She comes to the house. \"Can I help you?\" Anna asks. Tom says, \"Yes, please. My key is lost. I want to open my old box.\" Anna and Tom look in the garden together. They look near the old door. They want to find the small key.", "image": "images/lost_key/ch3.svg", "color": "#eff6ff", "visual_type": "friends" },
                { "title": "The Gold Key", "content": "Anna looks under a small rock near the tree. \"Look!\" she says. She finds a small gold key. It is very beautiful. Tom is very happy. \"You find the lost key!\" he says. Now they can open the box. They go back into the house.", "image": "images/lost_key/ch4.svg", "color": "#fff7ed", "visual_type": "gold_key" },
                { "title": "The Secret Inside", "content": "Tom puts the gold key in the box. He can open it now. Inside the box, there is a secret. It is a small map of the garden. \"This is a beautiful secret,\" Anna says. Tom and his friend are very happy. They find the lost key and the secret.", "image": "images/lost_key/ch5.svg", "color": "#faf5ff", "visual_type": "map" }
            ],
            "full_dictionary": {"tom":"ทอม","is":"เป็น/คือ/อยู่","at":"ที่","home":"บ้าน","he":"เขา","lives":"อาศัยอยู่","in":"ใน","a":"หนึ่ง","small":"เล็ก","house":"บ้าน","today":"วันนี้","finds":"พบ/เจอ","an":"หนึ่ง","old":"เก่า","box":"กล่อง","the":"คำนำหน้า","beautiful":"สวยงาม","but":"แต่","it":"มัน","closed":"ปิดอยู่","wants":"ต้องการ","to":"ที่จะ","open":"เปิด","looks":"มองหา","for":"สำหรับ","key":"กุญแจ","where":"ที่ไหน","asks":"ถาม","lost":"หาย","needs":"จำเป็นต้อง","find":"หา","it":"มัน","goes":"ไป","garden":"สวน","big":"ใหญ่","and":"และ","green":"สีเขียว","under":"ใต้","tree":"ต้นไม้","inside":"ข้างใน","grass":"หญ้า","looking":"กำลังมองหา","here":"ที่นี่","cannot":"ไม่สามารถ","happy":"มีความสุข","not":"ไม่","again":"อีกครั้ง","anna":"แอนนา","friend":"เพื่อน","she":"เธอ","comes":"มา","can":"สามารถ","i":"ฉัน","help":"ช่วย","you":"คุณ","says":"พูด/บอก","yes":"ใช่","please":"ได้โปรด","my":"ของฉัน","together":"ด้วยกัน","they":"พวกเขา","near":"ใกล้","door":"ประตู","rock":"หิน","look":"ดู/มอง","gold":"ทอง","very":"มาก","back":"กลับ","into":"เข้าไปใน","puts":"วาง/ใส่","now":"ตอนนี้","there":"มี","secret":"ความลับ","map":"แผนที่","this":"นี่/นี้","his":"ของเขา","am":"เป็น","are":"เป็น","was":"เคยเป็น","were":"เคยเป็น"}
        },
        {
            "id": "secret_bakery", "title": "The Secret Bakery", "level": "A1", "cover": "images/bakery/cover.svg", "description": "The mysterious shop with no baker.",
            "vocabulary": [{"word":"Bakery","translation":"ร้านขนมปัง"},{"word":"Bread","translation":"ขนมปัง"},{"word":"Smell","translation":"กลิ่น"},{"word":"Oven","translation":"เตาอบ"},{"word":"Sugar","translation":"น้ำตาล"}],
            "chapters": [
                { "title": "The Sweet Smell", "content": "Every morning, the village smells sweet. It is the smell of fresh bread. There is a small bakery in the village. Everybody loves the bread, but nobody sees the baker. It is a big secret.", "image": "images/bakery/ch1.svg", "color": "#fffbeb", "visual_type": "bakery_exterior" },
                { "title": "The Blue Door", "content": "Mia is a small girl. She likes the bakery. One day, she sees a blue door behind the shop. The door is very small. Mia wants to see inside. \"Is the baker there?\" she asks.", "image": "images/bakery/ch2.svg", "color": "#f0f9ff", "visual_type": "blue_door" },
                { "title": "Inside the Bakery", "content": "Mia opens the blue door. Inside, she sees a big oven. It is very hot. She sees flour and sugar on the table. But the room is empty. The bread is in the oven, but there is no baker.", "image": "images/bakery/ch3.svg", "color": "#fff1f2", "visual_type": "oven" },
                { "title": "A Little Magic", "content": "Suddenly, Mia hears a sound. A small bird flies from the oven. The bird has a tiny hat. The bird is the baker! It uses a little magic to make the sweet bread. Mia is very surprised.", "image": "images/bakery/ch4.svg", "color": "#fdf4ff", "visual_type": "bird_baker" },
                { "title": "The Baker's Gift", "content": "The bird-baker gives Mia a small cake. It is warm and sweet. Mia keeps the secret. Now, every morning, she visits the blue door. She and her magic friend make bread for the village together.", "image": "images/bakery/ch5.svg", "color": "#fff7ed", "visual_type": "cake" }
            ],
            "full_dictionary": {"every":"ทุกๆ","morning":"เช้า","village":"หมู่บ้าน","smells":"ส่งกลิ่น","sweet":"หอมหวาน","it":"มัน","is":"เป็น/คือ/อยู่","smell":"กลิ่น","of":"ของ","fresh":"สดใหม่","bread":"ขนมปัง","there":"มี","small":"เล็ก","bakery":"ร้านขนมปัง","everybody":"ทุกคน","loves":"รัก/ชอบ","but":"แต่","nobody":"ไม่มีใคร","sees":"เห็น","baker":"คนทำขนมปัง","big":"ใหญ่","secret":"ความลับ","mia":"เมีย","girl":"เด็กผู้หญิง","she":"เธอ","likes":"ชอบ","one":"หนึ่ง","day":"วัน","blue":"สีน้ำเงิน","door":"ประตู","behind":"ข้างหลัง","shop":"ร้าน","wants":"ต้องการ","see":"เห็น/ดู","inside":"ข้างใน","asks":"ถาม","opens":"เปิด","oven":"เตาอบ","hot":"ร้อน","flour":"แป้ง","sugar":"น้ำตาล","on":"บน","table":"โต๊ะ","room":"ห้อง","empty":"ว่างเปล่า","no":"ไม่มี","suddenly":"ทันทีทันใด","hears":"ได้ยิน","sound":"เสียง","bird":"นก","flies":"บิน","from":"จาก","has":"มี","tiny":"เล็กจิ๋ว","hat":"หมวก","uses":"ใช้","little":"เล็กน้อย","magic":"เวทมนตร์","make":"ทำ","surprised":"ประหลาดใจ","gives":"ให้","cake":"เค้ก","warm":"อบอุ่น","keeps":"เก็บ","now":"ตอนนี้","visits":"เยี่ยมชม","her":"ของเธอ","friend":"เพื่อน","together":"ด้วยกัน","the":"คำนำหน้า","in":"ใน"}
        },
        {
            "id": "magic_park", "title": "The Magic Park", "level": "A1", "cover": "images/park/cover.svg", "description": "Colors change when Leo moves in the park.",
            "vocabulary": [{"word":"Park","translation":"สวนสาธารณะ"},{"word":"Bird","translation":"นก"},{"word":"Flower","translation":"ดอกไม้"},{"word":"Green","translation":"สีเขียว"},{"word":"Happy","translation":"มีความสุข"}],
            "chapters": [
                { "title": "Leo's Park", "content": "Leo goes to the park. The sun is hot. The sky is blue. He sees a big tree. Under the tree, there is a green bird. Leo is happy.", "image": "images/park/ch1.svg", "color": "#f0fdf4", "visual_type": "magic_park_intro" },
                { "title": "The Green Grass", "content": "Leo runs on the grass. Suddenly, the grass is very green. He jumps up and down. He sees red flowers. They are beautiful.", "image": "images/park/ch2.svg", "color": "#ecfdf5", "visual_type": "green_grass" },
                { "title": "A White Heart", "content": "Leo looks at the sky. He sees a white cloud. The cloud is small. Suddenly, it is a heart! The sky is very blue now.", "image": "images/park/ch3.svg", "color": "#eff6ff", "visual_type": "heart_cloud" },
                { "title": "Playing Ball", "content": "Leo has a red ball. He plays with a dog. The dog is his friend. They play under the sun. The park is magic.", "image": "images/park/ch4.svg", "color": "#fff1f2", "visual_type": "playing_dog" },
                { "title": "Yellow Sun", "content": "Now it is evening. The sun is yellow. Leo goes home. He is tired but happy. He wants to visit the park again.", "image": "images/park/ch5.svg", "color": "#fffbeb", "visual_type": "sunset_park" }
            ],
            "full_dictionary": {"leo":"ลีโอ","goes":"ไป","park":"สวนสาธารณะ","sun":"ดวงอาทิตย์","hot":"ร้อน","sky":"ท้องฟ้า","blue":"สีน้ำเงิน","sees":"เห็น","tree":"ต้นไม้","under":"ใต้","there":"มี","green":"สีเขียว","bird":"นก","happy":"มีความสุข","runs":"วิ่ง","on":"บน","grass":"หญ้า","suddenly":"ทันทีทันใด","jumps":"กระโดด","up":"ขึ้น","down":"ลง","red":"สีแดง","flowers":"ดอกไม้","beautiful":"สวยงาม","looks":"มอง","at":"ที่","white":"สีขาว","cloud":"เมฆ","heart":"หัวใจ","ball":"ลูกบอล","plays":"เล่น","with":"กับ","dog":"สุนัข","evening":"ตอนเย็น","yellow":"สีเหลือง","home":"บ้าน","tired":"เหนื่อย","visit":"เยี่ยมชม","again":"อีกครั้ง","is":"เป็น","he":"เขา","the":"คำนำหน้า","now":"ตอนนี้","has":"มี","it":"มัน"}
        }
    ],
    "A2": [
        {
            "id": "brave_knight", "title": "The Brave Knight", "level": "A2", "cover": "images/knight/cover.png", "description": "Sir Leo was a brave knight who met a dragon.",
            "vocabulary": [{"word":"Knight","translation":"อัศวิน"},{"word":"Brave","translation":"กล้าหาญ"},{"word":"Castle","translation":"ปราสาท"},{"word":"Strange","translation":"แปลก"},{"word":"Dragon","translation":"มังกร"}],
            "chapters": [
                { "title": "The Knight", "content": "Sir Leo lived in a very old castle. The castle was made of large stones. He was a brave knight. He had a shining sword.", "image": "images/knight/ch1.png", "color": "#f1f5f9", "visual_type": "knight_castle" },
                { "title": "Strange Sound", "content": "Last night, he heard a strange sound from the dark forest. It was loud and heavy. He held his sword and went into the forest.", "image": "images/knight/ch2.png", "color": "#1e293b", "visual_type": "knight_forest" },
                { "title": "The Cave", "content": "Deep in the forest, Sir Leo found a large cave. Inside, there was a big dragon. It looked sad, not angry. It had a thorn in its wing.", "image": "images/knight/ch3.png", "color": "#450a0a", "visual_type": "knight_dragon" },
                { "title": "Helping", "content": "Sir Leo put his sword down. He walked slowly. \"I want to help you,\" he said. He pulled the thorn out. The dragon felt better.", "image": "images/knight/ch4.png", "color": "#fefce8", "visual_type": "knight_help" },
                { "title": "Friends", "content": "The dragon and the knight became friends. Now, the village was even safer. Sir Leo was a brave knight with a magic friend.", "image": "images/knight/ch5.png", "color": "#eff6ff", "visual_type": "knight_friends" }
            ],
            "full_dictionary": {"sir":"ท่าน","leo":"ลีโอ","lived":"อาศัยอยู่","old":"เก่า","castle":"ปราสาท","made":"ทำจาก","large":"ใหญ่","stones":"หิน","brave":"กล้าหาญ","knight":"อัศวิน","had":"มี","shining":"สว่าง","sword":"ดาบ","last":"ที่แล้ว","night":"คืน","heard":"ได้ยิน","strange":"แปลก","sound":"เสียง","forest":"ป่า","loud":"ดัง","heavy":"หนัก","held":"ถือ","went":"ไป","deep":"ลึก","found":"พบ","cave":"ถ้ำ","dragon":"มังกร","looked":"ดูเหมือน","sad":"เศร้า","angry":"โกรธ","thorn":"หนาม","wing":"ปีก","put":"วาง","down":"ลง","slowly":"อย่างช้าๆ","said":"พูด","pulled":"ดึง","out":"ออก","better":"ดีขึ้น","became":"กลายเป็น","friends":"เพื่อน","safer":"ปลอดภัยกว่า","magic":"เวทมนตร์"}
        }
    ],
    "B1": [
        {
            "id": "green_hero", "title": "The Green Hero", "level": "B1", "cover": "images/green/cover.png", "description": "Alex started a recycling project to save the city park.",
            "vocabulary": [{"word":"Environment","translation":"สิ่งแวดล้อม"},{"word":"Recycle","translation":"รีไซเคิล"},{"word":"Pollution","translation":"มลพิษ"},{"word":"Community","translation":"ชุมชน"},{"word":"Sustainability","translation":"ความยั่งยืน"}],
            "chapters": [
                { "title": "A Messy Park", "content": "Alex has lived in this city for ten years. Recently, he has noticed a lot of pollution in the local park. People throw plastic bottles and paper everywhere. He felt very sad about the environment.", "image": "images/green/ch1.png", "color": "#f0fdf4", "visual_type": "green_pollution" },
                { "title": "The Great Idea", "content": "\"We must do something!\" Alex thought. He decided to start a recycling campaign. He has already talked to his school principal and his neighbors. Most people have agreed to help him.", "image": "images/green/ch2.png", "color": "#ecfdf5", "visual_type": "green_idea" },
                { "title": "Community Action", "content": "Last Saturday, the community worked together. They collected five hundred bags of waste. Alex has organized different bins for plastic, glass, and paper. It was a huge success for sustainability.", "image": "images/green/ch3.png", "color": "#dcfce7", "visual_type": "green_action" },
                { "title": "Visible Impact", "content": "The park has never looked better. The grass is green, and the flowers are blooming again. If we work together, we can protect our planet. Many children have started to join the Green Club.", "image": "images/green/ch4.png", "color": "#bbf7d0", "visual_type": "green_impact" },
                { "title": "Future Plans", "content": "Alex hasn't finished his mission yet. He wants to plant one hundred new trees next month. If he gets more support, he will build a small garden for everyone. He is a true green hero.", "image": "images/green/ch5.png", "color": "#86efac", "visual_type": "green_hero" }
            ],
            "full_dictionary": {"alex":"อเล็กซ์","has":"มี/ได้","lived":"อาศัยอยู่","in":"ใน","this":"นี้","city":"เมือง","for":"เป็นเวลา","ten":"สิบ","years":"ปี","recently":"เมื่อเร็วๆ นี้","he":"เขา","noticed":"สังเกตเห็น","a lot of":"จำนวนมาก","pollution":"มลภาวะ","environment":"สิ่งแวดล้อม","people":"ผู้คน","throw":"ทิ้ง/ขว้าง","plastic":"พลาสติก","bottles":"ขวด","paper":"กระดาษ","everywhere":"ทุกที่","felt":"รู้สึก","very":"มาก","sad":"เศร้า","about":"เกี่ยวกับ","we":"พวกเรา","must":"ต้อง","do":"ทำ","something":"บางอย่าง","thought":"คิด","decided":"ตัดสินใจ","start":"เริ่ม","recycling":"การรีไซเคิล","campaign":"การรณรงค์","already":"แล้ว","talked":"พูดคุย","to":"กับ","his":"ของเขา","school":"โรงเรียน","principal":"ครูใหญ่","and":"และ","neighbors":"เพื่อนบ้าน","most":"ส่วนใหญ่","agreed":"เห็นด้วย","help":"ช่วย","him":"เขา","last":"ที่แล้ว","saturday":"วันเสาร์","community":"ชุมชน","worked":"ทำงาน","together":"ด้วยกัน","they":"พวกเขา","collected":"รวบรวม","five hundred":"ห้าส้อย","bags":"ถุง","waste":"ขยะ","organized":"จัดระเบียบ","different":"ที่แตกต่าง","bins":"ถังขยะ","glass":"แก้ว","it":"มัน","was":"เป็น","huge":"ใหญ่โต","success":"ความสำเร็จ","sustainability":"ความยั่งยืน","park":"สวนสาธารณะ","never":"ไม่เคย","looked":"ดูเหมือน","better":"ดีขึ้น","grass":"หญ้า","green":"เขียว","flowers":"ดอกไม้","blooming":"กำลังบาน","again":"อีกครั้ง","if":"ถ้า","can":"สามารถ","protect":"ปกป้อง","our":"ของเรา","planet":"โลก","many":"มากมาย","children":"เด็กๆ","started":"เริ่ม","join":"เข้าร่วม","club":"ชมรม","hasn't":"ยังไม่","finished":"เสร็จสิ้น","mission":"ภารกิจ","yet":"ยัง","wants":"ต้องการ","plant":"ปลูก","one hundred":"หนึ่งร้อย","new":"ใหม่","trees":"ต้นไม้","next":"ถัดไป","month":"เดือน","gets":"ได้รับ","more":"มากขึ้น","support":"การสนับสนุน","will":"จะ","build":"สร้าง","garden":"สวน","everyone":"ทุกคน","is":"เป็น","true":"ที่แท้จริง","hero":"ฮีโร่"}
        }
    ],
    "B2": [],
    "C1": [],
    "C2": []
};
